### PR TITLE
Changes Box's Bar to add a stage, slots, and make better use of the space.

### PR DESCRIPTION
**Pull request by RaccoonBro**
[box][discussion]

image

Main changes are:
- A new stage was added, finally giving Box a theatre after 7 years without
- Two slot machines were added, along with an ATM
- Adds a maint access point to the Bar
- Moves the disposal outlet for the Bartender from the backroom to the bar itself
- The kitchen backroom was slightly shrunk, but loses no functionality
- The boxing ring loses its direct maint access, but you can always go through the holodeck or go to sec maint anyway

Main concern is that the Bartender's vision is slightly reduced. They still can see most of the bar, but there's no good way to position the bar to gain any real visibility.

:cl:
 * rscadd: The bar on Box has been updated to include a stage and shift things around a bit.

### CODE REVIEW

**Comment by SonixApache** [comment]
I refuse to believe that it's been seven years.

**Comment by GreatBigFailure** [comment]
I still think you should give the bartender some version of a shutter switch to cut the stage off visually. A lot of bartenders see comfy construction as part of the job and if the clown is being particularly messy that shift it could get in the way.
Besides that it looks great. I like the potential for RP the stage creates. Also usable as a second shop in a very busy area if the stage isn't being used.

**Comment by RaccoonBro** [comment]
> I refuse to believe that it's been seven years.

5-6 years. Bar hasn't had a stage on this server since at the latest early 2015.

**Comment by RaccoonBro** [comment]
@GreatBigFailure I'm not sure where those shutters would go. Could shutter off the bar itself pretty easily but it wouldn't accomplish anything besides locking the bartender in. I was considering using smartglass for the stage, but curtains make more sense (and I'm lazy)

**Comment by RaccoonBro** [comment]
moved that air alarm by the bathrooms over to the south east of the bar near where it used to be. originally moved it when i slapped slots in that area for a time

**Comment by Kurfursten** [comment]
stage removed in #2936

**Comment by GreatBigFailure** [comment]
Curtains are probably enough then. I guess if it's a real issue the bartender can always construct a wall, they'd have the materials in that situation anyway.

**Comment by bungofungo** [comment]
I would move the piano into the theater stage itself, and put those slot machines in place of the piano location. I would also either move the juke there with them, or against the wall under the entertainment monitor at the top of the bar. This is severe bartending autism but things like arcades/slot machines should never be in a spot where the person operating them blocks an airlock, makes a lot of awkward pushing through people to get to seating situations. Those little slots at the topside entrance could be better put to use for vending machines or something

**Comment by RaccoonBro** [comment]
implemented the changes @bungofungo suggested, it does work a bit better now.

**Comment by FlintBarrel** [comment]
That juke placement really triggers my autism, and so does the reinforced tables being non-continuous to the wall. I dunno, it just looks awkward, and no other bar has it open like that.

**Comment by RaccoonBro** [comment]
I'm not sure of any better place to have it is the problem, it either blocks stuff, is oddly placed, or nobody at the bar can read when a song changes.

**Comment by DeityLink** [comment]
replace those chairs in front of the stage with sofas stat

**Comment by Exxion** [comment]
You *could* put a table under the juke there but it would be a tad immersion-breaking

**Comment by ShiftyRail** [comment]
Box's bar is way too big as it is IMO. It's hard to renovate it and it makes it too empty.

**Comment by RaccoonBro** [comment]
I have a few ideas on shrinking the bar, but that would be a pretty radical change from the point of this PR. Would be a good idea in the future, could probably move the stage down and expand the boxing ring area to add fitness equipment.

**Comment by Kammerjunk** [comment]
I want to be able to toggle all the curtains at once but that's not necessarily in the scope of this PR
would be nice though.

**Comment by FlintBarrel** [comment]
Personally i somewhat enjoy the big bar, you can do some mural type stuff you cant do elsewhere, along with some gimmick themed bars so that's kinda sad. But i guess we do atleast have roid's big bar, so whatever.

**Comment by ComradeDispenser** [comment]
What if you put the juke over by the slot machines?

**Comment by RaccoonBro** [comment]
Nobody at the bar would be able to hear track changes is the main problem with that

**Comment by Kurfursten** [comment]
Is this good to go or are you still taking feedback?

**Comment by RaccoonBro** [comment]
It's good to go, all tested n everything. May just make the jukebox broadcast track info over the entire area and shift it over somewhere else, but that's for another day.

**Pull request merged**
