### PR TITLE
New Splashscreen for Lobby

### PR DESCRIPTION
**Pull request by smalIboss**
## What this does
title23

## Why it's good

This was made as a gift by my asian/chinese friend who knows that I really play this game, he has already done work for our community and he is a big fan. This was specifically done as a splashscreen piece, with everything perfectly structured to make it a good and iconic image.
How it looks in lobby:
grafik

## Changelog

:cl:
 * rscadd: New splashscreen.

### CODE REVIEW

**Comment by Eneocho** [comment]
Sovl.

**Comment by WindowsErrors** [comment]
there's so much going on in this picture that you need AI upscaling in order to understand the majority of the details

**Comment by adacovsk** [comment]
I really don't want to look at a black man, the furry shit is enough

**Comment by d3athrow** [comment]
amazing

**Comment by Eneocho** [comment]
That reminds me, I still gotta finish the "Supermatter Sneed" splash screen.

**Comment by adacovsk** [comment]
> That reminds me, I still gotta finish the "Supermatter Sneed" splash screen.

no

**Comment by smalIboss** [comment]
> I really don't want to look at a black man, the furry shit is enough

im trying to get our repo unmarked by bringing in diversity, be thankful

**Comment by cloutcode** [comment]
trillstation1300... home

**Comment by kernikov** [comment]
It needs to say /vg/station on it somewhere

**Comment by ShiftyRail** [comment]
Good but needs to say /vg/station on it somewhere like kern said

**Comment by Kurfursten** [comment]
I agree that it should say /vg/station, but I also know smallboss moves so slow that it's probably more productive to just ask him to PR the new version separately in 2 weeks.

**Comment by Eneocho** [comment]
I can make a quick no effort variant if you want. With impact font and jpeg compression.

**Pull request merged**
