### PR TITLE
Friendly Fire 2: NT Boogaloo

### PR DESCRIPTION
**Pull request by Irradiation**
With the advent of security getting an RPG in their armory's secure locker, NT isn't free from the joys of friendly fire and collateral damage. Please don't bully.

:cl:
 * rscadd: The armory on Boxstation now has an RPG. Enjoy your friendly fire exercises, security.

### CODE REVIEW

**Comment by SonixApache** [comment]
💣

**Comment by AutismSpider** [comment]
looks fine to me

**Comment by Kammerjunk** [comment]
There are only so many synonyms for "mistake" and they are insufficient for this PR

**Comment by Irradiation** [comment]
I'm deleting the PR tomorrow, don't worry.

**Comment by ShiftyRail** [comment]
My heart says yes but my mind says no

**Comment by Cockswain** [comment]
I can't see anything that could possibly go wrong with this. I say we merge this this very moment.

**Comment by Accipitermaris** [comment]
it's in the locked locker which requires an emag at least
bolted down lockers are pretty robust

**Comment by SonixApache** [comment]
It'd be fine if we had stun, airsoft or EMP rockets.

**Comment by ShiftyRail** [comment]
He actually did it

**Comment by MusgardTiger** [comment]
revert this

better yet don't merge meme pr's in the first place wew

**Comment by GreenHairedAssistantRickysSmellyDick** [comment]
revert this
(carefully press enter twice to assure that i enter a new line like my favourite website reddit.com)
i dont even play the game anymore and im angry

**Pull request merged**
