### PR TITLE
Inaprovaline's metabolism has been buffed to 0.1

### PR DESCRIPTION
**Pull request by Irradiation**
It's amazing how the chem that's meant to stabilize people during crit long enough to reach medical treatment has a metabolism of 0.5. That's right, ZERO POINT FIVE. That means that a 15u Inaprovaline syringe from an O2 kit will barely keep a person alive for 60 seconds. To put things in pespective, regular food chems, like Doctor Delight, metabolizes at 0.4, which is roughly 75 seconds for 5u (Your average autoinjector).

EDIT: Changed the metabolism to 0.2. Should we go further to 0.25 or just make it 0.3 instead?

:cl:
 * tweak: Inaprovaline's metabolism has been slowed down to 0.2, down from 0.5.

### CODE REVIEW

**Comment by Probe1** [comment]
"regular food chems"

**Comment by bathosbathtime** [comment]
I don't think I've ever seen anyone else use Inaprovaline, and the few times I've used it myself was for the painkiller effects it has, and not for the fact that it stabilizes the patient.  The problem I see with it is that in order for you to use it, you have to go to a locker, hope a medical kit spawned in the locker, take out the syringe, and inject the chemical three times for ~60 seconds of stability.  All of that could be time spent taking the patient to medbay instead.  It is further made moot by cloning and the fact that it is outclassed by Dexalin+ due to how critical condition works in the game.

Though I would be happy with it being at 0.1 to have it used more, I will agree that a 0.2 or 0.3 per tick metabolism would be more 'balanced.'

I also don't see the need for making a new chemical that will either still be outclassed by Dexalin+ still or that will also outclass Inaprovline as Dexalin+ already serves that function.  Having three chemicals that do the same thing (keeping someone in critical condition alive longer) seems like an odd direction to go in, even if they very in strength.

**Comment by Irradiation** [comment]
True enough, I may be taking things far, but an actual extreme would be a metabolism of 0.01 or something. Regardless, 0.2 or 0.3, as 0.4 is still too fast for its usage.

Also screw that, we're not making a new chem when Dexalin+ and Dexalin already exist, with the former being THE chem to use for stabilizing dying patients.

**Comment by Irradiation** [comment]
@Intigracy IT WAS MERELY A RUSE. In all seriousness, metabolism might as well might be 1.5, since it's out of you so fast you barely noticed you injected it into yourself.

**Comment by Pathid** [comment]
@bathosbathtime 

Well the role of inaprov is a substitute for something more specialized. It does at least three things: stabilizes oxyloss, slows bleeding to the same degree bicaridine does, and gives that minor pain relief. It's something I'm using pretty much constantly as a medborg since of course they get a hypo with a replenishing supply. Sleepers also have this, even for people in crit when they won't dispense other chems. NanoMeds have it too. The syringe in the blue medkits though, it is kind of puzzling what that's for when it's only worth 60 seconds. Though it does negate that pain slowdown like you said, which is something.

**Comment by Waismuth** [comment]
Isn't dex+ better in stabilizing crit patients, though?

**Comment by Irradiation** [comment]
@Waismuth Absolutely. But does the average stationer have access to chemistry or a fridge to stock up on Dexalin+?  No, of course not, which is when you're forced to turn to the O2 lockers if you want to save someone's/your life. Then you realize that the time you took injecting the 15u Inaprovaline could have been better used dragging someone to a medical center.

**Comment by Probe1** [comment]
That's entirely the point.  You have about 20 medkits of inaprovaline in the halls from lockers.  Each kit has what 60-80 units of inaprovaline?  That's more than enough time to take someone to Medbay to treat them.

Inaprov is a low level emergency stabilizer to help you get a crit guy to Medbay.  If you need more than 5+ minutes you'd get from a single medkit to do that then they're dying from their normal problems anyway.

**Comment by Irradiation** [comment]
Last time I saw O2 aid kits, they contained 4 Dexalin pills, 1 15u inaprov *syringe*, 1 autoinjector and 1 health analyzer, you only get 15u Inaprovaline per kit, as opposed to 60-80u per kit as you say.

Here's another idea to replace the mtabolism buff: what if we replaced the syringe of Inaprovaline with an actual Inaprovaline pill? It'd keep its current metabolism but you wouldn't lose precious time by doing a triple injection.

**Comment by Probe1** [comment]
Split the difference and replace two dexalin pills with two inaprov pills

**Comment by Unknown-as-Captain** [comment]
@Probe1 
firefox_2018-04-04_15-28-52

Let's put our brains to the ringer here.
Does anyone actually use Inaprovaline for anything except making tricord? No, because it fucking sucks.
Will giving it a low metabolism make it OP? No, because it still fucking sucks.
It only prevents respiration damage from being in crit, not from blood loss. And even then, big whoop! Any defib clears that oxygen damage anyways, in fact inaprovaline is more deadly for you because it allows your blood to drain for longer and your toxins to accumulate for longer if that's what was killing you.
Fuck outta here with that arbitrary 0.3

**Comment by Irradiation** [comment]
What if I still buffed Inaprovaline's metabolism to 0.2/0.3 and replaced the inaprovaline syringes in O2 kits with pills instead?

**Comment by Probe1** [comment]
No.

**Comment by Unknown-as-Captain** [comment]
Go out and ask 100 players if they think Inaprovaline metabolism should be lowered to 0.2 and most will be surprised that it wasn't 0.2 already.

If you personally disagree with this PR you tag it controversial. "Needs fixing" is collab abuse because this is abso fucking lutely not what that tag is about.
You're not Pomf to be vetoing relatively small changes like this

**Comment by Probe1** [comment]
Wildly buffing basic chems because you're annoyed about first aid kits is not happening.

**Comment by DrCelt** [comment]
@Irradiation might be easier to add an extra inaprov syringe to the o2 kit than talk all day about whether 0.1 or 0.5 or 0.3 or 0.4 is a better metabolism

**Comment by Allspice** [comment]
Panthid touched on this, but to make it explicit: Inaprov slows internal bleeding to a near-standstill.

**Comment by Kammerjunk** [comment]
Whether it does one or the other, "more more more" is a silly train of thought. If you must add a reagent, add one specifically for reducing the rate of internal bleeding and just let inaprov into the insanely OP 0.2u-metabolism club shared with anti-tox, dex+, tricord, kelotane, and the base reagent all reagents inherit from

**Comment by Kammerjunk** [comment]
By which I also mean that "you don't tweak something by taking it to a different extreme" is entirely irrelevant and/or really very uninformed
A 0.2u metabolism isn't an extreme. It's the default.

**Comment by nuklearcellphoneg** [comment]
Inaprovaline is underrated and OP already, people just never utilize because usually you're going to have access to iron, bicaridine, blood, surgery, etc. Rarely do you need to rely on inaprovaline but it's strong even if the popular consensus is 'lol it sucks p useless tbh', that's largely a stance that's resulted from comparative thinking.

**Pull request closed without merging**
