### PR TITLE
Adds a disposal bin to the equipment room in Metaclub's brig

### LINKED ISSUE #35138: No trash bins in sec on meta
(WEB REPORT BY: powerhedgehog REMOTE: 206.221.180.138:7777)
# Revision
108e5d6953abcd9161441a8cc6533e85619e6daf

# Description
metaclub brig needs a trash bin
# Steps to Reproduce

# What you Expected

# What Actually Happened

### PR DESCRIPTION
**Pull request by Irradiation**
Fixes #35138

Capture

:cl:
 * rscadd: Metaclub: Added a disposal bin in the brig's equipment room.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I actually spoke to this player when he made the original report, and what he actually wants is a disposal bin, preferably inside the security office or equipment room. If you think that is too risky, remember the HOS already has one.

**Comment by pedr69** [comment]
mapdiffbot seems to be broken too

**Comment by Kurfursten** [comment]
Yeah that should meet the needs

**Comment by SonixApache** [comment]
change :cl: to format `xx: Metaclub: changes made`

**Comment by Irradiation** [comment]
Done.

**Comment by Irradiation** [comment]
By request of people on discord, I've moved back a plaque (wall) and placed the disposal bin in the place of the old plaque.

image

**Pull request merged**
