### PR TITLE
large hardon collider

### PR DESCRIPTION
**Pull request by pedr69**
[wip][sprites][content]
## What this does
image
[>>>/vg/397634197](https://arch.b4k.co/vg/thread/397306731/#q397634197) - i changed the worldle-based "combine 6 particles into 1" to more of a factorio-based "make a fuckhueg pipe"

- [x] the basics
- [ ] makes it actually draw power
- [ ] collision outputs(i don't work at cern so i have no fucking clue what the results should be)
- [ ] functional bottler
- [x] add boards to cargo and circuitprinter
- [ ] sprites [help]
- [ ] GUIs for the machines
- [ ] non dense pipes that you can walk over

## Why it's good
makes the engineers have something to do with all the power
## Changelog
 * experiment: large hadron collider
 * imageadd: collider sprites

### CODE REVIEW

**Comment by pedr69** [comment]
i posted this here because i am hiring industrial certified idea-guys on how this thing should actually function
starting wage 0.00

**Comment by west3436** [comment]
\>Make it fit under tiles so you can have it scale to fuckheug station-wide sizes for bigger output.
\>Require symmetry for proper function.
\>Consume power at an exponential rate as the collider grows.
\>Exotic materials can be formed depending on the size of the collider including Phazon, Bananium, Mythril, TC, Flawless Bluespace Crystals, or some sort of time-travel material??

**Comment by Kurfursten** [comment]
The LHC allows for the creation of certain particles (e.g.: the Higgs Boson). Therefore, the output should be an item that disappears after 0.00000000000000000000016 seconds (this is the actual correct amount of time).

**Comment by Eneocho** [comment]
> i posted this here because i am hiring industrial certified idea-guys on how this thing should actually function starting wage 0.00

I demand at least 5x the starting wage.
Here's some ideas with little regard for consistency between them:
- Make it so you can emag the hadron collider into the hardon collider. No idea what effect it could have, but I want that dumb name change at least.
- You can set the collider for particle synthesis or particle data collection, the former gives you materials, the latter gives you access to the admin-only research levels (Like NT-5).
- Catastrophic failure, sabotage or weaponization will produce a beam that will melt everything in it's path for X amount of tiles directly proportional to the power you used.
- You can channel the collider particle beam into the SME, with energy added directly proportional to collider power.
- You can use exotic particle physics bullshit to slowly upgrade an SME, at a VERY large energy and upkeep cost (Specialized fuel?). Eventually you can evolve the shard into a crystal. This would make it a slow but consistent source of crystals (Muh Deep lore, is this how the ayyliens made SM crystals???).
- Larger colliders are more efficient with power: A 100 tile collider needs 10GW to do X. while a 10 tile collider would need 1TW to do the same (thus an incentive to build HUGE or expand power autistically).
- Colliders can interface with R-USTs and exponentially increase field Mega Energy or enable reactive synthesis of exotic particles (like trilithium or a new particle that self breeds and makes fuckyou power).
- Nuclear Fission: You can transform large scale amounts of one material into another, following, for the most part, the periodic table (1 sheet of uranium can decay into several sheets of gold or iron, which themselves can decay further into glass or carbon (charcoal), which can be converted into diamond).
- Engineering gets a "Do particle physics research" centcomm with no end (like how cargo can send infinite amounts of plasma). You build a server next to the collider and collect the data. The more data you make, the higher the wages for the entire station are.
- Quantum effects can manifest the ever elusive pomfcoin and gooonecode if you do collider fuckery with enough power (dunno, 100GW?)
- Exposure to certain frequencies of the beam (randomized per shift) unlocks some/most/all genetic powers, these frequencies should be pretty dangerous themselves, so you are gambling being ashed for becoming the ubermensch.
- Strong enough experiments shutdown ALL bluespace protections, so you can teleport to and from centcomm (go for the 1TW SME).
- Placing certain beacons in places and powering them with the collider lets you place indefinite portal style portals.
- A strong enough collider beam can make the scrungulo go red, red scrungulo spreads cult/clockwork shit as it spreads (or something cooler than this)
- There's a small 0.0000001% chance for the nuke to explode if exposed to the collider beam.
- Catastrophic failure will self destruct the collider in its entirety, leaving a pool of non-expanding bluespace seas on the surrounding tiles (3 tiles radius around each collider piece).
- Collider can be weaponized to constantly shoot out uncontained antimatter, which explodes like a weldertank upon contact with a wall.
- Exposing plants to the collider beam will completely randomize their genes with no regards for logic (-100 potency bluespace tomato bros it is time).
- Exposed beams will EMP nearby electronic devices and irradiate nearby mobs if not shielded.
- Getting a beam hit straight to the face will make you see a blue glow for a few ticks.
- Mice have a small chance to become hulk rats if irradiated with the beam.

**Comment by pedr69** [comment]
gonna be away for a month so you could testmerge this after the test serb is fixed to not automatically restart every 15 minutes
hopefully i'll think of some reaction tables by then

**Comment by Kurfursten** [comment]
Testmerge when it has no GUI, no output, no sprites, and no power usage? What is being tested?

Let's wait until you get back to do testing. It'll keep, I know about long open PRs.

**Pull request closed without merging**
