### PR TITLE
BAD TO THE BONE

### PR DESCRIPTION
**Pull request by tinysaturn**
[content]
BAD TO THE BONE
kudos to @Kharkov72
B-B-B-BAD
BAD TO THE BONE
supplementary video:
https://www.youtube.com/watch?v=3kVFce1M_QQ
BAD TO THE BONE
-----------------
This PR adds the skull horn, crafted by combining a skull with a bike horn.
The skull horn has its own unique sound effect.
:cl:
 * rscadd: Bike horn + skull = BAD TO THE BONE

### CODE REVIEW

**Comment by Kammerjunk** [comment]
that's the most frustrating video I watched since https://www.youtube.com/watch?v=V1wjucGPocQ

**Comment by Kharkov72** [comment]
very important pr that I hope doesn't get us sued

**Comment by DamianX** [comment]
We might not have stick shifts but we do have conveyor switches. Just saying.

**Comment by WindowsErrors** [comment]
[finally, some real rock and roll](https://youtu.be/oISnQeC1N7c)

**Comment by Theophrastus1** [comment]
that don't confront me
long as i get my money next friday

**Comment by kane-f** [comment]
stick shift skull knob bad to the bone.mp4

**Pull request merged**
