### PR TITLE
Revert "ERT name sanitization"

### PR DESCRIPTION
**Pull request by yclatious**
Alright fuckbois, the speedmerge was utter shit, the server vote was hella conclusive -for a lack of restrictions-, people want this gone, I got requested to do it. Dont be nonces and merge this shit, as you guys had 0 reason to cause me, of all people, to stop reading my doujins and cease my shitposting to enable fun.

I am shaking my head vigorously, in plain disagreement and dissapointment, my brethren from other wenches.

[16:53:44]VOTE: Custom vote started by deitylink. Ultra Long names being allowed for ERT players is
[16:54:48]VOTE: Vote Result:
Retarded (but fun) won with 21 votes.
Utterly retarded, please remove it already! had 9 votes.
Fun had 2 votes.
(posted at https://github.com/vgstation-coders/vgstation13/pull/21870)
Reverts vgstation-coders/vgstation13#21870

### CODE REVIEW

**Comment by Irradiation** [comment]
Incoming speed close

**Comment by boy2mantwicethefam** [comment]
Person who speedclose double gay

**Comment by otatoh** [comment]
not only based but redpilled too

**Comment by DrSnips** [comment]
Check em

**Comment by ShiftyRail** [comment]
image

**Comment by luzzgawr** [comment]
image

**Comment by MadmanMartian** [comment]
Due to this causing administration issues, this will be closed.

Apologies.

**Comment by Intigracy** [comment]
1024 characters MAX_MESSAGE_LEN
vs
26 characters MAX_NAME_LEN

If you want longer names then make a PR to increase the name length define, but it's not getting a max length of 1024.

**Pull request closed without merging**
