### PR TITLE
ROGANbot

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
It took me 3 times longer to debug and fix the retarded merch console store datum than to actually code the thing itself. It was making a global singleton-like list of merch datums, then that list was never used and every time it wanted to make an item it created a new merch datum and left it to the garbage collector without even manually deleting it. Then it also turns out the UI was only generated once, in the console's New(). But it also tried to update UI anyways. But it didn't work because it uses a snowflake UI. Fuck you. Fuck whoever did this. I am genuinely mad.

Anyways it's an item that lets you AoE2post by saying taunt lines when it hears a number from 1 to 38. 11
https://www.youtube.com/watch?v=nr0zoGjulZ4

dreamseeker_2019-05-08_16-25-17

As you can see this item has a very high skill ceiling
Only 1 is obtainable to prevent people from buying 4 and turning it into the next buttbot comms destroyer.

:cl:
 * rscadd: Added the handy ROGANbot, available at Cargo's merch console for 100 credits.

### CODE REVIEW

**Comment by Jeroen52** [comment]
Upvoting this because I made the PR for the Old Empire Bar.

**Comment by PaulRitter** [comment]
11

**Comment by GlassEclipse** [comment]
Should put in vox trader vendor. Seems likt it fits more.

**Comment by Kitfox88** [comment]
chaplain should rush it roundstart so they can just spam 30

**Comment by Durgen** [comment]
aoe monk chap religion when

**Comment by Kitfox88** [comment]
wololo

**Pull request merged**
