### PR TITLE
Flash except it's incredibly sus

### PR DESCRIPTION
**Pull request by tinysaturn**
[sprites]
[content]
## What this does

https://puu.sh/JjNqA/33f63b74ea.webm
Adds a flash imposter simplemob that has the ability to vent-crawl and be generally annoying.
adminspawn only

## Why it's good
finally a tasteful reference to SS13's sequel
hopefully @Kharkov72 will be less likely to bus the crushed jpeg of a dripped out amogus

**Supplementary video**
https://www.youtube.com/watch?v=QYW1XWofXzc

## Changelog

:cl:
 * rscadd: Adds a flash look-alike simplemob
 * imageadd: Adds sprites for the flash look-alike simplemob and its spells

### CODE REVIEW

**Comment by Eneocho** [comment]
`>does not make the role reveal sound effect`
one job

**Comment by ValkyrieSkies** [comment]
>hopefully @Kharkov72 will be less likely to bus the crushed jpeg of a dripped out amogus

This won't happen and you know it.

**Comment by pedr69** [comment]
>flashes the HOS even though he has sunglasses on

B-B-BAKANA

**Comment by tinysaturn** [comment]
> > flashes the HOS even though he has sunglasses on
> 
> B-B-BAKANA

The sus flash has a flash spell that pierces eye protection on a 5 minute cooldown

**Comment by WindowsErrors** [comment]
People used to tell me that adding "meme" material such as among us or the punisher debased and lowered the quality of the codebase
but look around you, look at all the other codebases that surround us with their Amogus this, Wireless Spacepods that, Nanotrasen Drip here, Sus Town there
if it's everywhere you look, then is it a "meme" or just a reference to society?

**Comment by BomberBro** [comment]
Memes were a mistake.

**Comment by ShiftyRail** [comment]
One year rule.

**Comment by gurfan** [comment]
Its been over one year.

**Comment by Exxion** [comment]
image

**Comment by Kharkov72** [comment]
what have i wrought

**Comment by d3athrow** [comment]
at least it's not ponies @Kharkov72 

> what have i wrought

**Comment by Eneocho** [comment]
> at least it's not ponies @Kharkov72
> 
> > what have i wrought

inb4 tummy kittens or whatever that fucking adminbus was

**Pull request closed without merging**
