### PR TITLE
Swaps chemmaster and chemdispenser in Box chemistry for easier slurping + slight Box chemistry remodel

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
dreamseeker_2019-05-02_16-22-52

It's really annoying to actually use the slurp mechanic because you can only really do it with the bottom chemmaster and only in one awkward spot. I can't think of any way to fix this except to swap these around. I think it looks a little bit more aesthetic too, but I want to see how many people fucking hate this before I bother doing it for other maps too.
Yes, you can still use the bottom chemdispenser from the bottom through the table.

Also unatomically readds the potted plant that was removed from cloning

:cl:
 * tweak: Swapped Chemdispenser and Chemmaster placement in Box chemistry for easier use with the slurping mechanic.
 * rscadd: Added a second plasma bar to Box chemistry, since all the other maps had 2 and if I removed those I would have been lynched. Remodeled tablespace slightly.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Food for thought: With this layout, clowns can falsewall the front desk to have sneaky access to a chemdispenser.

Personally I don't think this is a big deal, but it's worth mentioning. If it does become a big deal, those walls could be made reinforced to match the rest of chemistry.

**Comment by PaulRitter** [comment]
where's the potted plant in that pic

**Comment by brndd** [comment]
what is the slurping mechanic

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
#21140
It's so you can fill a cauldron with 500u autism and quickly make it into 10 50u pills, or fill a bucket with dex+piccolyn and lace it into all your pills even if you're using a large beaker

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Surprisingly people don't hate this so I might as well do it for all maps

Before I do: Should the walls be replaced with rwalls to preemptively deny the falsewall chemdispenser strat? :+1: or :-1:  this post or forever hold your piece

**Comment by HarseTheef** [comment]
Realistically it halves the area that the dispensers can be used.  More specifically pushing the bottom dispenser unit away from what I consider to be a class 7 greytide zone.  Bottom dispenser chemist was previously one of the most diligent watch dogs of this class 7 zone.  This change effectively increases the passive anti-greytide power of chemistry by twofold by increasing the likelihood of the shitterwatch spot being used. 

nzZHslq

It's clear whose side you are taking in this war, as well as who you are working for.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I gave thought to it and yes, it does reduce the amount of tiles from which you can use your chemdispenser. It is a shame, but I can't really think of a way to prevent that. In any case, I think this might actually be a good thing, because if people want to nigger your chemdispenser while you're using it, they have to physically push you away.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Turns out the other maps don't exactly need this or isn't applicable to them so, box only

**Comment by HarseTheef** [comment]
For what it is worth, I also believe it is a good thing, because it encourages chemists to use spots that are less likely to be walked into or interfered with, as well as what you said about belligerents and undesirables.  Another interesting result of this is that blowing the dispensers via a MALF or a general bomb will be more likely to breach open chemistry.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Done with this PR, check OP for updated changes

**Comment by ValkyrieSkies** [comment]
what the FUCK is slurping

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
You either slurp or you suck

**Pull request merged**
