### PR TITLE
plasma clothing and eyedamage tweak

### PR DESCRIPTION
**Pull request by pedr69**
remade and merged the PR's because i think i was being too atomic

### maek plasma moar dangerous:

- glasses, masks and headsets can now be plasma contaminated
 -plasma or pressure resistant helmets prevent head contamination
 -a gas mask prevents eye contamination
- plasma contaminates glasses burn your eyes
 -mesons, materials, scigoggles, thermals and NV goggles are plasma proof

### maek plasma less dangerous:

- eyes being burned by plasma no longer break completely, stopping just short of full blindness
- eyes will be burned slightly slower (1 damage per tick instead of the old 2.5)

## Why it's good

spreads the joy of plasma blindness to a much larger part of the crew, at the cost of
reducing the joy of plasma blidness slightly - plasma will now hurt your eyes to this point instead of full blindness
image

## Changelog

:cl:
 * bugfix: wearing a hat but no glasses will no longer prevent your hat from being plasma-contaminated
 * tweak: masks, headsets and some glasses can now be plasma-contaminated
 * rscadd: plasma-contaminated glasses will make you blind
 * tweak: plasma no longer blinds you permanently after 14 seconds of exposure

### CODE REVIEW

**Comment by Eneocho** [comment]
For future reference, the permablindness is fixed by taking rye to fix the shitcode genetic blindness you get and imidazoline to fix the eye damage.

**Comment by pedr69** [comment]
well just imidazoline works, but getting to medbay with zero visibility and having to rightclick everywhere is the hard part
also, how come bleach decontaminates stuff when sprayed but liquid plasma doesn't contaminate when sprayed?

**Comment by angryturnip** [comment]
I haven't read the code at all but if masks can be contaminated I would implore you to make clown/mime masks not have that happen

**Comment by pedr69** [comment]
>maek plasmaproof

already done - https://github.com/vgstation-coders/vgstation13/pull/34086/commits/d4235b4aed767ad0a39c9e144845317776ef3142

**Comment by pedr69** [comment]
god dammit...
can't believe the pr with 9upvotes and 8 downvotes got closed
and then the collab he close the pr but i respawn and now there's actually more downvotes
it's so fucking over

**Comment by Kurfursten** [comment]
Lack of support and atomicity

**Comment by Eneocho** [comment]
what a shame

**Pull request closed without merging**
