### PR TITLE
Revert "Flash powder flashbang"

### LINKED ISSUE #22906: new flashpowder literally deletes mobs if injected into them
and also deletes your beaker if made in one @SonixApache

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Can be used to LITERALLY DELETE MOBS FROM EXISTENCE INSTANTLY

fixes #22906

Maybe readd this as a different recipe if you want to readd it later please because I want to flash people without deafening everyone in the process (maybe aluminum potassium chlorine oxygen?)

### CODE REVIEW

**Comment by ShiftyRail** [comment]
Whoopsie
I'll merge this as soon as Travis is done

**Comment by boy2mantwicethefam** [comment]
Add a changelog

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
dammit 15 seconds too late for the changelog

**Comment by boy2mantwicethefam** [comment]
SHIFTY

**Comment by SonixApache** [comment]
1000% tested
amazing

**Comment by FudgePucker** [comment]
This sounds like it is the single most powerful chem in the game. How many times was it used while it was merged?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
One, and it only deleted a beaker

**Pull request merged**
