### PR TITLE
adds ablative and bulletproof helmets to cargo

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
image
armor crate(20cr) now has 3 helmets and vests, from the previous 2 helmets, 2 vests and 2 bulletproof vests
experimental armor crate(~~35cr~~ ~~70cr~~ ~~ONE HUNDRED~~150 CREDITS) now has 2 ablative vests and helmets, from the previous ablative, bulletproof and riot mix
adds a bulletproof armor crate(30cr) with 2 bulletproof vests and helmets

## Why it's good
less unobtainable items... good?

## Changelog

:cl:
 * rscadd: bulletproof armor(and helmet) crate at cargo
 * tweak: armor crate now has three normal sets
 * tweak: experimental armor crate now has two ablative sets and costs an insane amount

### CODE REVIEW

**Comment by adacovsk** [comment]
raise the cost of experimental to like 150

**Comment by pedr69** [comment]
150 is insane
the tactical assault crate costs 120, and you get visor helmets, riot shields, and normal,bulletproof and ablative carrier variants
you can rnd the vests with a bit of diamond and they don't even come in lockboxes
and with armory access which the crate is locked to you could just take your ablative from there

**Comment by Eneocho** [comment]
I agree, raise them to at least 100c. Too cheap. The metaclub will complain about muh balance with this price.

**Comment by pedr69** [comment]
currently you get an ablative vest, bulletproof vest, riot suit and riot helmet for 35
why would adding another ablative and getting rid of the other shit quintuple the price?
the metaclub isn't complaining about the current ablative prices

**Comment by gurfan** [comment]
the metaclub might not be complaining but I am
raise the prices!!!

**Comment by djkramer123** [comment]
>making the ablative helmet obtainable

lol

**Comment by pedr69** [comment]
I KNEEL

**Comment by pedr69** [comment]
>more and more downboats the more i raise the price

very well.

**Comment by assmops** [comment]
the fact that sci can print more ablatives is bad enough
we really dont need even more of them plus ablative helmets easily available
not to mention that you can buy multiple crates of these roundstart and have enough money left over in the cargo debit to get enough guns to rival the armory, sci at least needs mats before they can start arming up

**Comment by pedr69** [comment]
>sci at least needs mats before they can start arming up

false, and the weapons they can make from metal and glass beat the armory variants by a mile(except lasers they need mats to shit those out)
while the armor that science can make before they get mats isn't THAT good(only 50% resist but covers limbs), after they get mats they get a riot-bulletproof-ablative EOD suit all in one, which covers limbs too

and armor doesn't even matter, since you'll be made horizontal before being killed anyway, and the helmets don't save you from being made horizontal
i guess the emojicracy has spoken, and i think the emojicracy is retarded

**Pull request closed without merging**
