### PR TITLE
SAMMI tweaks and changes

### PR DESCRIPTION
**Pull request by tinysaturn**
[tweak]
[qol]
## What this does

This PR does the following for SAMMIs:
1. Gives them a unique welcome message that links to a new wiki page written by @Eneocho instead of the MoMMI welcome message (what the fuck)
2. Makes the cyborg lawsync sound play whenever their laws are changed (this is normally silent for no good reason)
3. Forbids a SAMMI from using a multitool on itself to reprogram its laws and epically self-antag (what the fuck did the original coder mean by this)
4. Lets SAMMIs talk normally and on common
## Changelog

:cl:
 * rscadd: Adds a welcome message for SAMMIs and a sound effect for a law change
 * tweak: SAMMIs can no longer reprogram themselves
 * rscadd: SAMMIs can talk now

### CODE REVIEW

**Comment by pedr69** [comment]
>Forbids a SAMMI from using a multitool on itself to reprogram its laws

perhaps you could also disable the law upload word blacklist, since that's in place to prevent it from subverting itself and murderising everyone

**Comment by tinysaturn** [comment]
> perhaps you could also disable the law upload word blacklist, since that's in place to prevent it from subverting itself and murderising everyone

The blacklist is there for the general of purpose of needing an emag or a captain level ID in order to release the safeties and turn it into a murderbot
Humans inputting laws can still trip the blacklist and get an invalid text error

**Comment by Eneocho** [comment]
I remember one round where the SAMMI reprogrammed himself to make screwdrivers, so he printed like 500. Sad to see that go.

**Comment by PrimeDSS13** [comment]
> > Forbids a SAMMI from using a multitool on itself to reprogram its laws
> 
> perhaps you could also disable the law upload word blacklist, since that's in place to prevent it from subverting itself and murderising everyone

I came here just to post this, the word blacklist is such shitty """"design"""".
No other law uploads work like this in the game at all, I have zero idea why Kanef did it this way. If someone wants to antagonize with a robot, the shitty nontalking nonmoving one handed weirdos shouldn't be harder to set than the actual AI and cyborgs.
Additionally, the blacklist doesn't even accomplish it's goals. All it does is make writing laws cumbersome since you have to avoid keywords (impossible to know which ones set it off unless codediving), and you can still make murder laws without an emag or access, you just have to make them obtuse and Blaine like to avoid using the word "sentient" and such. I've done it multiple times myself, even.

A note that I feel less strongly on, I don't even know why SaMMIs can't talk. They're not MoMMis, they have no "plz dont interact" law or functionality, so it's a certainly confusing. Obviously it's because they're just (poorly thought out) subtypes, but nearly everyone just throws them a speaker so they can communicate. It just feels like an unneeded extra clunky step.

**Comment by tinysaturn** [comment]
> 
> A note that I feel less strongly on, I don't even know why SaMMIs can't talk. They're not MoMMis, they have no "plz dont interact" law or functionality, so it's a certainly confusing. Obviously it's because they're just (poorly thought out) subtypes, but nearly everyone just throws them a speaker so they can communicate. It just feels like an unneeded extra clunky step.

SAMMIs not talking seems like a deliberate choice actually, considering the keeper variable for them is specifically set to true.
Setting it to false will let them talk normally and gives them common radio access.
I don't have a problem with SAMMIs talking and I can add it to the PR if people are okay with it.
dreamseeker_kf2IRDxwWq

**Comment by Eneocho** [comment]
The loss of the MoMMI/SAMMI speak in exchange for galcom. A fair price to pay.
Would also work for SAMMI translators. Imagine a reformed pox raider using a sammi as live translation/bar assistant.

**Comment by tinysaturn** [comment]
I'm pretty sure you can still talk to MoMMIs on :b

**Comment by Eneocho** [comment]
> I'm pretty sure you can still talk to MoMMIs on :b

Yeah, but it's not the same. The shittalk to the derelict mommi hits different when you can speak in their snowflake channel.

**Comment by tinysaturn** [comment]
I'm more looking forward to shitters going insane when a SAMMI doesn't state its laws after being asked to

**Comment by Eneocho** [comment]
> I'm more looking forward to shitters going insane when a SAMMI doesn't state its laws after being asked to

`Shitsec McCunt [Common] (Security Officer) screams "OMG THE SAMMI IS ROGUE BORGS ROGUE GET THE IONS"`
`Stationary Assembly MMI 433 [Common] (Cyborg) states: "shard"`

**Review by Kurfursten — COMMENTED** [review]
If this were just the first two changes I would merge it immediately, but SAMMI talking is probably something that should have community approval

**Comment by pedr69** [comment]
the safeties feel silly anyway
the thing is stationary and has fuck-all for murderweapons, as opposed to borgs
a personal AI has more murderbone potential, spawns roundstart and requires no ID/emag to override

**Comment by Kurfursten** [comment]
What? SAMMIs can pick up a weapon, pAIs can't. I guess a pAI can make small amounts of sleep toxin on a 10 second delay while you're holding it, but as soon as you drop it from falling asleep it can't give you more chems.

**Comment by Eneocho** [comment]
> What? SAMMIs can pick up a weapon, pAIs can't. I guess a pAI can make small amounts of sleep toxin on a 10 second delay while you're holding it, but as soon as you drop it from falling asleep it can't give you more chems.

His point is that a pAI has way more dangerous potential than a SAMMI. Both require someone to give it access to weaponry, but pAIs spawn roundstart and can fuck shit up if they are given a smart laser or mounted on a hacked MULE if given an order to kill people. 
SAMMIs just stand there, menacingly, not to mention that they need to be built and hacked in order to be dangerous. I feel you're over reacting, SAMMIs are weak as shit even if hacked.

**Comment by pedr69** [comment]
>pAIs can't [pick up a weapon]

#33382

**Comment by Kurfursten** [comment]
What you're saying is not that pAIs are dangerous, but rather that MULEs are dangerous. It seems a little silly to say "pai has more murderbone potential at roundstart without emagging" when what you mean by that is "if you broke into cargo and hacked a mule to override its safeties and then inserted a pai". Yes, that's true, and if you break into engineering you can set up a sammi next to the supermatter and a welding tank and give it a welder. The danger isn't the sammi or the pai.

None of this conversation really has to do with sammi speech though.

**Comment by Eneocho** [comment]
I doubt SAMMI speech will be that much a game changer. Beyond a couple bans for shitters saying: "MY BODY IS IN THE ASTEROI-" nothing else will happen. Everyone already gives them a speaker.

**Comment by Kurfursten** [comment]
The votes have it

**Pull request merged**
