### PR TITLE
adds bone gel and fixovein to the surgery switchtool

### PR DESCRIPTION
**Pull request by aceedex**
see title
https://i.imgur.com/dbLLLcH.png fixovein
https://i.imgur.com/amU5VcN.png bone gel
not the best but I guess they'll do
 * rscadd: the surgery switchtools, both maxed and the printable one, now have bone gel and fixovein in them by default

### CODE REVIEW

**Comment by SirSkeleto** [comment]
please also add the ability to put the C.L.O.T. on the switchtool

**Comment by boy2mantwicethefam** [comment]
What about the upgraded version?

**Comment by aceedex** [comment]
read nigga, read.
also I dunno what the fuck a clot is but Ill look into it

**Comment by DrSnips** [comment]
While the gel in the upgraded version isn't really necessary since the mender does it's job it doesn't hurt. The fixo should be a CLOT in the upgraded one.

**Comment by SirSkeleto** [comment]
also note that this allows people to make new fixoveins and bone gels without having to do the chem stuff or order a surgery crate from cargo

**Comment by DrSnips** [comment]
Not like it really matters since the ghetto versions are extremely abundant (screwdriver and wire) and don't really have any impact balance wise.

**Comment by DrSnips** [comment]
That sound's gay and inconsistent.

**Comment by aceedex** [comment]
Ill be honest Im not a fan of bone gel being surgery crate only and this is simply another avenue to make those items after research has been done for quite an up in cost

Also since clots are children of fixoveins they fit in there as is I'll just add the clot to the maxed one no prob

**Comment by DrSnips** [comment]
Realistically there's no reason why the gel and fixo couldn't be in the autolathe. I can't think of any big issues that would come from it other than less internal bleeding deaths and unbroken bones

**Comment by Kurfursten** [comment]
>Realistically there's no reason why the gel and fixo couldn't be in the autolathe

Aren't you the one who established that fixovein and bonegel are things made in chemistry, not out of metal from a lathe? 🤔 

also @aceedex see above this is what he's talking about not crate

**Comment by MadmanMartian** [comment]
It's not surgery crate only, there's a method to making it that's strange and requires chemical interaction.

I believe bone gel is made using milk and cryoxadone in a vial, whereas fixoven is made using bicaridine and clonexadone in a vial.

**Comment by aceedex** [comment]
ye I know kurf, same difference. dont change what I said about it being a more costly thing to make only after research is done

**Comment by DrSnips** [comment]
Yeah I kind of did it on whim so medical could get them quickly [enough] and because people thought it might be fun to get them through chemistry.

**Comment by ShiftyRail** [comment]
This seems to have plenty of support, even though the code for the object itself is less than ideal.

**Pull request merged**
