### PR TITLE
Reduces Cult weight to 2, down from 3.

### PR DESCRIPTION
**Pull request by Irradiation**
#23165 doesn't really change much, since we generally always have the amount of "enemies" required to roll cult anyway. I'm doing this so we can have a break from Cult Station 13, featuring cult rounds 2-4 times in a row, with the occasional 1-2 rounds without cult. Discuss.

[role][gamemode]

:cl:
 * tweak: Cult's weight has been lowered slightly, making it less likely to roll at roundstart.

### CODE REVIEW

**Comment by Irradiation** [comment]
Welcome. Welcome to Cult Station 13. 

You have chosen, or been chosen, to relocate to one of our finest remaining cult stations. I thought so much of Cult Station 13 that I elected to establish my Cult here, in Maintenance so thoughtfully provided by Nar-Sie. I have been proud to call Cult Station 13 my home. And so, whether you are here to stay, or passing through on your way to parts unknown, welcome to Cult Station 13. It's safer here.

**Comment by utilitas-** [comment]
Now make the cost 35-40, and add a minimum player requirement of 30.

**Comment by fralda** [comment]
Based

**Comment by DamianX** [comment]
oh god i just realized this is a reactionary pr

**Comment by Commandersand** [comment]
image

**Comment by tuypo1** [comment]
> oh god i just realized this is a reactionary pr

Yeah no shit, cult haters love to exaggerate how common cult is

**Comment by Kurfursten** [comment]
I feel weird about merging this because it has a lot of support but I have heard anecdotally that the spike in cult last week subsided and now we haven't had it as much?

**Comment by DeityLink** [comment]
No amount of weight changing prevents the chance of a ruleset firing twice in a row, since we're using full random distribution instead of some pseudo random stuff.

Anyway there's been 12 cult rounds in the past week. With an average of a bit under two per day:

06/13 Thursday: 2
06/14 Friday: 1
06/15 Saturday: 2
06/16 Sunday: 2
06/17 Monday: 2
06/18 Tuesday: 2
06/19 Wednesday: 1

That's way less than a few months ago so I'm pretty sure it's a joke PR @Kurfursten

**Comment by Kurfursten** [comment]
Since this is such a minor change and the fervent support *appears* to have subsided, I'm going to close this. If you make a new PR and it gets the same level of support, I'll merge it. I have the suspicion that the earlier reactionary sentiment won't be there anymore. It would seem #23165 was significant after all.

**Comment by BomberBro** [comment]
I'd like to point out that, while we haven't had as much of cult as when this PR was made, saying that none of them were back to back is flat out false. On late Sunday into Monday there were three cult rounds that all came one after the other.

**Comment by DeityLink** [comment]
My bad then. Personally I wish we used pseudo-random distribution to cull the possibility of this occurring.

It shouldn't be hard to log what rulesets were used during the previous roundstart and dynamically lower the weight slightly.

**Pull request closed without merging**
