### PR TITLE
O2 First-Aid Kits now contain 2 Inaprovaline pills instead of 1 Inaprovaline syringe and a Dexalin pill.

### PR DESCRIPTION
**Pull request by Irradiation**
After a bit of discussion in the Inaprovaline metabolism PR (#18016), I've decided to swap around the contents of the O2 First-Aid kit in order to encourage the use of Inaprovaline, along with standardising the usage of pills over syringes. 

Each Inaprovaline pill contains 30 units of Inaprovaline and should benefit people that didn't like having to triple-inject someone to give them 15 units of Inaprovaline.

EDIT: by demand and for the purpose of ghetto chemistry, one of the Inaprovaline pills has been swapped with the old Inaprovalie syringe.

:cl:
* tweak: O2 First-Aid kits now contain 2 Inaprovaline pills and 3 Dexalin pills, replacing the old inaprovaline syringe and 4 Dexalin pills.

### CODE REVIEW

**Comment by SonixApache** [comment]
Perhaps it's finally time to replace the O2 locker kits with general-purpose aid kits.

**Comment by Chazach** [comment]
This also removes easy access syringes for ghetto chem and such

**Comment by Diavill** [comment]
you're becoming megamaw but instead of skeletons its fucking inaprovaline

**Comment by Unknown-as-Captain** [comment]
https://github.com/vgstation-coders/vgstation13/issues/18045#issuecomment-379579431

I think a pill probably wouldn't be needed if injections lasted longer than 20 seconds.

**Comment by Irradiation** [comment]
@ShiftyRail Syringes and metabolism wouldn't be a problem if Dylan hadn't scrapped the original metabolism and turned in to 0.5 seemingly by accident in a PR a long long time ago. (https://github.com/vgstation-coders/vgstation13/pull/6806/files#diff-5da7182f398e1fd964dee9d74d475679R655)
@Diavill Who's Megamaw and what did he do?
@Chazach I could always replace one the Inaprovaline with the old syringe pill so people could ghetto chemistry once more.
@Unknown-as-Captain I'm inclined to agree, but looking at the original metabolism PR, swapping out the contents of the O2 First-Aid kit seemed like the most reasonable and less radical solution.

**Comment by Pathid** [comment]
Evidently having access to a few easy syringes is important for doing nefarious stuff.

syringe

**Comment by nuklearcellphoneg** [comment]
Personally I think removing the syringe is kind of bad because it can aid in medical acts of desperation, like transferring blood to someone who needs it 15u at a time

**Comment by Probe1** [comment]
@Irradiation You are an omnishambles.  You make a balance PR out of the blue to change something dramatically without a good reason.  You fail to provide that reason.  People get mad at my attitude and dig up a dozen good reasons.  Now that you have the strong arguments for the original change what are you gonna do?

Remove syringes.

**Pull request closed without merging**
