### PR TITLE
Bagelstation mining roid overhaul

### LINKED ISSUE #15062: Bagel: Minerals are SPARSE
There is such a low density of minerals on the main asteroid. Why is this?
You need a drill to get anything of worth.

### LINKED ISSUE #15607: Disconnected vents on bagel
- on the left

### LINKED ISSUE #15735: Backwards bagel vent
(WEB REPORT BY: vahalian REMOTE: 172.93.109.202:7777)
>Revision eacb22abdf1de3b8533f6554a53d319308692cb6 

>General description of the issue
Theatre vent #2 is disconnected facing the wall

>What you expected to happen
the vent not to be backwards

>What actually happened
It was backwards

>Steps to reproduce if possible
go to vent, pry up carpet

### PR DESCRIPTION
**Pull request by CptWad**
bagel mining

obviously, people without proper access wont be able to access what they shouldn't
also you can condense the space xenoarch takes up far more than expected, half of the shit given is unnecessary fluff to begin with.
when I first made this map I got lazy at this point due to loss of intrest and wanting to get the map into the game. Now time has past and I decided to remake this with 90% less copy pasting

fixes #15062 
fixes #15607
fixes #15735

:cl: 
 * experimental: New Bagelstation mining asteroid layout. Science and miners now share the same station with vox traders as uncomfortably close neighbors 
 * tweak: High yield rock placement tweaks, diamond should now be possible to find in a similar vein to how you do it on other stations. 
* bugfix: Other small fixes to bugs people have pointed out
* tweak: New additions to bagel in general.

### CODE REVIEW

**Comment by yclatious** [comment]
>vox near people

Do you want roundstart rushed raiding partys of gigantic feathered bypeds going CAW :v we made much coin cousin to steal everything not bolted and bolted down? Because you are going to get it, alongside giving the bird people the slightest idea anyone wants to be around them, alongside the clear issue of putting xenoarchs and miners in the same living area, if the xenoarch miner wars weren't much of a thing before, they sure will be now.

Other than that, I like the style, even if the lack of surgery tools in maint surgery is kinda dissapointing and the random firelock assembly doesn't really do much, looks real nice.

**Comment by CptWad** [comment]
I am a madman I know
This is also partly an experiment. As a backup I saved the old vox station and made this one very unintrusive so I can swap them out if it becomes a problem.

**Comment by yclatious** [comment]
If its easily revertable, Im fine with it being a experiment if it goes well, long as the birds get the boot when they try to be too friendly and think humans like being around them as people instead of traders.

**Comment by CptWad** [comment]
Easy to revert for me
image
really its up to the first few rounds and if shitters play or not

**Comment by DrSnips** [comment]
For a place that houses xenobio, it sure lacks fire extinguishers. As well as it just lacking them everywhere.

**Comment by Kurfursten** [comment]
I like a lot of what this has to offer, especially the new mineral conveyor. I can tell you put a lot of work into making it look nice. I do think you go a bit overboard in accommodations though. The outpost needs as many microwaves as the kitchen? Particularly since science will just cook their own food with easy access to microwaves with the super-stocked botany room. Both the Vox post and outpost start with a full set of drink dispensers? Two chem dispensers and two sets of xenobot machines?

There seems to be a general lack of cameras, don't forget to add them.

I'd talk to experts in xenoarch about the location of those test chambers. The thing about artifacts is they have a way of casting rads or EMPs in a large radius through walls, and they're pretty close to the main halls right there.

**Comment by CptWad** [comment]
>cameras

f u c k
hold on

**Comment by SarahJohnson489** [comment]
It's not even just a concern about main halls. You can roll a long-range on your effect and basically hose the entire outpost with rads/emp. Or it's activated when you bring it in and it hotboxes the halls up. It's why I was so vehemently against basically anything not xenoarch on the outpost in the past. Thankfully most players have no clue how to xenoarch, less play it consistently, less speedrun larges, and even less of those will roll a large radius so the deaths are very rare.

Consider adding a chute by the external airlocks to long-term storage, and a chute to the anomaly scanner lab.  Varedit the names or whatever so people know where they go to.

**Comment by HarseTheef** [comment]
Interdepartmental interaction.  I love it.

**Comment by DrSnips** [comment]
*fighting

**Comment by CptWad** [comment]
ok that should do it

**Comment by F-OS** [comment]
you sneaky bastard

**Pull request merged**
