### PR TITLE
Medical Maint tweaks

### PR DESCRIPTION
**Pull request by CptWad**
After some talking with Bomber Harris I went in and tweaked the area a bit to make it flow better
Other notable tweaks
Moved the meter in telescience so it read the right pipes pressure
G. Surgeries doors now show up as bolted on renders
virology moved down a bit
added 1 grille by the singlo containment. A single meteor cant knock out the singlo containment any more. Several still will.

image

[box]
[tweak]

:cl:
 * tweak: Boxstation medical/viro maint touched up a bit
 * tweak: Box singlo containment afforded one more grille for space debris protection

### CODE REVIEW

**Comment by PrimeDSS13** [comment]
Pre-PR Box maintenance, for reference.
image

**Comment by SonixApache** [comment]
image
dumb proximity, move them back to where they were

**Comment by CptWad** [comment]
thy will be done

**Comment by godietxt80** [comment]
they're the same picture.

**Comment by Kurfursten** [comment]
This is an extremely autistic nitpick but boy those 4 unpixel-shifted cigs in a row look terrible to me. I get that you're trying to make a trail of butts but at least inject some soul

**Comment by SonixApache** [comment]
>roundstart trash

disgusting

**Comment by CptWad** [comment]
ok but it will take a while since I am currently busy on personal shit

**Comment by CptWad** [comment]
image

**Comment by ShiftyRail** [comment]
skub

**Pull request merged**
