### PR TITLE
Reverts flashbangpowder changelog

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Does this work?

### CODE REVIEW

**Comment by brndd** [comment]
No it doesn't. Why would you want to remove the changelog anyway? Why not just make a new changelog saying "haha nevermind"?

>DO NOT EDIT THIS FILE BY HAND!  AUTOMATICALLY GENERATED BY ss13_genchangelog.py.

>HEY, YOU.
>ADDING A CHANGELOG ENTRY? MAKE changelog/USERNAME.yml.  READ example.yml SO YOU DON'T SCREW UP.
>ADDING CREDITS?  EDIT templates/header.html (or footer.html if they're for old teams)

**Comment by ShiftyRail** [comment]
I actually remember making a PR like this one way back so it'll work, it's just ill-advised.

**Comment by bathosbathtime** [comment]
It still was something that existed in the code.  Even if it worked this would be bad record keeping.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I checked ss13_genchangelog.py and it generates from .all_changelog.yml, that's why that warning is there

As for the second disclaimer that's the old changelog system

**Comment by brndd** [comment]
All I know is that I made the mistake of editing one of these files by hand and it broke automatic changelog generation for a week, so only do this if you're ready for PJB's wrath.

**Comment by gbasood** [comment]
yeah no do not do this
either add a new changelog entry describing the revert or don't do anything at all

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Ok, I tried just comitting an empty commit and that auto-closes the PR, so there goes my idea of merging an empty PR with a changelog entry

So, oldchangelogs it is

**Comment by bathosbathtime** [comment]
Would have just slapped a "//removed flashbang capability" on the flash powder code to use the automated CL, myself.

**Pull request closed without merging**
