### PR TITLE
Glock pack cargo crate price has been reduced to 60$.

### PR DESCRIPTION
**Pull request by Irradiation**
Price tag on the cargo crate has been reduced from a high 200$ to a more acceptable 60$, which is in line with the price for glock ammo crates.

Like it says on the tin, glocks are currently mostly unused, due to how they're completely overshadowed by laser/energy guns in terms of DPS and projectile speed.

Some may argue that glocks are good because they don't get affected by EMPs, but let's be fair, at 15 damage per lethal round, we aren't going very far. In addition, if we were to compare crate price tags, the Weapons crate costs 30$ and gives you 2x Laser Guns, 2x Stun Batons, 2x tasers 2x flashbang boxes and 1x bolas box. And everything in there is rechargeable. And stuns for longer than rubber glock rounds.

:cl: 
 * tweak: The price for the  glock pack crate in cargo has been reduced to 60$.

### CODE REVIEW

**Comment by SonixApache** [comment]
Sure, maybe it'll work out.

**Comment by Zennyization** [comment]
why use glocks when you can use eguns

**Comment by Probe1** [comment]
Cause glocks show everyone you're an original gangster

**Comment by Irradiation** [comment]
Because >muh ballistic guns

**Pull request merged**
