### PR TITLE
Cleaver throw chance

### PR DESCRIPTION
**Pull request by Allspice**
dont think "throwing your weapon away" should have a chance to do nothing if it's supposed to be a feature of that weapon

:cl:
* tweak: Traitor cleaver knockdown-on-throw chance 85% -> 100%

### CODE REVIEW

**Comment by calzilla1** [comment]
"It also has a strong to stun when thrown."
It should be changed just for this alone

**Comment by TGFH** [comment]
It's meant to be a melee weapon. The idea is that you are taking a risk by trying to use it as a ranged weapon.

**Comment by Allspice** [comment]
It's meant to be a weapon you can smack people with, or flick at them to knock them down. Which is why it deals 5 less damage and costs 2 more tc for a chef compared to an esword. Plus, even if this is merged, the risk is that you're throwing away 10 tc with no particular guarantee that you'll be able to pick it up again.

**Comment by Blithering** [comment]
Esword doesn't have the ridiculous butcher option cleaver does.

**Comment by APCUnlocked** [comment]
I fully support this, e-sword has always felt like a much better option in any situation, but with this PR the cleaver would have an actual gimmick other than hee hoo can't get this off my hands

**Comment by calzilla1** [comment]
> I fully support this, e-sword has always felt like a much better option in any situation, but with this PR the cleaver would have an actual gimmick other than hee hoo can't get this off my hands

Are you talking about the HF Machette?

**Comment by Allspice** [comment]
@APCUnlocked 
Note, this is for the meat cleaver, the chef's uplink item. Not the machete.

**Comment by Allspice** [comment]
@Blithering Main upside of the cleaver is flicking it at people, meating people is primarily a thematic gimmick, and while meating is superior to decaps for being a dickass, it's not sufficiently superior to justify dicking over the traitor 15% of the time they throw the cleaver. That's without touching on the things eswords get that cleavers do not: deflect, greater sharpness, and the relatively recent buffs of superior armour penetration and airlock/wall cutting.

@APCUnlocked 15% chance to catch, 85% chance to get knocked down.

**Comment by Blithering** [comment]
The butcher thing is far too strong not to be considered its main gimmick.

**Comment by Allspice** [comment]
Cut a head with an esword and stash it in a depowered disposal or some shit, they are "quite unlikely" to be found. Or melt it with acid. Not terribly difficult to round remove people consistently. Main upshot of cleaver is packaging up those abilities into one tool and making it so you don't need to swap hands, and saving a bit of footwork on the first option I mentioned.

But I feel this is getting onto a tangent. The more important question is: What beneficial effects does the failure RNG for one of the cleaver's main selling points, have for gaemplay? Tricky pens are fairly lame, but I don't see people clamoring for a 15% chance for a pen to do nothing and alert the would-be victim.

**Comment by Blithering** [comment]
Cutting a head with an esword and stashing it still leaves a body and stashed head, clicking it with a cleaver leaves three bites of meat. The two are vastly different. I don't see why the cleaver needs a thrown stun at all to get value for your TCs. Also the parapen is 1 use only, so I don't see it as comparable either.

**Comment by ShiftyRail** [comment]
Enough support to pass

**Pull request merged**
