### PR TITLE
grues no longer eat a person's clothes and backpack

### PR DESCRIPTION
**Pull request by pedr69**
[ided]

## What this does

- [x] makes people drop their shit when eaten by a grue
- [x] makes the SPS beep when dropped by a grue eating

## Why it's good
durrrr

## Changelog
 * tweak: grues will no longer eat the contents of your pockets and backpack

### CODE REVIEW

**Comment by BomberBro** [comment]
Can you figure out a way to make them eat light sources in the bag at least? If a guy has 20 flashlights in his bag you're fucked

**Comment by pedr69** [comment]
light sources in a bag don't get emitted
only the stuff you have in your hands/pockets/belt/exosuit slot
the way the light drain works is just by creating a negative strength light, so 4 * brightness=3 flashlights will drown out the lightdrain until you kill a couple people and get retard strength

**Comment by Hinaichigo** [comment]
Why not have the contents of what they eat get stored in their stomach instead so if you kill them and cut them open you can get the items out?

**Comment by pedr69** [comment]
why would the grue eat the clothes but leave the head on the floor?
would make more sense to me if the head or maybe even the entire body(possibly skeletonized) got moved into the grue

**Comment by DorainGrey** [comment]
> What about having the clothing/items of the beings they eat get stored in their stomach instead so if you kill them and cut them open you can get the items out?

Why though, Grues have already been overtuned to the extreme. Making it impossible to fight a Grue that's eaten like 6 people, they don't need even more buffs.

**Comment by Hinaichigo** [comment]
One way you could fight a very powerful grue in a dark section of maint without getting to close to it is to wear a hardsuit and leak plasma into the area and ignite it, since they don't get any more health or damage resistance no matter how much they eat and you'd get the heat damage and also illuminate the whole area, burning them. Also the light would prevent them from shunting away. If you put the plasma canister in front of you and push it, it could also act like a shield from the grue attacking directly.

**Comment by DorainGrey** [comment]
> One way you could fight a very powerful grue in a dark section of maint without getting to close to it is to wear a hardsuit and leak plasma into the area and ignite it, since they don't get any more health or damage resistance no matter how much they eat and you'd get the heat damage and also illuminate the whole area, burning them and preventing them from regenerating. Also the light would prevent them from shunting away. If you put the plasma canister in front of you and push it, it could also act like a shield from the grue attacking directly.
Yes and the instant anyone opens an airlock, including the escaping Grue, you flood the station, killing even more people.
Or the Grue just breaks down an R-Wall and leaks it for you...
Are you sure Grue even takes heat damage, it's a simplemob?

> That being said, I'm not sure if I think they should keep the heads of the people they eat in their stomach, just so people can get back into the round as crew if they choose to wait as a ghost rather than hatching as a grue; that way you can have an over-unity situation with obsgang or other ghosts joining as grues and crew eaten by grues possibly being cloned. Though it is interesting to consider like "bagging a big one" and then pulling like 4 chewed up bodies out of the grue's stomach and dragging them to medbay for treatment.

Grue's not eating Weapons in hands, is one of the few saving graces. Allows assistants to start fighting them when Sec inevitably fails.

**Comment by Hinaichigo** [comment]
Simplemobs do take temperature damage yeah.

**Comment by pedr69** [comment]
speaking of eating and gibbing, why do vox bleed blue but when they get gibbed they bleed red?

**Comment by Hinaichigo** [comment]
Calling .gib on a vox makes blue gibs last time I checked. What situation makes it red?

**Comment by Hinaichigo** [comment]
Maybe eat the clothes but leave the other stuff like backpacks, glasses, pocket contents, etc.

**Comment by pedr69** [comment]
hmm, should i call user.death() on the parent human/gib instead, so the SPS beep whenever you gib? ie EINATH/singulo/bombs?

**Pull request merged**
