### PR TITLE
new AI core look

### PR DESCRIPTION
**Pull request by pedr69**
## Why it's good

chudbot_yotsubaB_5x

## Changelog
 * imageadd: chud AI core

### CODE REVIEW

**Comment by anaxosa** [comment]
aight

**Comment by tinysaturn** [comment]
billions of non-humans must die

**Comment by pedr69** [comment]
also, fun fact for recording video of pixelated games like ss13:
x264 needs to have a resolution in multiples of 16, otherwise your output comes out looking like complete dogshit, even if your recording quality's lossless

**Comment by gurfan** [comment]
Red board thoughever

**Comment by Kromkar** [comment]
Stale meme.

**Comment by Eneocho** [comment]
>wish i knew how to enlarge a gif

I just use ezgif.com/resize to enlarge the gif. There's a config to resize without edge merging so it keeps the pixels intact.

**Comment by Eneocho** [comment]
enlarged

**Comment by ErrorsWindows** [comment]
Screenshot (1973)

**Comment by Theophrastus1** [comment]
fuck right off

**Comment by PrimeDSS13** [comment]
collabs please close this PR

**Comment by ErrorsWindows** [comment]
> collabs please close this PR

but  why?

**Comment by Hinaichigo** [comment]
Why not change the background color a bit to increase the contrast?

**Comment by pedr69** [comment]
it's yotsuba B colored
if you think another background color would make the majority of the voterbase change their mind, i can try doing that too

**Comment by anaxosa** [comment]
if your downvoting this consider your potential lack of vision

**Comment by Hinaichigo** [comment]
> it's yotsuba B colored if you think another background color would make the majority of the voterbase change their mind, i can try doing that too

Maybe black or have some sort of colorful static or glitch pattern.

**Comment by ConfusedCactus** [comment]
cringe

**Comment by Pastamadness** [comment]
Coal

**Comment by calzilla1** [comment]
NAS

**Comment by Eneocho** [comment]
Yet again we have a man of vision getting trampled by the metaclub.
They may want us to forget the soundsynth fiasco, but we remember.

**Comment by gurfan** [comment]
total Ai death

**Comment by ErrorsWindows** [comment]
i think it just looks like a cool cartoon character like on saturday television what's the issue

**Comment by Kurfursten** [comment]
Can't believe this is going in the books of "most voted on PRs" in the last year, alongside things like giving maint access to CMO, moving vending machines to TGUI, and revert removes line.

Anyway just making a call on what is essentially a tie.

**Comment by Eneocho** [comment]
For shame. We will remember this.

**Pull request closed without merging**
