### PR TITLE
Adds the Speedrunning religion

### PR DESCRIPTION
**Pull request by Irradiation**
Thread asked for this.

PS: I need better keyword names and a better Deity name.

[content]

:cl:
 * rscadd: Added the speedrun religion.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Now I can make my Narcissa Wright chaplain!

**Comment by MadmanMartian** [comment]
fairly sure there's another religion with cancer as its keyword

**Comment by Irradiation** [comment]
capture
Apparently not, or my CTRL-F fu is terrible.

**Comment by Intigracy** [comment]
don't forget dilation stations

**Comment by spoonylove** [comment]
Deity should clearly be JOHN FUCKING NUMBERS. Chaplain spawns with a timer, autism, and a can space mountain wind.

**Pull request merged**
