### PR TITLE
Adds the NT-12 semi-automatic magazine-fed shotgun.

### PR DESCRIPTION
**Pull request by Irradiation**
This shotgun uses either 4-round box magazines or 20-round drum magazines. For the sake of balance, the drum magazines will only be obtainable through adminbus, vaults, wizard summon guns or traitor bundles.

EDIT:
Due to Sonix's shotgun sound PR getting merged before this one and my branch being older than the sound PR, I'm adjusting in here properly. IT'S READY TO GO.

Credits:
-TheBimmer231 for the sprites
-@DrSnips for helping me unfuck spriting code
-@RealestEstate for unfucking an in_hand
-@SonixApache for sounds and code
nt12

:cl:
 * rscadd: Added the NT-12 semi-automatic magazine-fed shotgun.

### CODE REVIEW

**Comment by Durgen** [comment]
the gun with the drum mag would be a funny bartender traitor item

**Comment by Blithering** [comment]
Slightly autistic request here, but can you refluff it to be a third party manufacturer rather than NT? Design seems to be different to the usual black blocky affair NT usually makes

**Comment by Irradiation** [comment]
Can I get away with it because it's an NT subsidiary? Besides, the regular shotguns aren't NT-brand blocky.

**Comment by SonixApache** [comment]
sprites feel sort of out of place tbh but whatever

**Pull request merged**
