### PR TITLE
Buffs the plates for the plate carrier

### PR DESCRIPTION
**Pull request by Irradiation**
Because they're currently hilariously terrible and damage bleedthrough is a pain in the dick, thanks nu-damage resist code. Note that on rare occasions, the plates will break at a much lower damage threshold, because damage resist code isn't 100% consistent with plate code. The below results are the most consistent I've been getting.

Currently:
-Ceramic (default) plates tank NO ballistic shots (they don't reduce or absorb any damage) and can tank one (1) laser shot.
-Plasteel (ballistic) plates tank one (1) shotgun/revolver round and break, leaving you with 30 brute + bleeding.
-Ablated Ceramite (laser) plates tank seven (7) laser shots, leaving  you with 30 burn.

Buffed:
-Ceramic (default) plates tank one (1) shotgun/revolver round and break, leaving you with 6 brute and no bleeding. It also tanks four (4) laser shots, leaving you with 6 burn.
-Plasteel (ballistic) plates tank three (3) shotgun/revolver round and break, leaving you with 18 brute and no bleeding.
-Ablated Ceramite (laser) plates tank seven (7) laser shots, leaving you with 21 burn.

[tweak][balance]

:cl:
 * tweak: Buffed the plates for the plate carriers. They'll now tank more damage and reduce the amount of damage that pierces the plates every hit.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
The entire point of them is armor absorption, why would you nerf the point of them?

**Comment by Baronzegit** [comment]
> The entire point of them is armor absorption, why would you nerf the point of them?

This PR is buffing the special plate-based armors though, not nerfing them.

**Comment by MadmanMartian** [comment]
By increasing their armor base, but nerfing their armor absorption

**Comment by SonixApache** [comment]
standard plates are slightly too much now i feel

**Comment by Irradiation** [comment]
Try out the values I've changed, R0b0. 

As for the standard plates, I'm not sure if they should be midway between the specialized plates or just be a babbyshit plate.

I definitely have to try this in low pressure, though.

**Comment by ShiftyRail** [comment]
Not sure how much the "armor_absorb" var has evolved with the damage rework, but that damage rework was a straight up buff to the average damage reduction of every single armor value.

image

(Black line was the final thing being merged)

**Comment by Irradiation** [comment]
Ceramic plates are a bit less tanky to bullets now. In other news, low-pressure absolutely fucking destroys plates. Giving them atmos protection and/or max melee resist isn't doing anything to stop pressure exploding them, so I suspect pressure ignores all armor values and goes straight for their low health stat.

Any suggestions on how to make them atmos-proof, outside of jacking up their health and thus fucking up the damage absorption numbers?

**Comment by Irradiation** [comment]
Turns out that unless combat code gets reworked, there's no way to stop plates from getting destroyed by pressure, as per R0b0's own words when @Dacendeth asked him if it was a feature.
Capture

**Comment by ancientpower** [comment]
As suggested by Yred, you could make the plates ignore all damage under LOW_PRESSURE_DAMAGE (which is 2). They'd still break under high pressure but at least that makes sense.

**Comment by Irradiation** [comment]
Time to try that out

**Comment by MadmanMartian** [comment]
It is possible to get around it without having to rewrite combat code, you've just gotta make a new signal that's either triggered by bullets, explosions, punches etc. or add a new argument to the signal currently being used that tells you the source of the damage, and act accordingly.

**Comment by Kurfursten** [comment]
well r0b0 was the only one who objected and he's gone now

**Pull request merged**
