### PR TITLE
volume pump stalling fix

### PR DESCRIPTION
**Pull request by pedr69**
[easy]
image
you know how they were red forever even if you turned them off?
well now they aren't, they'll only look stalled when they're on

:cl:
 * rscadd: fixed volume pump states

### CODE REVIEW

**Comment by pedr69** [comment]
also how do i remove commits from the thing, i've been fucking around in my repo and it pastes all that shit in here too
do i need to delete it and start doing everything using new branches?

**Comment by Hinaichigo** [comment]
You either have to make a separate fork for each change, or change the "head" of the branch.
See the comments here #32184 where I encountered the same thing and DamianX provided a solution.
If you update the head of this branch and push it it'll update it here as well.

**Comment by pedr69** [comment]
>commandline stuff

i use the browser because sh*thub wont let me fuckin login anywhere else
might just nuke the repo and make it again but with proper branches this time

**Comment by Eneocho** [comment]
> also how do i remove commits from the thing, i've been fucking around in my repo and it pastes all that shit in here too do i need to delete it and start doing everything using new branches?

If you're doing browser coding (based), just go to the file you want to change and edit it then commit, you'll make a new branch on your fork that's up to date with bleeding edge and will only have the edited change you did. Now browse to that new branch (branch-2, for example) and edit all the other files you wanted to edit. You'll end up with an up to date branch with only the changed files, no commits from any previous project.

**Comment by Hinaichigo** [comment]
> i use the browser because sh*thub wont let me fuckin login anywhere else

You might need to create an access token and use that instead of using a password.

**Comment by DamianX** [comment]
You need to setup SSH keys, probably.
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Pull request merged**
