### PR TITLE
Makes Box Chemistry's table a little more organized and adds 3 small beakers

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
dreamseeker_2018-08-02_04-28-33
powercreep of the fucking CENTURY

:cl:
 * tweak: Made Box Chemistry's table a little prettier

### CODE REVIEW

**Comment by MusgardTiger** [comment]
>i can see the things on table without having to alt + click

delete this, that habit is burned into my brain

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I will not delete this and I cannot be stopped

**Comment by DamianX** [comment]
Having multiple items of the same type with the same pixel_{x,y} is a crime in 21 states

**Comment by strawberrytan** [comment]
Perfect, now all I have to do in chemistry is drag the cash register into the hall where I don't have to see it

**Pull request merged**
