### PR TITLE
Make tomes improve rune-writing even while closed.

### PR DESCRIPTION
**Pull request by Allspice**
The popup is obnoxious.

:cl:
* tweak: Tomes now improve rune-writing even while closed.

### CODE REVIEW

**Comment by Kurfursten** [comment]
The open book sprite is much more visible ~~and arguably having your vision obscured because you're reading your notes is deep immersion~~

**Comment by Allspice** [comment]
Open book is marginally larger, closed book has the spooky red eyes. I figured it's a wash.

**Comment by iFlashYou** [comment]
merge when?

**Comment by MadmanMartian** [comment]
@DeityLink thoughts?

**Comment by DeityLink** [comment]
Eh, fine I guess. You still have to open it to use stored talismans anyway.

**Pull request merged**
