### PR TITLE
Altclicking paper folds it

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
:cl:
 * rscadd: Alt-clicking paper in your hands brings up the paper folding menu

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Do I update the wiki before or after this is merged?

**Comment by RealestEstate** [comment]
I'm not too big a fan of alt-click actions because it screws me up when I try to alt click on a pile and there's a jumpsuit or will be a piece of paper on top.
just my 2 cents.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
@RealestEstate Fixed that

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Well I already updated it so me "shrugs

**Comment by RealestEstate** [comment]
nice. I upboated this PR

**Pull request merged**
