### PR TITLE
Antitoxin OD (>60 units) makes you throw up (this removes a lot of anti-toxin and fucks up your powergay ratios)

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Eventually someone was gonna have to do something about people drinking 900u antitoxin.
I want antitoxin's OD to be something that does not fuck up the day of someone who is given too much by a newbie doctor, but still dissuasive enough that people won't WANT to 900u antitox anymore.
Vomiting removes antitoxin from blood and fucks up your ratios if you're combining it with other powergay chemicals like creatine and synaptizine, but it doesn't fuck your day up otherwise. So I think it's a good solution.
Oh it also makes your screen shake an ever so tiny bit. Not enough to be debilitating in any way but still annoying enough to make you fucking hate it.

:cl:
 * tweak: Antitoxin now overdoses at 60 units. It will still heal, but it will also occasionally make you throw up.

### CODE REVIEW

**Comment by Allspice** [comment]
oh frick

**Comment by brndd** [comment]
Excellent idea.

**Comment by kilozombie** [comment]
Honestly pretty sensible overdose result

**Comment by strawberrytan** [comment]
Nice

**Comment by codeungabunga** [comment]
Overdosing is fine, however overdosing based on time in system is not fine.

This will make creatine chem backpacks that gradually inject anti toxin impossible to use, especially those that are already pre-defined in code that completely rely on it.

**Comment by brndd** [comment]
This doesn't give it a time-based overdose.

**Comment by codeungabunga** [comment]
I am not very familiar with overdose code, but I've seen `(overdose_tick && tick >= overdose_tick)`, is that not based on time in system?

**Comment by MadmanMartian** [comment]
I like the moving of the overdose check to its own function. Could be used for something interesting

**Comment by brndd** [comment]
> I am not very familiar with overdose code, but I've seen `(overdose_tick && tick >= overdose_tick)`, is that not based on time in system?

Antitox has no `overdose_tick` defined so that doesn't apply. The vomiting, however, does seem to increase in likelihood the longer your overdose goes on. At a glance it seems like it caps out at 350 ticks, which would be 600 seconds (or units).

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
What brndd said, you can't overdose on AT unless you have 60+ in blood, only thing that scales with time is the chance to vomit

**Comment by HarseTheef** [comment]
Genuinely curious, do people still do this, or is it just one of those hypothetical boogeymen that no one actually does anymore?  There are much better and easier methods out there that achieve the same results and are more or less actually permanent.  I know I moved to that because of the hassle of fiddling with making that much of the chem.  Who are the current offenders?

**Comment by Kurfursten** [comment]
Even if it doesn't affect anyone, I feel like stuffing a million antitoxin down your throat should have some side effects, even if it only affects clowns that eat the whole chem fridge. We need more side effects for shoveling pills down your throat 👍

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I did this.

**Comment by HarseTheef** [comment]
Why though, when the other method is so much damn easier and better and you get way more than choral immunity and tox recovery?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
You mean chem implants? I'm sure you can see how they're not the same thing at all. Misplaced flex

**Comment by HarseTheef** [comment]
Er, no.  Forget I said anything.  I'm sure we will see it here in another 3-4 years.

**Comment by kilozombie** [comment]
Harse is talking about milk.
It makes your bones stronger.

**Comment by brndd** [comment]
If you think there's some powergay strategy even dumber than 900u antitox, then say it out loud. If you want to keep it to yourself so you can keep powergaying, just don't say anything. We don't need that kind of smug bullshit here. Keep it in the thread.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This is the 5th most upvoted PR of all time and it barely does anything.

**Comment by bathosbathtime** [comment]
It is an interesting interaction.  That's all you need for a good change as far as I am concerned.

**Pull request merged**
