### PR TITLE
Adds three recipes that use crab meat

### PR DESCRIPTION
**Pull request by RaccoonBro**
[Content]
Someone mentioned this in the general a few days ago. There's a grand total of one recipe that uses crab meat in the game, might as well up that to four.

**Crab Cake** - 4 Nutriment
1x Crab Meat
5u Flour

**Crab Curry** - 20 Nutriment
2x Crab Meat
1x Chili Pepper
2x Tomato
10u Water

**Crab Spaghetti** - 8 Nutriment
1x Spaghetti
2x Crab Meat
5u Water

Sprites in-game:
image

:cl:
 * rscadd: Adds crab cakes, crab curry, and crab spaghetti to the microwave recipes.

### CODE REVIEW

**Comment by SkowronX** [comment]
why not a food thats just crab legs

**Comment by RaccoonBro** [comment]
If it's like spider legs that'd mean adding butchering to crabs and adding in raw crab legs as well. Could do it though!

**Comment by Kharkov72** [comment]
🦀

**Comment by Kurfursten** [comment]
>Crab Curry (along with most other curries) contains more than forty (40!) nutriment

Someone didn't think about inheritance. But it's not your fault, since the others do this too.

**Comment by RaccoonBro** [comment]
Would it be best to just remove the nutriment lines on all the child curries since they're all the same? 20 nutriment is a lot as is.

**Comment by Kurfursten** [comment]
Yes, just let them inherit the 20 from the base curry, should be more than enough for any of them.

**Comment by RaccoonBro** [comment]
Fixed, curries now give 20 nutriment. Still works with the microwave n all that.

There's a lot more stuff thats fucked in snacks.dm though, stuff like Cheddar Chips gives 13 nutriment because of the same reason, but thats for another day.

**Comment by Kurfursten** [comment]
Yes

**Comment by bathosbathtime** [comment]
Very good PR, but the quick merge makes me uncomfy.

**Comment by RaccoonBro** [comment]
Wiki updated

**Comment by nuklearcellphoneg** [comment]
How do I make surimi though?

**Pull request merged**
