### PR TITLE
Shift-MMB on things at a distance makes you point at them.

### PR DESCRIPTION
**Pull request by Allspice**
Right-clicking to point at things is pretty bad, especially if that thing is moving. I tested the only other distance-altclicks I'm aware of (silicons turning vpumps et al without mucking about with the menu, and AI doorshocks) and this didn't interfere with that; let me know if there's other distance altclicks to test I guess.
edit: welp, mmb used instead of alt-click

:cl:
* rscadd: shift+mmb-click on things at a distance to point at them.

### CODE REVIEW

**Comment by Allspice** [comment]
other possibilities mentioned:
1. mmb (and remove mmb handswitching)
2. shift+mmb

**Comment by DamianX** [comment]
I like either of those more than this.

**Comment by Pathid** [comment]
I vote for shift+mmb and adding it to hotkeys-help.

**Comment by Sooose** [comment]
Anything but alt click, please.

**Comment by SonixApache** [comment]
very nice QoL

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Did not update wiki

**Pull request merged**
