### PR TITLE
rig helmets worsen vision

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
image

and with mesons on, 
image

## Why it's good

fixes vision inconsistency #34152

## Changelog

:cl:
 * rscadd: hardsuit helmets are now less transparent

### CODE REVIEW

**Comment by Dacendeth** [comment]
1 tile feels like nothing, make it as bad as welding helmets with a suit upgrade to make it mostly negated, CE suit starts with the upgrade as well as antag rigsuits.

**Comment by pedr69** [comment]
while hardsuit helmets do have the same eyeprot value as welding helmets, giving them the same vision override seems horrible to me and i'm not even a rig baby
3 is the furthest i'd go but i don't think even 1 will get majority approval
image

**Comment by Eneocho** [comment]
fuck no
you went from basedman to c*der in one PR

**Comment by Theophrastus1** [comment]
I will always support nerfing the hardsuit crew. Make it an actual rigsuit upgrade instead like Dacendeth said. Also add departmental access to the suit lockers.

**Comment by Eneocho** [comment]
> fuck you you're the soyman

image

**Comment by Eneocho** [comment]
Some jobs (such as mining) absolutely depend on using the hardsuit constantly, and having the helm worsen the vision, even slightly, is terrible for seeing threats such as basilisks.

**Comment by Theophrastus1** [comment]
> > fuck you you're the soyman
> 
> image

crazy that you went through the trouble of creating this

**Comment by Theophrastus1** [comment]
> Some jobs (such as mining) absolutely depend on using the hardsuit constantly, and having the helm worsen the vision, even slightly, is terrible for seeing threats such as basilisks.

how is mining real? you just find the spur and then conquer the entire roid with zero effort

**Comment by Eneocho** [comment]
> crazy that you went through the trouble of creating this

took literally 20s between googling soyjak template and putting the text

>how is mining real? you just find the spur and then conquer the entire roid with zero effort

I've been wanting extra/harder roid mobs for years now.

**Comment by Exxion** [comment]
>image

Having the top edge of this image on my screen causes my entire screen to become dithered. What the fuck?

**Comment by kacurasuo** [comment]
just seems annoying tbh
please post pictures comparing and contrasting effects with mesons

**Comment by Pastamadness** [comment]
If this is what you implied was your fix to advanced welding goggles getting the same overlay it's really funny and immersive. I support giving hardsuits minor inconveniences just to encourage people to at least remove their helmets when walking inside a non-vented station. People don't even seem to remember that suits and magboots barely slowed you down in the past. 
That said if the permabanned, soyposting whiners get their way with blocking this PR, please go ahead and just remove the overlay altogether from said goggles.

**Comment by Hinaichigo** [comment]
Precursor to the EVA nerf.

**Comment by ErrorsWindows** [comment]
> this kind of superfluous "balancing" benefits nobody and only adds one more nuisance to playing the game. These kinds of changes are what lead TG into the shitter. Do you have an actual reason why you think this change is a good idea or are you just trying to implement change for the sake of change? Is someone's experience being ruined by rig suits not having a blinding effect?

rhetoric... always more rhetoric...

**Comment by PavelCIA** [comment]
This is based because it encourages ARRPEE by making people remove their helmet while on the station

**Comment by GenericGoose** [comment]
why it's good
-

close it

**Comment by Dacendeth** [comment]
The comment about miners needing full vision is silly, most of the damn time you're not in a fully lit area so one tile of vision loss does absolutely nothing.

**Comment by Hinaichigo** [comment]
Kinda seems atmospheric in a way.

**Comment by Laz0rG** [comment]
> This is based because it encourages ARRPEE by making people remove their helmet while on the station

no it does not, in fact there's literally never any reason not to just carry the hardsuit in your hand when on station unless there's a threat of ZAS. The blinding effect as it stands does literally nothing but provide a minor nuisance which is exactly why it's a terrible change.  A proper "nerf" would be to pull a TG and make it so hardsuits don't let you see behind yourself, but that would again just force people into constantly ripping off the hardsuit in atmos and carrying it in their hand. It could be argued then that nerfs would be necessary to stop people from constantly immersion-breaking in running around full speed with a heavy hardsuit in their hand, and so the cycle of nuisance balancing continues until the server transforms into a shittier TG.

**Comment by ErrorsWindows** [comment]
I kinda liked the old abandoned station on beestation that had the ancient RIGsuit which was a normal hardsuit except it made a bunch of clanking and whirring and various other noises of machinery crashing together whenever you moved in it, basically giving away your position to anyone a mile away, I'd literally be in the hallway outside the bar and the cook and bartender would be asking over the radio about why it sounds like two Transformers having sex in the bar

At least space law considers noise pollution under vandalism

**Comment by ErrorsWindows** [comment]
😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕 😕

**Comment by DorainGrey** [comment]
While I agree on the miners part somewhat, I don't think it should hit the CE suit.

**Comment by Killette2** [comment]
1 tile of blur looks weird, 3 is too gay. 2 is the sweetspot but 1 is reasonable to fuck with people wearing them on station needlessly. I don't think this will interfere with mobs at all, I'm pretty sure I could see a big blue basilisk even if there's a grey filter over it just like I can see and decipher plenty of objects in exxions picture

**Comment by githubuser4141** [comment]
> 

It's not that obnoxious it's like two sounds "whirr" and "brrr" that play when one moves, though.
Maybe a 'noise module' should be added to RIGs, one could brand it either as a movement alert, like on a IRL truck, or a comedy nose generator that requires clown ore.

**Comment by Hinaichigo** [comment]
If rigsuits were just being added in now I think this wouldn't be so controversial and would be seen as making sense. With the range set to 1 and not even fully blocking the last tile, this is much more of an aesthetic change than a balance change. It's been the way it is for a long time but this is kind of cool. Like whenever you're out in space you have this sort of reminder that your helmet is keeping you safe from the freezing vaccum, and then if you take it off or get spaced you get a clear unobstructed view of the void, but also die.

One the other hand, there is also something nice about being able to drift through space or say view your construction projects etc. without obstruction so I can see why people might not want it from an aesthetic point of view.

**Comment by Theophrastus1** [comment]
> While I agree on the miners part somewhat, I don't think it should hit the CE suit. The upgrade approach suggested is a good compromise I'd support and similar to how other servers handle it.
> 
> Also I think as a general point, people should be filling the "Why is it good" section of controversial PRs/

I'm pretty sure the CE suit was exempt explicitly since its meant to be the king of all suits, but idk ask pedr

**Comment by pedr69** [comment]
aight come to dorms

**Comment by SonixApache** [comment]
one supposed issue with RIGgers is that they can take off and put on their suit at will, thus avoiding a number of downsides by just carrying their suit around
a solution to that would be to make RIGs only donnable and doffabble by suit storage units

**Comment by Theophrastus1** [comment]
> one supposed issue with RIGgers is that they can take off and put on their suit at will, thus avoiding a number of downsides by just carrying their suit around a solution to that would be to make RIGs only donnable and doffabble by suit storage units

as much as sonix still posting on github is sad and pathetic, this isn't a necessarily bad idea.

**Comment by DorainGrey** [comment]
> one supposed issue with RIGgers is that they can take off and put on their suit at will, thus avoiding a number of downsides by just carrying their suit around a solution to that would be to make RIGs only donnable and doffabble by suit storage units

This is a much more reasonable compromise, than move speed debuffs/vision debuffs etc 
Hardsuits can only be put on at suit storage.
Provides relevance to soft suits which could still be stored and worn without the need for suit storage.

**Comment by pedr69** [comment]
i typed up an angry response but then remembered medbay
if hardsuits can't be taken off without a storage unit, a dead/injured rigbaby arriving in medbay means he's fucked because he's entombed in the suit
which i think is a pretty good downside desu

**Comment by Eneocho** [comment]
that's a terrible fucking downside what are you talking about

**Comment by ErrorsWindows** [comment]
i think there just needs to be some thing telling everybody else that this person is a rig baby sort of like how speaking was changed for zine addicts

**Comment by Laz0rG** [comment]
> a solution to that would be to make RIGs only donnable and doffabble by suit storage units

I already "suggested" that idea because it's utterly retarded. Do that and rig suits will never be worn ever again, barring setting up radioactive engines in space. You would then have to nerf spacesuits somehow, and while you're at it why not add a mandatory trans pride jumpsuit while you're at it too so we can be just like TG

**Comment by incakola** [comment]
> Could always just give rigsuits the ability to be crowbar'd off or some kind of "emergency release" for that kind of situation that can be pressed by someone.
emergency removal should somehow damage the suit
medbay should have appropriate equipment/suit storage to remove hardsuits, or perhaps make this a job for mechanics

removing the ability to remove a hardsuit by hand is also a positive for the wearer for anyone who would want to do so maliciously
wearing someone else's suit to fool another person would become more difficult
I don't like the PR
/vg/ toes the line as the last vanilla pure ss13 experience already

muh immulsions tag when

**Comment by Theophrastus1** [comment]
> > Could always just give rigsuits the ability to be crowbar'd off or some kind of "emergency release" for that kind of situation that can be pressed by someone.
> > emergency removal should somehow damage the suit
> > medbay should have appropriate equipment/suit storage to remove hardsuits, or perhaps make this a job for mechanics
> 
> removing the ability to remove a hardsuit by hand is also a positive for the wearer for anyone who would want to do so maliciously wearing someone else's suit to fool another person would become more difficult I don't like the PR /vg/ toes the line as the last vanilla pure ss13 experience already
> 
> muh immulsions tag when

Yeah, I agree with that, it was just an option for someone who would bitch about how putting on their rigsuit is putting on their casket, although if it could be done at ANY suit station to be removed, then maybe it would be fine since medbay on most maps has 2 rig lockers.

**Comment by Inorien** [comment]
As far as gameplay changes go this is very minor, though I question why its necessary

Do we have an existing **issue**? I notice the "Why its good" section of the original post is still blank. People going around wearing their hardsuits everywhere is an IC thing, not something to "fix" with code changes - this just comes across as an unrequested change that you want to make (for some reason) but can't justify. It would make more sense to prevent people eating through a hardsuit and/or internals, etc. People would hate you even more for that

**Comment by pedr69** [comment]
>eating through internals

but how would the vox eat then

**Comment by Inorien** [comment]
> >eating through internals
> 
> but how would the vox eat then

they can fuck off back to their own shitty "station" and do it there

**Comment by OfficerBeepsky** [comment]
What is the point of this change, it's not going to discourage anyone from actually using rigsuits on station when they aren't needed. 
Just going to encourage people to power game more with mesons.

If rigbabies bother you so much, just shun them IC. Fear of being called a podbaby, stopped most people taking pods.

**Comment by Killette2** [comment]
Nobody cares about the term podbaby. Pods were more relevant when our server pop is 50 or higher because then the escape shuttle can get too zoo-like. If you don't take the shuttle you'll miss a ton of action, so people avoid pods because they're boring

**Comment by pedr69** [comment]
actually i got a better idea
might work on it later

**Pull request closed without merging**
