### PR TITLE
stalled scrubbers turn red

### PR DESCRIPTION
**Pull request by pedr69**
[wip]
if you think this is a step towards goon/TG soulless atmos, please tell me to fuck off

https://user-images.githubusercontent.com/18052467/195997878-865c004b-e528-49de-a291-fac031b88229.mp4

## What this does
currently, when the scrubbers' pipe gets filled with too much gas, they stop working
this PR makes them turn red to indicate that

## Why it's good
not sure, really

## Changelog
 * imageadd: scrubbers turn red if their pipes clog

### CODE REVIEW

**Comment by pedr69** [comment]
i now see why the premapped scrubber facing left didnt turn red, but the playermade ones facing up did
image

**Comment by pedr69** [comment]
only possible problem i see is the fact the entire waste loop updates at once when it's full - updating icon_state of ~150 scrubbers at once, might cause momentary features?
i was hoping it would be easy to only turn them red when the pipe is full AND the scrubber tries to suck some gas
but it isn't easy

**Comment by Hinaichigo** [comment]
I'm also curious if updating `icon_state` is more performance heavy than updating another var.
If so I might want to optimize some stuff in #33471.

**Comment by Exxion** [comment]
It apparently is, but only slightly. Looks like about 50% more time taken than for a normal var. This is negligible unless you're updating it many thousands of times.

**Comment by adacovsk** [comment]
Do this for vents too

**Comment by pedr69** [comment]
vents work differently, instead of on/off when the pressure limit is met, they just keep working faster the more pressure there is
also, can't turn them red because red vents mean "siphoning"

perhaps by having the blue circling thing circle faster the more air moved in the last tick? but that means quite a big refactor

**Pull request merged**
