### PR TITLE
Lowered the reagent quantities for the Saltwater recipe.

### PR DESCRIPTION
**Pull request by Irradiation**
After receiving feedback and personally experiencing it, I've decided to lower the recipe cost of Saltwater from 5u Sodium Chloride + 50u Water to 5u Sodium Chloride + 20u Water. The resulting amount has been lowered to 20u from 50u. 
The idea behind this change is that currently, you need a large beaker or a mob container in order to mix Saltwater, which goes against ghetto principles. You'll be able to use small beakers/soda cans/what-have-you for Saltwater mixing now!

:cl: 

 * tweak: Lowered the recipe of Saltwater to 5u Sodium Chloride/20u Water from 5u Sodium Chloride/50u Water.
 * tweak: Lowered the resulting amount of Saltwater to 20u from 50u.

### CODE REVIEW

**Comment by Aurx** [comment]
Why not make it 1u+4u = 5u?  I see no reason that it shouldn't mix in smallest proportions.

**Comment by Irradiation** [comment]
Because when it was originally 1u + 10u, Probe complained that he would vomit when drinking water with steak, which contains 1u of Salt.

**Comment by Probe1** [comment]
Because then eating normal foods that contain salt reacts in your mob to create saltwater.

**Comment by Irradiation** [comment]
GOTTEM

**Comment by Aurx** [comment]
Then abuse the chef for serving food and drink that makes you vomit.

**Pull request merged**
