### PR TITLE
Allicin now works as botany anti-toxin again.

### PR DESCRIPTION
**Pull request by Irradiation**
Furk you Deity for removing botany anti-tox in your viro rework.

:cl:
 * rscadd: Allicin now works as botany Anti-Toxin again.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
why not just make it a child of anti toxin again?

**Comment by Irradiation** [comment]
Because Deity remade it as botany Spaceacilin and probably wouldn't like it if I turned it straight back into a child of Antitoxin.

**Comment by DeityLink** [comment]
That or we could have a second reagent and you could get antitox from kudzu instead.

**Comment by Irradiation** [comment]
Double-stacking synthetic & natural reagents for more healing is Chemistry's God-given right, you heathen.

**Comment by DeityLink** [comment]
yeah I meant plant-antitoxin, just invent a new reagent.

**Comment by Irradiation** [comment]
But *why* should we add an outright new reagent that does the exact same thing as Allicin did previously?

**Comment by DeityLink** [comment]
Because Allicin is an IRL antibiotic.

**Comment by ComradeDispenser** [comment]
Don't encourage non-antag botanists to grow kudzu just to get anti-toxin

**Comment by bathosbathtime** [comment]
>realism
>
Antibiotics don't work well against viruses or parasites. Telling someone else to make a new reagent when you repurposed an existing reagent is nuts.  Allicin already had believable functionality before it was changed.  What's worst is that this function wasn't at all replaced?  This seems like a decent solution to these problems.

**Pull request merged**
