### PR TITLE
plasma contamination tweak

### PR DESCRIPTION
**Pull request by pedr69**
relate PR #34011
## What this does
plasma can now contaminate glasses, masks and headsets
contaminated glasses burn your eyes when worn
changes the checks on hats/exosuits contaminating clothes under them

you will not go blind if you wear:
-a biosuit/spacesuit(hard hats are space suits)
-plasma resistant glasses(welding, meson, science, material, NV)
-a gas mask
## Why it's good
durr make plasma more dangerous

## Changelog
 * bugfix: wearing a hat but no glasses will no longer prevent your hat from being plasma-contaminated
 * tweak: masks, headsets and some glasses can now be plasma-contaminated
 * rscadd: plasma-contaminated glasses will make you blind

### CODE REVIEW

**Comment by ConfusedCactus** [comment]
I understand the logic, but is this actually fun? Plasmafloods being even more debilitating than they already are is not really my idea of fun.

**Comment by Eneocho** [comment]
Sorta agreeing with cactus here. Going blind is a HUGE negative (even if you know the general map layouts by heart and can navigate to medical to get ye eyes fixed). As it is currently you can at least see the shelters popping out so you can quickly make your way to them and decontaminate inside.

**Comment by pedr69** [comment]
yeah my thinking was to sort of equalise the blindness - currently you get permanently fucked in seconds if you didnt powergay some shades, and completely unscathed if you did

i do find it funny how the "nerf blindness" PR got downdooted into oblivion
and this "buff blidness" PR is also getting a negative response by the look of things

**Comment by Eneocho** [comment]
I'm all up for nerfing blindness on the other PR, it's the MUH BALANCE HURR metaclub that doesn't want the thing merged.

**Comment by angryturnip** [comment]
Mime/clown masks getting contaminated is soulless

**Comment by ErrorsWindows** [comment]
> Sorta agreeing with cactus here. Going blind is a HUGE negative (even if you know the general map layouts by heart and can navigate to medical to get ye eyes fixed). As it is currently you can at least see the shelters popping out so you can quickly make your way to them and decontaminate inside.

there was this one round where the wizard hit me with that dollar store blind spell while I was in the dorms and shit straight up took me over 4 minutes to even get into the medbay lobby, let alone get service or enter the medbay, and that was even with me right clicking shit to act as reference, thankfully it's not full on blackout blindness like the blindfold

**Comment by BomberBro** [comment]
Why do the glasses fuck up your eyes even under a gas-tight mask? Also, clown/mime masks are children of gas masks so they're immune to plasma, right?

**Comment by Eneocho** [comment]
> Why do the glasses fuck up your eyes even under a gas-tight mask? Also, clown/mime masks are children of gas masks so they're immune to plasma, right?

I think he means that if your glasses are contaminated you'll get eye damage even if wearing a gasmask.

**Comment by pedr69** [comment]
>Why do the glasses fuck up your eyes even under a gas-tight mask?

something about the mask not sealing against your face because of the glasses so the plasma can come in
can try to spaghettify a fix if you want

**Comment by Eneocho** [comment]
>something about the mask not sealing against your face because of the glasses

But you can wear glasses and masks, as seen on this image I googled.
image
>but those are specialized glasses rather than regular

Space magic, ain't gotta explain shit.
Also it is really unintuitive and would be reported as a bug.

**Comment by xeroxemnas** [comment]
whole thing reeks of salt tbh

**Comment by pedr69** [comment]
hmmm might revive this

**Pull request closed without merging**
