### PR TITLE
Literally just removes the Chemistry cash register

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
I checked the logs and in the last 6 months, 2 sales were made with this thing

### CODE REVIEW

**Comment by Tehsapper** [comment]
what about other PoSes then

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
They were used 3, 6, and 12 times in that same time so clearly they're important enough to stay

**Comment by Allspice** [comment]
Make it so you can hide small things in the POS drawer so you can grenade people as they walk by

**Comment by Exxion** [comment]
Just use a plant

**Comment by SonixApache** [comment]
>ONLY on box

**Comment by strawberrytan** [comment]
Good change, I literally drag the cash register out to hide it under the plastic flaps every round for the table space

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
@SonixApache Box and Bagel are the only maps with a chemistry point of sale and I don't want to get my fingers dirty with bagel crust

**Comment by SonixApache** [comment]
😒

**Comment by dickmuncher** [comment]
I use it, no reason to remove it if you hate it. Changes are made to make the station/server better in general. How does this make the station better? Spoiler Alert: It literally doesn't.

In the words of Senator Armstrong, the server changes to suit the individual, not the other way around.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
This particular cash register was used 2 times
2 times in 6 months
I have seen it get dragged off its table at least 2 dozen times (and those were only the instances that I personally saw)
I have even seen more custom vending machines built one tile next to it than the amount of times it was used

I think +1 table space is literally an improvement over having it there

**Comment by Dacendeth** [comment]
Let players deconstruct them for some metal, their usefulness would skyrocket.

**Comment by SonixApache** [comment]
@dickmuncher 
just use the EFTPOS if you're adamant about using shitty payment systems
or ask for cash

**Comment by Exxion** [comment]
I strongly suspect he wasn't being serious

**Comment by Intigracy** [comment]
2 uses in 6 months is abysmal

**Pull request merged**
