### PR TITLE
Can attach IV drips to rollerbeds

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
The IV doesn't gain any powers or anything like that, it just adds a clunky way to pull people and IV them at the same time.
I can't really think of any way I will personally be using this but people are free to come up with uses for it.

:cl:
 * rscadd: You can now attach IV drips to rollerbeds. The rollerbed will still accept people on top of the IV drip.

### CODE REVIEW

**Comment by DrSnips** [comment]
Is there a way to remove it?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yes, it works exactly the same as buckling, just click the rollerbed to unattach.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Remind me to update wiki with this and with chemmaster slurping

**Comment by Caboozles** [comment]
Could be very handy for on-the-move blood transfusions or emergency shuttles.

**Comment by spoonylove** [comment]
this is very useful, just for those hectic medbay days.

**Comment by Blithering** [comment]
My only complaint is it hides whether the IV is set to draw or inject, good PR otherwise and the buff that rollerbeds desperately needed

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah it looked very stupid otherwise

**Comment by tuypo1** [comment]
Really does need a way to tell at a glance if it is drawing or injecting.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Issue with that is that if I render the IV on top of the rollerbed, besides looking stupid, it also steals clicks. Ctrlclicking the IV here doesn't actually start pulling, and clickdragging people onto the IV doesn't buckle them.

I wanna say that this probably won't be an issue since people will probably only use this with IVs set to inject, but if you can think of another solution I can try. Maybe just auto-lock IVs to inject when coupled to a rollerbed?

**Comment by tuypo1** [comment]
Locking the ivs to inject may be the best solution until a spiriting based solution is available.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
done

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Updated wiki with this and with #22694

**Pull request merged**
