### PR TITLE
Replaces the bloodbag table in Metaclub with a Bloodbank fridge

### PR DESCRIPTION
**Pull request by Irradiation**
Replaces the bloodbag table in Metaclub with a Bloodbank fridge.

EDIT: Please don't hit me Probe

:cl: 
 * rscadd: Added a blood bank fridge in metaclub medbay in place of the bloodbag table in Metaclub's medbay.

### CODE REVIEW

**Comment by Probe1** [comment]
You folks are killing me with these changelogs.  Just write rscadd: Metaclub now has a bloodbank fridge instead of a table with bags.

* rscadd:  It's not necessary to talk about every single thing you did
* tweak:  just hit the high notes and balance changes
* rscdel: bloating up your list leads to players skimming harder and ignoring changes
* bugfix: you mong

**Comment by Sooose** [comment]
Now we just need to remove the one from deff and we're all done.

**Comment by Probe1** [comment]
image

@Sooose

**Comment by Sooose** [comment]
@Probe1 I meant we need to remove the bloodbank fridge because its deff.

**Pull request merged**
