### PR TITLE
emaggable clown soundsynth

### PR DESCRIPTION
**Pull request by pedr69**
[wip]
by wip i mean feel free to suggest more sounds to be added
it keeps the default sounds(good luck finding the one you want in the long ass list)
image

:cl:
 * rscadd: sound synthesizers can be emagged

### CODE REVIEW

**Comment by kane-f** [comment]
I'd like if these sounds were added to the normal list rather than just replacing them.

**Comment by Exxion** [comment]
We removed bwoink for a good reason. It's a sound with only OOC significance. Also it made people ahelp constantly asking if they were bwoinked but BYOND ate the message.
The Discord sound also only has OOC significance, though it doesn't have the latter problem. It would be funny if this were a noRP server, but it isn't.
The rest are all fine

**Comment by Eneocho** [comment]
Based
But yeah, add it to the list instead of replacing it.

**Comment by Eneocho** [comment]
Add the superfart sound effect (the one from the genetic power).

**Comment by adacovsk** [comment]
the "supermatter crystal hyperstructure currently at..."

**Comment by Eneocho** [comment]
The command message sound effect.

**Comment by pedr69** [comment]
i'm not sure about the longer musics, since they are almost 30 seconds long 
lowered the volumes for em a bunch so you can't earrape someone as easily

**Comment by Eneocho** [comment]
Add _doorstuck and _scream too (the ones the AI uses).

**Comment by pedr69** [comment]
as for 
>NOOOO REMOVE DA META SOUNDS

if the shitmins really cant respond to resulting ahelps with "iunno ask the clown", i could probably turn on shiftpitch for the bwoink so it's not the exact sound as being boinked
the discord one stays in though

**Comment by Kurfursten** [comment]
You can keep the bwoink sound only if you first permanently fix the bug where byond occasionally eats messages, including ahelps

**Comment by pedr69** [comment]
> You can keep the bwoink sound only if you first permanently fix the bug where byond occasionally eats messages, including ahelps

works on my machine, unable to reproduce

**Comment by pedr69** [comment]
[controversial]

**Comment by DamianX** [comment]
Let's not do this

**Comment by Eneocho** [comment]
Once again damian fears what he does not understand. Open this PR you fearful man.

**Comment by pedr69** [comment]
closed with a 66% majority yet line got removed with only a 53% majority... curious...

**Comment by Eneocho** [comment]
They removed it BECAUSE of the bwoink (and the discord notification. try to find the discord addicts).

**Comment by Eneocho** [comment]
@DamianX reopen this

**Comment by DamianX** [comment]
image

**Comment by pedr69** [comment]
>BWOINK LE BAD!!

non antag chaplains have access to a bwoinking tool. the holyjuke lets them play bwoinks.
https://ss13.moe/media/source/holy/Adminism.ogg

an antag clown being able to bwoink is not okay because ??? bwoink sacred? ???
i rest my case.

**Comment by Eneocho** [comment]
Just make a nominal change and reopen this, king. We will not be silenced by the cabal.

**Pull request closed without merging**
