### PR TITLE
discordworks IV PDA cartridge

### PR DESCRIPTION
**Pull request by pedr69**
[controversial][muhimmersions]
formerly open PR's : #32461 #32769 #32787

## What this does
image
discord virus PDA cartridge - has 5 uses of a virus that makes the target PDA play the discord bweep when receving messages/money
adds the discord cardridge to a hacked Ptech vendor
it also lets kharkov varedit your PDA sound to amogus

## Why it's good
https://user-images.githubusercontent.com/18052467/200643475-5245c95e-9645-456e-a894-e096c87420e2.mp4

## Changelog

:cl:
 * rscadd: Discord virus PDA cartridge
 * tweak: hacked Ptech vendors now stock Discord cartridges
 * imageadd: discord virus PDA cartridge

### CODE REVIEW

**Comment by gurfan** [comment]
No!

**Comment by pedr69** [comment]
>for the fourth time

hence the IV

**Comment by Pastamadness** [comment]
E for effort, my man

**Comment by boy2mantwicethefam** [comment]
It's funny but I hate the codebase getting sullied by Discord memes.

**Comment by Exxion** [comment]
I think you think this joke is a lot funnier than it is
Also, again, no

**Comment by NigglyWiggly** [comment]
Mentioning discord at all is already a problem

Make it play the bwoink instead so you can kill them when they’re distracted by a _different_ OOC thing

**Comment by SECBATON-GRIFFON** [comment]
-ACK!

**Pull request closed without merging**
