### PR TITLE
green balloon

### PR DESCRIPTION
**Pull request by Allspice**
a great idea stolen from deity

balloon

:cl:
* rscadd: Add an ordinary green balloon to the AutoDrobe (requires coin)

### CODE REVIEW

**Comment by ancientpower** [comment]
add a visible string to the inhands or else

**Comment by DeityLink** [comment]
Yeah it should have a visible string, just like the syndie balloon.

**Comment by Allspice** [comment]
redballoon inhand doesnt have string

**Comment by DeityLink** [comment]
wait, what is this mandela effect bs

**Comment by Jackreturnswithaveangenace** [comment]
It doesn't, but the byond and NT balloons do. It should probably have a string sprite.

Also the redballoon doesn't replicate an effect that ordinary players can see, add the string to your balloon.

**Comment by ShiftyRail** [comment]
Red ballon doesn't have a string but it doesn't look exactly like the safety square.

**Comment by DeityLink** [comment]
so either add the string or change the sprite a little

**Comment by PavelCIA** [comment]
you can't do this... how am I supposed to know who the valids are...

**Comment by bathosbathtime** [comment]
It should only work 'perfectly' if the person holding the balloon is facing the 'camera' and I don't care how meta that would be.

**Pull request merged**
