### PR TITLE
fixes LOOC color

### PR DESCRIPTION
**Pull request by pedr69**
i think i get the hang of the shithub now
the code works on my machine

Untitled

### CODE REVIEW

**Comment by DamianX** [comment]
Great first PR.

**Comment by pedr69** [comment]
what's the deal with the checks thing; i'm guessing it's to prevent nerve gas if the code doesn't compile or if the maps get deleted or something?

**Comment by ValkyrieSkies** [comment]
Ensures that merging the PR isn't going to (immediately) nuke the server.

**Comment by Exxion** [comment]
1. Checks that the code itself isn't bad in any of several very specific ways
2. Checks that it compiles
3. Checks that it compiles and doesn't break any of several very specific things

**Pull request merged**
