### PR TITLE
Adds Tier 3 parts equivalents made with plastic

### PR DESCRIPTION
**Pull request by aceedex**
A rethread of  [22572] but fixing what the science metaclub didn't seem to approve of

 But why?
So that mechanics, who are often enough forgotten by mining and such, can make their primary function of machine upgrading immediate without having to wait for RnD to do research or for mining to deliver. The parts added are tier 3 so whats the worst that can happen? some borg recharges faster somewhere if someone cares to do it?
Doing it this way as opposed to changing the material cost in the protolathe also avoids the issue of the plastic wars that spawned for scientists wanting to do research by deconstructing tier 3 for that sweet material 5.

This PR simply lets mechanics do their job a bit more readily without stepping on any toes

:cl:
 * rscadd: A special set of stock parts was added to the mechanics locker. They're reproduce able with plastic so you no longer need to bother science with it

### CODE REVIEW

**Comment by Dacendeth** [comment]
Just get bluespace bins by asking or breaking in it's not that hard.

**Comment by DrSnips** [comment]
I'd rather we just abort mechanics already. Its a joke of a job that people pretend is justified by claiming they do upgrades or anything. Their machines to flatpack and such are outclassed by plastic bags. It solely exists to be assistant++ who want to do autism projects.

**Comment by aceedex** [comment]
A job shouldn't break in to places to do its thing tbh. This is the best way I could see to reconcile that and sci autism about plastic flaps to do research

**Comment by boy2mantwicethefam** [comment]
I'm boy2mantwicethefam and this is my favorite PR on /vg/station.

**Comment by aceedex** [comment]
thank you barry very cool

**Comment by DrSnips** [comment]
A possible alternative is that you make the gen fab or something a bit more robust and able to replace some mats in an item's cost with plastic at some MAGIC NUMBER conversion ratio (ie. 1 silver = 3 plastic)

**Comment by SonixApache** [comment]
\>this PR lets mechanics literally skip research
:+1: on plastic equivalent tier 3 parts
:-1: on giving them to mechanics at roundstart for free (what the fuck were you thinking?)

**Comment by aceedex** [comment]
What exactly is the issue sonix.  T3s don't do anything gamebreaking. Research isn't exactly hard for mechanics to do, specially if they're just looking for T3s.  What's more they'd still have to install the parts manually if they decide to mass produce them roundstart because they don't start with rpeds. I think the fact that they'd have to sit there and reconstruct machines by hand if they skip out on research is a very fair exchange

**Comment by SonixApache** [comment]
Giving away even more free roundstarts skips to research (see also: mecha syringe guns) devalues research even further
QoLing mechanics specifically just so they can get their "job checklist before fucking off" done faster is fucking gay, especially if you don't mirror it for science in general.
Allowing both jobs to work together with more easy, 👍 
Giving each job even less to do and even less reason to exist, 👎 

What if the mechanics machines were just in the R&D lab, and "mechanic" was just an alt-title for scientists...?

**Comment by aceedex** [comment]
Id say that that's beyond the scope of the PR, but that's also you could make that argument for about half the jobs in the station.
It's also not letting them do their job checklist and skip to doing whatever. Machine upgrading honeslty takes a little while. You print out all the parts and have to go installing them department by department either by having to wait on people letting you through or breaking in like a weird reverse greyshit. Specially takes time if you're doing it by hand. I agree that it's a little strange as a research skip but, consider this. If a mechanic wants to rush research why would he use these new parts when they can do it faster by using the things in the tcomms closet they have access to?
I don't see it as anything major but I guess it's one of those agree to disagree things

**Comment by yackemflam** [comment]
I say that jobs should need each other to do well, there's a reason why sec doesn't have some of medbays tech and vice versa
It's why science doesn't have a printer nor do they start with glubbs etc
That's why I'm always annoyed with xenoarch xenobot and toxins being on the roid.
RnD should need miners to grab the materials and miners need scientists/mechanics to make/give new mining shit

**Comment by aceedex** [comment]
I sort of like the departmental co operation meme but I don't think a job should have to be subject to two other departments co operating in order to do their main thing. Specially if it's as time consuming and borderline unimpactful as machine upgrades can be

**Comment by yackemflam** [comment]
T2 upgrades already does that with the parts costing only glass and metal

**Comment by aceedex** [comment]
Thats true, but T2's are in a weird purgatory. Any sort of time spent upgrading anything to T2's is a complete waste of time that's better spent securing the materials and research to get T3's. Otherwise you spend the better part of a round making stuff a _tiny_ little bit better instead of a little bit better, only to either have to do it again when materials for parts become available, have some science dude do it again because they had materials all along or, you go do something else because doing what you just did for an extremely marginal gain is not fun.

Personally speaking I'd have T2's removed altogether if only to clear the bloat the stock parts tab on the protolathe has. Ive never seen a practical use for these guys and it really feels like they're a hold over from a time where rounds took much longer

**Comment by yackemflam** [comment]
Or you can just upgrade to t2 and if science/mining doesn't give you the materials to get t3 OR if there's no mining you still did the station good
you also can do other stuff like repairing rooms and remodeling other rooms. There's an abandoned office that you can make into something

**Comment by aceedex** [comment]
again, from a time investment standpoint, youre simply better off going to mine the things yourself and all the hurdles that that entails instead of touching T2's
Also the point of the PR isnt that mechanics dont have anything to do, but just to add a bit more independence and structure to their main gimmick of being responsible for machine upgrades, instead of maybe I just do whatever autism project if mats dont come or I go double dip jobs since mats arent coming. remember that even if these new parts are there roundstart there's only 50 plastic that the mechanics start with that also gets used for whatever machine duplication there is. There's a bit of time investment to the plastic T3's as they're either dependent on botany instead of mining or they have to take some time to set up a plastillium farm.

**Comment by yackemflam** [comment]
my point is that mechanics are already fine with t2's and shouldn't be self sufficient in almost everything.
Plastic isn't even a problem when you can order a stack of 25 sheets for cheap

**Comment by ancientpower** [comment]
why is this so controversial, at worst this PR will do nothing and at best it will make a support role more likely to actually do something useful

**Comment by yackemflam** [comment]
people are getting tired of powercreep

**Comment by aceedex** [comment]
And like I explained T2s are a hodgepodge of poor design that are best left ignored in a round. Even if you order the plastic from cargo then you're still dependant on cargo to approve and deliver. 
To call this powercrepé is also a little over the top. Like I said in the OP, what's the worst that happens? Some dude spends 20 minutes making machines better and some Borg somewhere gets a fast charge ?

**Comment by yackemflam** [comment]
that's exactly why powercreep is so strong, everything gets stronger over time to the point where everything is too strong

**Comment by FudgePucker** [comment]
Mechanics has its role as the bridge job between science and engineering, like mining is between science and cargo. CE doesnt get science and research access, but does have mechanic access.

I support the idea of alt tier three parts that require plastic, but they could require research behind the protolathe. That might mean more junk into the feature bloated tumor, but it would mean locking the parts behind some research time gate. Mechanics can just go over to tech storage to get the machine to do research or just print the board, they cant go mining.

**Comment by yackemflam** [comment]
It used to be that scientists couldn't go mining either, and there are people who thinks that the outpost shouldn't even be a thing in the first place for different reasons

**Comment by aceedex** [comment]
I'd have done that fudge, but the stock part tab seriously makes me want to commit gun kiss every time I load it up

**Comment by PJB3005** [comment]
First, I am *99%* sure we had a powercreep PR like this before a few years ago and it ended up getting reverted.

Preamble: mechanics don't do fucking shit even when they *have* the materials to upgrade the station.

All the rounds that I've tried playing xenoarch I try to delegate machine upgrades to the mechanics so I can fuck off to the roid faster. Giving them bluespace RPED with bluespace bins loaded. Loading up the protolathe to capacity.

They never fucking do it, and I *never* hear them ask me for help when I am going full upgrades-from-R&D myself either.

I wholeheartedly agree that mechanics need to be made more useful. This PR, however, is just poorly thought out powercreep. You wanna know why? Because it doesn't fix the core god damn issue: **THEY DON'T HAVE AN RPED**. No god damn mechanic is gonna bother upgrading all the machines around the station if it takes forever.

Allow mechanics to make an RPED with plastic instead of gold, round start. Hell, maybe give them one at round start. It's not problematic balance-wise because if they gave a fuck they'd take the gold in the vault to make one instead. **Then** allow them to make **T2** parts with plastic. **Round start.** Treat the R&D version as the more cost-effective variant that they'd prefer to use when R&D gets their heads out of their ass.

Now mechanics has their hands full with round start work. T2 parts finally get their time to shine, and shit will actually get upgraded. 

What I especially like about this is that R&D could actually ask mechanics to upgrade their machines for them. Why? Because there's that annoying spot of wanting to make a bluespace RPED to upgrade R&D but then you're wasting a lot more diamond constructing the bluespace RPED than if you upgraded R&D with a regular RPED first. I know I would ask them to do this if I knew they were competent.

**Comment by aceedex** [comment]
Full disclosure I actually thought someone had gone on ahead and made an rped cost plastic when I first made this PR since someone had mentioned that to me. That's next on the list once this goes through. 

As for the T2s idea, it's a nice idea that doesn't rock the boat but I already explained how I feel about T2s and how much of a waste of time they up there.

**Comment by yackemflam** [comment]
T3's should stay strong and a pain in the ass to actually get. Making them piss easy would completely nullify the point of T2's and at that point you should just remove them

**Comment by aceedex** [comment]
That's the thing they're already piss easy to make just not for the job that requires them. 
I will look into removing T2s because  I hate the stock part tab clutter  but again, step by step

**Comment by PJB3005** [comment]
> That's the thing they're already piss easy to make just not for the job that requires them.

Bullshit. Getting materials to make T3s as mechanics is not difficult at all, **you just have to god damn ask**. Miners bring shit to R&D first because *they give them their drill*. Not because mechanics shouldn't get materials.

If you actually bothered to god damn ask for materials you'd *get them* to upgrade the station with.

Mechanics RARELY cooperate with R&D in my experience and it's *never* my fault as the person doing R&D. Always the mechanics.

**Comment by aceedex** [comment]
🤷
In literally every single mechanic round for the last month that I've played and a very significant time on my overall playtime I hound both mining and rnd for materials for the end result to be "just go in to rnd and pilfer what you can" 
Which I don't fault the players for, shit happens and mechanics get forgotten is the way of the world. Hence this PR

**Comment by yackemflam** [comment]
again, this pr is just going to make t2 parts a lot less worth it and completely glossed over because people will just go for t3's even more

**Comment by SonixApache** [comment]
bluespace
matter
bins

**Comment by aceedex** [comment]
If you're asking for and installing bluespace matter bins  in sci you might as well be asking for mats. They're neat but don't really change the concept

**Comment by FudgePucker** [comment]
Last time I was a mechanic and asked science for materials I got told to fuck off.

Maybe the best solution is to add another category to the protolathe, plastic utilities (or just plastic or whatever the guy who does it wants to call it), this could include the tier three plastic parts, a RPED that requires plastic, and could be used for future mechanic toys. This would solve part of the "power creep" argument by requiring the research time gate, but also side step adding to the stock part tumor, and it wont have that much of an impact on the protolathe menu as a whole because you can enable disable catagorys. I feel like this is the best compromise and the way forward for this PR, it would also add room to expand on the mechanic job as a whole. Maybe add broken atmospheric devices to it like limitless scrubbers to the section, so that mechanics can start to become more intertwined with engineering, but that is outside the scope of this PR, just looking into the future.

**Comment by GoodG1448** [comment]
What if, like, we give science and mechanics a single bluespace bin at roundstart so they can share a small ammount of mats.

**Comment by SonixApache** [comment]
what if the mechanics didn't exist as a seperate entity, and 'mechanic' was just an alt-title for scientists or roboticists

there's no materials problem if the materials are all in the same room

**Comment by PJB3005** [comment]
There's no materials problem either if people are not-stupid enough to make bluespace matter bins.

I don't like the idea of merging mechanics and scientists because it's give even *more* powercreep to the job.

**Comment by FudgePucker** [comment]
Like I said earlier, Mechanics is the engineering science bridge job, just like miner is the science cargo bridge job. If you remove mechanics you need to give CE research and science access.

Also why not just remove tier one stock parts from the protolathe? The autolathe can produce them

**Comment by PJB3005** [comment]
> just like miner is the science cargo bridge job

What? That analogy is just completely incorrect.

> Also why not just remove tier one stock parts from the protolathe? The autolathe can produce them.

The autolathe menu is hot garbage compared to the R&D console protolathe menu, for one.

**Comment by DamianX** [comment]
Controversial and inactive.

**Pull request closed without merging**
