### PR TITLE
bootyborg upgrade

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
adds a borg upgrade to the traders and the old vendotron (and spacemart, since that picks from every existing item)
image
the ass gets removed if the cyborg gets a module reset

## Why it's good
fetish content

## Changelog
 * rscadd: cyborg b.r.a.p. upgrades have been spotted in shoal warehouses.

### CODE REVIEW

**Comment by west3436** [comment]
\>why it's good
\>fetish content

**Comment by kernikov** [comment]
I demand equal rights.
Where are the boobie borgs???

**Comment by gurfan** [comment]
Installing the module should automatically pick the color that corresponds to your module type (red for sec, blue for standard, etc)
Being able to tell what module a cyborg is at a glance is important.

**Comment by pedr69** [comment]
>should automatically pick the color that corresponds to your module type

that's what i was thinking of too, will try and think of something to do with the mining module
>you only added it to the vendotron

the trader box picks from all defined borg upgrades, minus the gripper. the booty is in by default.

if anyone wants to sprite booty moMMI's go ahead and i'll add em too

**Comment by wankov** [comment]
this looks like a great addition to the game

**Comment by Pastamadness** [comment]
No trader please. Make it exclusive to the old vendotron and spessmart.
Trader is too common a source for this.

**Comment by Theophrastus1** [comment]
> No trader please. Make it exclusive to the old vendotron and spessmart. Trader is too common a source for this. Also, some sort of "polite" naming for the module to make it sound more like a real upgrade instead of some sex toy addon would be nice in my opinion.

exhaust upgrade

**Comment by ErrorsWindows** [comment]
> >why it's good >fetish content

well you can't say they're beating around the bush for the pull request writing now

**Comment by pedr69** [comment]
i can't for the life of me get the module check to work
`borg.module == SECURITY_MODULE` doesn't work
`istype(borg.module, SECURITY_MODULE)` doesn't either
how the fuck do i do this

**Comment by Eneocho** [comment]
how about borg.module = SECURITY_MODULE

**Comment by pedr69** [comment]
>:warning: assignment in condition, may have intended == operator instead

i could theoretically try checking the sprites list to see which module's selected but that's a level of shitcode i'm not willing to commit to the repo <sub><sub>yet</sub></sub>

**Comment by Eneocho** [comment]
Upgrade could be named:
* Active Shielding System
* BOdy Override TYpesetter (I tried REALLY hard to come up with a good sounding acronym that actually used all 5 letters in BOOTY instead of this but I couldn't).
* Digitally Upgraded Melee Protection

**Comment by Eneocho** [comment]
Try `if(modtype == (SECURITY_MODULE))`, that's how the robot.dm file checks for your security module (and gives you the FOLLOW YOUR LAWSET ABOVE EVERYTHING ELSE reminder).

**Comment by pedr69** [comment]
with how big the rack is on engi/mining models, i wouldn't be surprised to see an influx of those borg flavors

**Comment by Hinaichigo** [comment]
> i can't for the life of me get the module check to work `borg.module == SECURITY_MODULE` doesn't work `istype(borg.module, SECURITY_MODULE)` doesn't either how the fuck do i do this

Maybe try ispath() instead of istype()?

**Comment by pedr69** [comment]
nvm enocho already PM'd me the fix

**Comment by Pastamadness** [comment]
I still hate them but you've implemented what I suggested so I'm removing the thumbs down.

**Comment by Eneocho** [comment]
gorrillionaires when

**Comment by ErrorsWindows** [comment]
today: booty borgs
tomorrow: booty borg emagged keistering functionality

the future is looking bright

**Comment by SonixApache** [comment]
repoban when

**Comment by Laz0rG** [comment]
next thing you know tajaran aren't a valid race and are a round start choice and felinids get added from TG. Slippery slope.

**Comment by ErrorsWindows** [comment]
> with how big the rack is on engi/mining models, i wouldn't be surprised to see an influx of those borg flavors

Screenshot (2026)

**Comment by githubuser4141** [comment]
> Upgrade could be named:
> 
> * Active Shielding System
> * BOdy Override TYpesetter (I tried REALLY hard to come up with a good sounding acronym that actually used all 5 letters in BOOTY instead of this but I couldn't).
> * Digitally Upgraded Melee Protection

Imo it's bad faithy to trick people into installing joke modules that one would get hazed for, the names should communicate clearly what they are, and have plausible IC name
Maybe if the upgrades have their initialism spelt out like (Cyborg Module: Digitally Upgraded Melee Protection [DUMPy]) in the exofab menu it'd be a bit more clear? It'd be cool if it actually did upgrade the armour at the cost of, say, materials - speed & power efficiency?

**Comment by Pastamadness** [comment]
> It probably wouldn't be as bad if it actually gave a boost to armour at the cost of materials, speed and/or power efficiency - so you'd look ridiculous and would get bullied for it but newbies wouldn't feel too bad if it had actual benefits

I think that giving it actual, situation purpose defeats the whole point of it being just a joke upgrade module. The old vendotron already has its own selection of obscurely named and expensive tools most people have no use for and to me people buying random stuff that might be useless or funny is part of its gimmick.
Also, the shitty robotfucker sprite is its own reward both for those who would make fun of it or like it.

**Comment by pedr69** [comment]
you really think the BRAP doesn't spell it out clearly enough?

**Comment by githubuser4141** [comment]
> you really think the BRAP doesn't spell it out clearly enough?

kinda? I've known SS13 for 5+ years now and I definitely didn't pay attention to the 'funny memes' right away. BRAP is okay because it doesn't imply an upgrade. 'Active Shield System' is a pretty mean name imo.

**Comment by Eneocho** [comment]
Active Shield System, a toggleable system that uses powerful electromagnetic plates to reactively shield from structural damage. This system uses a lot of power, equal to 30x the damage nullified and halves the damage received to any component or structure. Cyborg structural appearance is reworked in order to fit the specialized electromagnets.

**Comment by Securitymain** [comment]
when

**Comment by Kurfursten** [comment]
Traders are uncommon, traders who buy the random borg upgrade box are nearly nonexistent. Appearing on the vendor list is quite rare. This is mostly harmless because I think it will only appear in shifts where squidmoko is adminning.

**Comment by Laz0rG** [comment]
It's over.

**Pull request merged**
