### PR TITLE
Fixes False Fangs not letting you bite

### LINKED ISSUE #26389: Fake vampire teeth are too fake
(WEB REPORT BY: rubylips REMOTE: 206.221.180.138:7777)
# Revision
17342d950988ef005a55f9b771cea44c00189e18

# Description
Fake vampire teeth from the cargo halloween costume crate don't let you bite people. They make you punch them like wearing a normal mask does. This is obviously a gamebreaking glitch.
# Steps to Reproduce
Wear fake teeth
Try bite and harm intent on man
# What you Expected
Bite man
# What Actually Happened
Punch man

### PR DESCRIPTION
**Pull request by RaccoonBro**
[bugfix]
fixes #26389

:cl:
 * bigfix: You can now bite people while wearing False Fangs from Cargo

### CODE REVIEW

**Comment by DamianX** [comment]
>Apparently the overlay never went away if you took glowing false fangs off, this fixes that too!

How did you determine that was happening and how did you test that your fix works?
`update_icon` is not implemented for `/obj/item/clothing/mask/vamp_fangs`, and it certainly doesn't take a mob as a parameter.

What are you doing?

**Comment by RaccoonBro** [comment]
leftover from trying to troubleshoot some bug that popped up during testing that left the glowing teeth overlay on your character. not sure what caused it exactly, but it isn't an issue anymore after removing that line so ¯\_(ツ)_/¯

**Comment by Dacendeth** [comment]
I remember the fangs icons persisting after taking them off, was inconstant before but it definitely happened from time to time.

**Comment by RaccoonBro** [comment]
I haven't been able to recreate the bug, and there was nothing in the player's vars that would cause it to happen from what I saw.

**Comment by GreatBigFailure** [comment]
You've saved the server.

**Comment by Kurfursten** [comment]
So you definitely tested this?

**Comment by RaccoonBro** [comment]
yep, works solid

**Pull request merged**
