### PR TITLE
Adds the NATO phonetic alphabet as a default language for deathsquads.

### PR DESCRIPTION
**Pull request by Allspice**
deathsquad lang

Language key is ~%~ &. Thinking of speech/ask/exclaim verbs to use.

:cl:
* rscadd: Deathsquad can now talk in a phonetic language with :&

### CODE REVIEW

**Comment by SonixApache** [comment]
`conveys "".`, `reports ""!`, `questions ""?`
or just stick with the default really

**Comment by DrSnips** [comment]
% is used by the insectoids. Once again kulling of some of the languages when?

**Comment by Blithering** [comment]
I know few people have it on, but it would be fun to have the default audible speech be changed to combine grunt mumbling when speaking this language

**Comment by jknpj** [comment]
Requesting:
CP, HQ, contact, backup

**Comment by Kurfursten** [comment]
Update wiki or suffer my curse

**Pull request merged**
