### PR TITLE
Hypozine TC cost reduction

### PR DESCRIPTION
**Pull request by Irradiation**
**The TC price for the "Lethal Speed Chemical" (Hypozine) has been reduced from 12 TC to 4 TC.**

As mentioned, I just lowered the price from 12 to 4. The idea behind this change is that:
A) There's mostly no incentive to use the traitor chemicals when you can do the same, if not better, with regular chemistry.

B) 4 TC for a chem that requires at least 5u to kill someone is a bit excessive, when you compare it to the "Explosive Hug Chemical (Bicarodyne)", which has a VERY slow metabolism and only needs 1u in the body to do its thing. 

C) When compared to Chef special sauce, the sauce costs 2 TC, gives you 20u of it. You need 2u to kill someone and your target will KNOW when they've eaten it. That's 10 kills for 2 TC. Same with Hypozine. By dropping the Hypozine cost to 4 TC, you'll get 6 kills for 4 TC,

### CODE REVIEW

**Comment by HarseTheef** [comment]
8 is still insane.  An emag is inifinitely more useful and the same price.  Drop it to 4 or 6 honestly.

**Comment by Irradiation** [comment]
Good point Harse, especially when the victim KNOWS they took Hypozine because they're going at Mach 2, you're only getting 6 potential kills out of 30u of hypozine....while bicarodyne is 30 potential explosive kills and is more subtle.

**Comment by SarahJohnson489** [comment]
Yeah, may as well help it get used over putting an instacrit pill in the bicard pool.

**Comment by Dacendeth** [comment]
There is a difference in obviousness though, it's possible there can be multiple people in medbay that could have ordered hypozine while there's only one chef to point fingers at. That being said I still think the price of hypozine is way to high even at 8 given you can shout about it over the radio as soon as you realize you're going mach 5

**Comment by Irradiation** [comment]
After the discussion had in this PR, talking with people on the discord and crunching some numbers, I've come to realize that 8 TC is still overly expensive if you compare it to Chef Special Sauce. 2 TC will get you 20u of Chef Sauce. you need 4u to kill someone, so that's 5 kills for 2 TC. With this extra change, Hypozine would be 6 kills for 4 TC. And as mentioned multiple times before, people will KNOW that they've eaten hypozine and like the Chef, there's only 1 or 2 potential suspects to validsalad.

**Pull request merged**
