### PR TITLE
pAIs can now be inserted into beepsky

### PR DESCRIPTION
**Pull request by aceedex**
[WiP] [dnm] [balance] [discussion]
https://my.mixtape.moe/tdqepd.mp4
At the moment is in a rough state because I know there's gonna be a lot of opinions about it, and I want to get some input before doing too much. As of right now you can insert, remove a pAI and the pAI in control can only stun like a madman. The final idea is for paisky to be able to only stun and cuff, any sort of callouts are left to the pAI player, and perhalps extend this to e209s. I do wonder if ideally it would be locked behind security access, like a button in the secbot control menu, or if leaving it for everyone would be ok. 
:cl:
 * rscadd: pais can now be inserted into securitrons. be extra nice to beepsky

### CODE REVIEW

**Comment by bathosbathtime** [comment]
Anything more than the pAI riding along while being nothing more than a hitchhiker to beepsky is getting a no from me.
I'm afraid anything else would result in creating an unstoppable monster for security or completely gut security's strongest tool by clicking on it with a pAI.

**Comment by Cockswain** [comment]
Perhaps you could simply allow the PAI to pilot beepsky with a sechud, and it can only interact with people who are set to arrest. regardless, it will take sec access to open up a securitron unless you have an emag.

**Comment by aceedex** [comment]
It doesnt have to be one or the other. pAIs in bots use different procs, so its completely possible to have no impact on regular secbots.

jkp also floated the idea of making a child of secbots for pais, which is also a good solution

**Comment by spoonylove** [comment]
Sec access would be the ideal balance for putting the pAI into a secbot. I think being only able to target arrest targets is also pretty fair. I've long wished for pAI ED209s tho so not sure how much my opinion matters. from the vid, some kind of charge/cooldown seems necessary. If this proves too controversial I would personally be happy with a pAI cheapsky spamming *law.

**Comment by Sooose** [comment]
A valid hunting silicon that doesn't have the normal law restraints, how horrifying. BIG no from me.

**Comment by aceedex** [comment]
well, here's an idea to float by you. pAI beepsky could be toggled to connect/disconnect from beepsky. The toggle would allow the pAI to simply toggle movement, and it would have to disconnect from control to allow beepsky to do any sort of arrest

**Comment by Kurfursten** [comment]
This does not appear as though it can pass in its current form

**Comment by aceedex** [comment]
Ye, doesnt seem to be much interest. Ah well

**Pull request closed without merging**
