### PR TITLE
Adds a client preference to switch between "toggle pull" and "always pull"

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Toggle pull (default behavior, same as before):
When ctrl+clicking something you're already pulling, you will stop pulling.
Always pull:
When ctrl+clicking something you're already pulling, you will continue pulling (nothing happens).

I wanted this for a long time since I forget I'm pulling people sometimes and when I click them again I accidentally let go.

:cl:
 * rscadd: Added a client preference that lets you choose to ignore ctrl+clicks on things you were already pulling, so you don't accidentally let go of them.
 * tweak: Trying to pull yourself is now a shortcut to stop pulling.

### CODE REVIEW

**Comment by SonixApache** [comment]
i wish we had those TG status things, so you could just see a "YOU ARE PULLING" icon that is more obvious than the tiny thing in the bottom right

**Comment by Kammerjunk** [comment]
btw
ADMIN LOG: Error #: 1 - table client has no column named pulltoggle

**Comment by SonixApache** [comment]
@Kammerjunk when was that? Because  #19541 should've solved that.

**Comment by Kurfursten** [comment]
Shifty reports it's still happening on live

Seems to happen when someone saves their prefs

**Comment by SonixApache** [comment]
well i turned the thing on and then the chicken turned the thing off so I guess it's not the thing that's doing it

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
For any poor soul trying to use this as reference on how to add client preferences
I set up the migration wrong and was fixed here https://github.com/vgstation-coders/vgstation13/commit/34f72c28e6be4f001e3c6b8bd05d1747097c7671

**Pull request merged**
