### PR TITLE
Disables blood&gib&tracks persistence

### LINKED ISSUE #23124: Maybe it's time to tone down or revert permagunk
#### Description of issue

Permagunk is a bad addition for the game for two reasons.

Chiefly, there is very little way to explain it IC-wise ; it boils down to the tentative "morning shift are animals", which gets boring to repeat after the n-th time.
As a result, you end up with a station of sociopaths who are content to ignore the rotting corpse next to them if there's no janitor or if there's no soap available.
The end result is inherently harmful to RP ; it's harder to keep in character when there's 4-th wall breaking messes everywhere?

How can your submarines immerse themselves in such conditions ?

Secondly, permagunk makes it a lot more difficult to detect signs of unusual activity or messes ; was this bloodtrail leading to maint from a previous shift, or did someone just get murdered ?
Did someone kill a borg in maintenance, or is it just junk from a round before ?

Combine that with the tendency of rounds to go to shit relatively fast, with dozens of blood tracks, vomits, and other effects (particularly visible in places like medbay), and you end up in a confused haze in which you ignore any and all blood because it's gonna be a false lead 75% of the time.

Much like the first point, this further encourages the idea that spacemen are just sociopaths, used to living in the trash, and removes a lot of opportunities to build up narratives by following blood tracks in maintenance.

#### How to fix it

Reverting it completely may be a bit too excessive, but I believe capping the number of decals and trash carried over from one round to the next to, say, 10 **per zone** wouldn't be so bad.

The decals should also not last more than 1 round.

Feel free to discuss.
[discussion]

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
[vote]
Fixes #23124

This code was made to be so modular that you can simply untick these files. The current snapshot of blood in every station will remain in Pomf's PC, preserved until the end of time, in case someone in the distant year of 2023 re-enables blood persistence and Box will once again become flush with the blood of 2019 jobbies.

:cl:
 * rscdel: Disabled persistence for blood, gibs, and tracks. Other cleanable decals like vomit will still remain, as will rubbish like food wrappings.

### CODE REVIEW

**Comment by Kitfox88** [comment]
remove puke too reeeeeee

**Comment by utilitas-** [comment]
How 'bout no. It's the type of silly and weird shit that I love about the game, the same shit you lot seem to be *hell bent on removing wholly from the game*. If you hate it so much, make less messes or get a bar of soap and clean it up yourself.

**Comment by ancientpower** [comment]
> 
> 
> How 'bout no. It's the type of silly and weird shit that I love about the game, the same shit you lot seem to be _hell bent on removing wholly from the game_. If you hate it so much, make less messes or get a bar of soap and clean it up yourself.

This only removes the types of decals that fuck with detectives and investigation, vomit and garbage still remain.

**Comment by GoodG1448** [comment]
What about oil/dead borg-MoMMI stuff?

**Comment by GlassEclipse** [comment]
I like this change for RP reasons. The station is bathed in blood after a cult round and people just walk around, doing their jobs like normal. Doesn't make much sense.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I think "oil" is just recolored blood but I could be wrong.

**Comment by Sooose** [comment]
My immulsions are saved.

**Comment by utilitas-** [comment]
@ancientpower I never had a single problem with the persistent blood stains as detective. They are a different hue than all the other blood, don't interact like fresh blood and don't show up as fresh blood in the noir blood-o-vision power. If it fucks with you, you simply have to git gud.

**Comment by Blithering** [comment]
Spawning in as captain round start and finding that your comfy chair is sitting in someone's intestines is a bit immulsion breaking, particularly when you're expected to pretend they've been there all along

**Comment by Kurfursten** [comment]
I don't think this actually needs a server vote, in the span of a week it has shown that it is not a contentious issue with overwhelming support.

**Pull request merged**
