### PR TITLE
Syndicate robot module changes

### PR DESCRIPTION
**Pull request by aceedex**
First part of the big borg changes. This PR does the following
-Removes the emag from the blitz module borg. 
This change is made in the hopes that the borg cannot simply go out and kill all jobbies for free. The lack of an emag would hopefully mean that the borg is encouraged to stay near the operatives and act as a supplement in firefights instead of just emagging everything and killing everyone. I dont think this change would be extremely significant to the blitz module and Im more than open to reverse it myself it comes to pass that the borg is severely neutered by it. Note that the plasma axe the borg comes equipped with is similar to the combat borg's meaning that they can cut through walls and girders if they become stuck. 

-Gives the crisis module a max switchtool and changes the syndie hover bed to have parity with the surgery roller beds
The crisis module is in charge of fixing and doing surgery on the most at risk, chaotic prone to exploding in your face killing you patients in the game. Speed is of the essence, and not stabbing your patient because your bed sucks is also kind of nice. I dont think this fixes how they never get picked by ops but I think it helps them be a lot less dysfunctional 
:cl:
 * rscadd: Syndicate crisis borgs now have a max surgeon's switchtool
 * tweak: Crisis borg roller beds no longer have a chance to fail a surgery step
 * rscdel: Removed the emag module from the Syndicate blitzkrieg borg

### CODE REVIEW

**Comment by icantthinkofanameritenow** [comment]
The big issue with the crisis borg is that ops rarely if ever have the time to even try surgery, borg or no borg. There's no real motivation to do so since ops are only effective when they hit fast and hard- it's simpler to leave a wounded guy behind than it is to give the crew a chance to rally as you waste time fixing him up. 

Its role needs to be fundamentally changed if it's going to get any kind of use.

**Comment by aceedex** [comment]
I think it's role is very fine as it is, which is to say be an anchor for particularly flukey ops. Ill definitely look into making it better at this though because for sure it's not what it should be. Some ideas ive been thinking of is the inclusion of a hookshot so it can drag more than one person and recycling the idea of some super drug that works when buckled in to something, so that crit ops can be saved easier but living ops arent god mode

**Comment by iFlashYou** [comment]
Would be nice if the emag one was its own PR

**Comment by PrimeDSS13** [comment]
I agree with iFlashYou, one of these changes are a lot more major than the others.

**Pull request merged**
