### PR TITLE
Expands metaclub station perma a bit.

### LINKED ISSUE #21517: Meta's Perma needs some stuff (feature request)
Current meta's Perma is miles better than what it used to be, but still it's lacking some stuff to bring it on equal levels with the other permas

It lacks a grinder, or a mortar to get flour, sugar, ketchup or hotsauce.
it lacks a table to have a spot where to eat.
it doesn't even has salt shakers so that's pretty much cutting you from a lot of culinary recipes
no knifes, not even plastic ones so you can't cut bread, cakes or pies

i would also mention that it would be great if there was a chicken on it, but that's box's gimmick so yeah
maybe add some loose parts outside to, like a single wooden plank and a metal sheet so you have to work for those things, giving you a sense that your new home is getting better with time.

### PR DESCRIPTION
**Pull request by Irradiation**
Closes #21517 

This PR adds:
-A cow
-A bucket
-A dinning room
-A grinder
-Ustensils
-Salt & pepper shakers
-A FUCKING BATHROOM.

[meta][qol]

capture

:cl:
 * rscadd: Metaclub's gulag has been expanded to allow prisonners access to a dining room with associated ustensils, salt & pepper shakers, a grinder, a cow and an actual bathroom.

### CODE REVIEW

**Comment by DrSnips** [comment]
It doesn't seem like map diff bot is working well. Post pics?

**Comment by Irradiation** [comment]
b

**Comment by Durgen** [comment]
Should be a named cow tbh

**Comment by Kurfursten** [comment]
Please resolve map conflicts, you can contact me for a speedy merge at that time

**Pull request closed without merging**
