### PR TITLE
new medhud icon for "dead but revivable" people

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
Capture
adds a medhud icon(animated) for dead people who haven't ghosted out
icon

## Why it's good
easier to prioritise patients, so you don't spend 2 minutes healing a guy who won't defib

## Changelog
 * rscadd: new medhud icon for revivable corpses
 * imageadd: new medhud icon

### CODE REVIEW

**Comment by adacovsk** [comment]
how about green background skull and red background skull

**Comment by Dacendeth** [comment]
So wait, the normal icon appears if they're ghosted out but still playing? This is a nice idea but I feel like im going to have to wait in my body now to get medbay to pay attention to me.

**Comment by pedr69** [comment]
>This is a nice idea but I feel like im going to have to wait in my body now

oh nono nonononono how will i get my ghost knowledge metainfo now?

**Comment by Dacendeth** [comment]
The health analyzer has a way to tell ghosted and still in the round why cant they just be used here as well?

**Comment by djkramer123** [comment]
Would be nice if it showed while people were ghosted, or if there were a different icon for that.

**Comment by wotisjanitor** [comment]
I agree with dj here, that would be very good

**Comment by gurfan** [comment]
Nobody sits around in their body when they die, this needs to appear when they're a ghost yet still revivable.
No need to make a new icon.

**Comment by pedr69** [comment]
this is meant to prioritise medbay patients, see who to defib first
if niggas are still there just not in their bodies it's sorta useless, there's no guarantee they'll come back
unless we force them to, like borgs getting revived - they don't get bwoinked but forcibly moved inside the now functional robot

**Comment by pedr69** [comment]
i have no idea why the ghost medhud is so different - it shows monkeymen while the normal hud doesn't, and this PR doesn't seem to work on the ghosthud
tried adding to human/life/handle_hud_list.dm, which is the only other situation the "huddead" gets set but that seems to do nothing

**Pull request merged**
