### PR TITLE
Judge role 2: standalone job edition

### PR DESCRIPTION
**Pull request by tinysaturn**
[content]
[fluff]
While playing through one of the Ace Attorney games, I remembered there was an attempt at implementing a dedicated Judge role in the form of an IAA  alt-title.
https://github.com/vgstation-coders/vgstation13/pull/30189
It was somewhat negatively received PR, aside from the slapfight in the PR's comments, it just tacked on an alt-title onto the  IAA and that was sort of it.
## What this does

This PR adds a new station judge job

JUDGE FACTS

- is implanted
- spawns in the courtroom
- spawns with judge swag
- has access to the courtroom, brig doors (the part of the brig that most maps' courtrooms connect to) and bridge
- banned from castle
## Why it's good

Hopefully with the presence of a dedicated space law judge the crew will pursue more civil lawsuits and court cases.
I think the judge will also be a more neutral arbitrator compared to the usual HoS/secoff judge or judgeclown
## Changelog

:cl:
 * rscadd: Adds new Judge job

### CODE REVIEW

**Comment by Pastamadness** [comment]
People created drama over an alt job title? 
What the fuck

**Comment by Hinaichigo** [comment]
You probably wouldn't know in advance that a court case was going to occur when you join and select your job. It's sort of the same with lawyer but judge has an even narrower purview.

**Comment by Anton-Kr** [comment]
Honestly hate the idea. Its rarely used and having a random crew member play judge is half the fun of trials

**Comment by Eneocho** [comment]
I doubt implementing magistrates like paradise has would work, considering the balidhunting nature of our sec staff and the fact that anyone that impedes the (((fun))) of horizontaling spessmen tends to get beheaded because "he surely was a tator".

**Comment by WindowsErrors** [comment]
> Thanks for the detailed info. I do kind of like the idea of there being some form of mediator between suspected antags and assistants, and sec.

the mediator is what's on my belt
image

**Comment by Eneocho** [comment]
We need a spess edit of that pic.

**Comment by west3436** [comment]
Why don't you just add some Communications Console feature which will pick a random crewmember and send over the proper gear for them as needed instead of making a new role? Trials happen like once a month

**Comment by kilozombie** [comment]
From my experience, Warden kinda acts like a very insecure version of the Magistrate. You throw your cock all over the place and pretending you have authority when you don't actually command anyone. It's really fun

**Comment by Optimism333** [comment]
> From my experience, Warden kinda acts like a very insecure version of the Magistrate. You throw your cock all over the place and pretend you have authority when you don't actually command anyone. It's really fun

I think IAA is more comparable, in that the amount of authority you have is quite dependent on what clout you can get from Centcomm and by convincing Heads of Staff to listen to you through roleplay. And they are also an impartial investigator, completely divorced from any departmental bias since they don't belong to any station-side department. The Warden is a member of security and does actually have the authority to command secoffs in the brig, as well as acting as being directly responsible for the welfare of prisoners in the brig. Not really a neutral role or one without any command authority.

As for the role of Judge itself... yeah. I pretty much agree with what was said. It would inherit very similar issues as IAA in terms of being able to get anything done as a neutral investigator. As IAA you have no real tools to force compliance with your investigations, especially when you check the tab and see Admins Online: (0). And if the subject of your investigation is security or command, there's nothing to stop a secoff or Head of Staff from just tasing you and chucking you down disposals.

A judge role would come with the problems that IAA has with enforcing any baseline of authority and also have the issue of only having duties to carry out in extremely rare circumstances. I certainly can't see a reality where security gives a damn about getting a warrant signed by the Judge, which is one of the only things I could think that they could be responsible for outside of trials.

**Comment by Kurfursten** [comment]
Lacks support

**Pull request closed without merging**
