### PR TITLE
Map update PR

### LINKED ISSUE #12771: ai on box can be killed by his own turrets
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue 
if the turrets aim at a dude breaking from captains office the 2 turrets on the left will shoot the ai istead

>What you expected to happen
ai not dying from  his own turrets

>What actually happened

ai got damage from the turret
>Steps to reproduce if possible

break a wall from captains and be the laser turret target and look how the ai dies from lasers

### LINKED ISSUE #13665: RD access is shit
(WEB REPORT BY: pvak REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
rd doesnt have access to things like the tech storage, eva and ai modules windoor

>What you expected to happen
have access to shit that rd is supposed to have

>What actually happened
no access

>Steps to reproduce if possible
be rd

### LINKED ISSUE #13667: replace arrivals shuttles lack of computers with Fluff Compooters

### PR DESCRIPTION
**Pull request by CptWad**
Large-scale map updates long overdue
Ill do a separate one for deff later. 

Largest changes:
Holodeck cameras added for all but deff. I had to use a weird wonky method to get it to work but this SHOULD do it without breaking immershuns or cameras. The camera is actually placed in the wall next to its placement allowing vision inside the holodeck without vision elsewhere. Shitty but until someone can code cameras that don't delete if the holodeck changes then it can be undone
image
in refrence to #13968 

AI core on box can be shot by its own turrets no longer! All other maps have this format of walls around the AI to prevent this, why box has been ignored is a mystery
image
fixes #12771

Bugfixes/tweaks:
fixes #13667, #13964, #14702, #14411, #14267, #13586, #13327, #11162, #15438, #14475, #15443
fixes(excluding deff) #14205, #13783, #14003, #14984, 

image

Shit that isnt map issues and should be closed
closes #13665

:cl: 
 * bugfix: Bugfixes across tgstation and metaclub
 * experimental: AI's should now be able to see inside the Holodeck.
 * tweak: AI core on tgstation has been altered slightly. It should no longer be possible to kill the AI with its own turrets now, without help of course. 
 * bugfix: Fixes mining generation entering the vox outpost on box.

### CODE REVIEW

**Comment by CptWad** [comment]
shit how do I do and operators on the fixes #1 #2 #3 etc?

**Comment by ihadtoregisterforthis** [comment]
Fixes #1, fixes #2, fixes #3 

>The following keywords, followed by an issue number, will close the issue:
close
closes
closed
fix
fixes
fixed
resolve
resolves
resolved

**Comment by Intigracy** [comment]
I dislike the botany backroom being the only thing you see, it's better to be able to tell at a glance what they're growing.

That and you're removing a kill spot by making so many windows between the two.

**Comment by SarahJohnson489** [comment]
Put a sink on the left and right of each harvest row in the trays. One of the things that really bungles your botanical bum is the water trips with your buckets after the tanks are out.

As a just in case, can you do a test run as AI just to make sure the camera coverage is good?

I'm not really familiar with the wall flasher's field of view(?) determination but it's still covering well from there?

Not a big enough deal to stop it but it's a bummer to lose being able to IED/grenade the glass then the APC from the side

On the deff AI core, If you position right, I forget what tile, along the left wall the top right turret will cornershoot the AI

**Comment by CptWad** [comment]
>I dislike the botany backroom being the only thing you see, it's better to be able to tell at a glance what they're growing.
That and you're removing a kill spot by making so many windows between the two.

that's the idea
what?


OK

don't need to i've memorized camera coverage its good. 7 tiles away from the camera. Might add a second though 

small area flash, in its position it gets less coverage but thats just the nature of having so much crammed into such a spot. Generally you can still flash people in front of you where as before you could hit people up and to the right of you a little

I mean it removes some of the versatility that the original design has but ultimately its more defensible and the added bonus of not accidentally killing yourself

thanks for the info

**Comment by Unknown-as-Captain** [comment]
Flip botany backroom and botany frontroom

The fridge isn't even next to the trays

Also less chance of bee escapes

**Comment by CptWad** [comment]
image

**Comment by Unknown-as-Captain** [comment]
If you take a closer look, there's SOMETHING wrong with the placement of the fridge and that windoor

**Comment by CptWad** [comment]
I noticed and moved things around

**Comment by Unknown-as-Captain** [comment]
Better but really put the backroom at the back

**Comment by CptWad** [comment]
Would that honestly be a deal breaker? There's far more benefit to having the growing in the back over the front
You can grow your shit without onlookers deciding they care and if theres a plasma plant guess how much easier it is to contain
Less visibility allows antagonists to do as they will back there with very little prying eyes and the now frontroom can be used to more properly store shit or deal with people in

**Comment by Unknown-as-Captain** [comment]
More easily contained kudzu is a bad thing if you ask me

The front room looks so sterile and lame to have it  as the only thing out on the hallway, people like seeing plant shenanigans and seriously if you need privacy for your death kudzu take it to the backroom, never had any issues with that. Hell people largely don't give a fuck even if you do it right next to the window.

Lastly:

that kitchen layout is gross

**Comment by CptWad** [comment]
kitchen layouts always been gross

To me this is mostly A clerical thing. Backrooms up front because it maximizes space for both rooms since the freezer is not aligned with the kitchen. It fit so I thought to try it out

**Comment by Fruktlimpa** [comment]
Give the front room some green color and I'm fine with it. Botany boards up their windows half the time anyways.

**Comment by kilozombie** [comment]
As a massive botany fag, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA yeah I agree with a lot of the criticisms voiced by Unknown-As-Captain. I haven't personally seen any reason to change it, and adding more doors makes growing stuff and exiting just that little bit more annoying. Box Botany is possibly cluttered, but much more convenient and well-structured than this, which genuinely feels like a mess.

As a massive chef fag, AAAAAAAAAAAAAAAAAAAAAA no, Box Kitchen is just fine, leave it as is. In fact, it's one of the least inconvenient, because the shitty Goofkitchen machines are far away from the action.

**Comment by kilozombie** [comment]
Fuck it, ignore my entire post, no more criticism, just a suggestion, hacked together out of images:
boxtany

**Comment by kilozombie** [comment]
EVEN BETTER:
boxtany2

**Comment by Zennyization** [comment]
I dont like that the backroom of botany is now in the front, it just looks wrong. It also removes an area where you could kill people without anybody knowing and I just feel the area 'looked' better with just the trays showing. I'm sure there is a way to keep it as a backroom but just make it smaller while still connecting to maint.

**Comment by kilozombie** [comment]
This is a very relevant concept from Lokiamos which expands Botany in a clever way, while keeping the backroom a backroom:
lokitany

**Comment by yclatious** [comment]
As a ocasional botanist, shit nigger what are you doing putting the backroom in the front, it looks ugly, prevents people from seeing botany and what they are up to and just looks off. Last image Kilo made is honestly amazing, if you want to remake botany, do it like that, aesthetic as fuck.

**Comment by Supermichael777** [comment]
yeah trays don't need a row on each side the pic has more "space". my only complaint is that it has four pointless tables where it could have some of the requirement cramping the backroom and it has 4 inset machines where a pushout and wall would look better. 
thou >not annexing the library

**Comment by Kokuten** [comment]
Why not just take space from the library?

**Comment by Lokiamis** [comment]
The library is one of the most important rooms on the station is why

**Comment by Unknown-as-Captain** [comment]
Reabsorb some of the cancerous north maint tumor

**Comment by Unknown-as-Captain** [comment]
Also this is why you make a atomic PRs

**Comment by kilozombie** [comment]
Also in that picture from Lokiamis definitely remove the water tank.
And do something else with that table space. Maybe just remove a couple.

**Comment by Blithering** [comment]
A possible solution to the holodeck problem would be putting xray cameras outside

**Comment by Kurfursten** [comment]
Just going to put in with the others who say this current botany proposal is unsatisfactory. Many of the same reasons - no room with privacy for antag stuffs, two doors to get to the main hall, putting xenobot up front and the biogenerator all the way in the back. I actually liked having the two-airlocks separating me from maint, too, it's added security. Remember that botanists do not have maint access so we almost never use that door.

**Comment by CptWad** [comment]
alright 
👍 to change botany
👎 to do nothing
😕 if you dont care

**Comment by yclatious** [comment]
I just want kilos last pic botany, so if the 👍  is for that, then sure, 👍

**Comment by CptWad** [comment]
t'is

**Comment by kilozombie** [comment]
:+1: if you can just improve Lokiamis' layout in terms of tablespace and moving some stuff into the main room.

**Comment by CptWad** [comment]
not too hard. 

In other news ill be pushing an update to unchange botany since my changes were evil apparently.
Alongside are some quick changes to remove a potential way to get onto central command 

I was also wondering if the shuttle should have cameras, and if it did should they be full coverage or not?

**Comment by CptWad** [comment]
actually ill make a seperate pr later for botany changes and have this be primarily bugfix oriented

**Comment by CptWad** [comment]
>map compiler didnt run

woops

**Comment by CptWad** [comment]
scratch that I ran the map compiler in the wrong repo

**Comment by DrSnips** [comment]
The AI cores that have those walls on the side make it impossible to get out of if you walk in with a new AI core. Replacing them with shutters or blastdoors would be ok. Also I dont think the main AI core camera on meta is xray like most other AI cores have, this is incase the shutters are closed while still letting you see inside the center part.

**Comment by DeityLink** [comment]
No pls don't remove my botany backroom!

It's such a comfy place where to start a cult.

**Comment by CptWad** [comment]
and THAT should be it. Merge whenever

**Comment by CptWad** [comment]
@gbasood help my bugs didn't close

**Pull request merged**
