### PR TITLE
Adds desc text to Donutgiver

### PR DESCRIPTION
**Pull request by yclatious**
Because I got bloody bored of people not knowing what in the dickens it did or rather, how to fucking use it once it laid upon their bare bald domes. Hopefully this helps atleast a little.

:cl:
 * rscadd: Altered the desc of Donutgiver to say all four commands for its usage.

### CODE REVIEW

**Comment by Kurfursten** [comment]
There are 4 voice commands, just like the Lawgiver. Just like the Lawgiver the words are not in the desc, but they are on the wiki.

**Comment by yclatious** [comment]
Well thats still a buncha baloney and Im adding the rest of the words then.

**Comment by brndd** [comment]
make it say the words are etched on the inside so I can stop imagining a Vietnam war helmet with SPRINKLE and JELLY written on it in big chalk letters.

**Comment by Kitfox88** [comment]
add words to the lawgiver's description too

**Comment by yclatious** [comment]
Honstly brndd, that was half of the reason I wanted to change the desc. The mental picture of a space nam sec soldier with BORN TO SPRINKLES in his helmet is just too good to pass up.

And I will Kitfox, soon as I find the blasted file for it.

**Comment by yclatious** [comment]
Something something [22840]

**Comment by Kurfursten** [comment]
lawgiver.dm

**Pull request merged**
