### PR TITLE
Various misc mapping changes to Boxstation

### LINKED ISSUE #34994: box shitmappers
[box][boxstation]
image

### PR DESCRIPTION
**Pull request by Irradiation**
Fixes #34994

c1

c2

c3

c4

:cl:
 * tweak: Boxstation: Actually finished the air supply piping in maintenance east of the Ghetto Bar.
 * tweak: Boxstation: Moved the light switch in atmos from under the APC to the wall south of the tables by the entrance.
 * tweak: Boxstation: Moved the light switch in the Burn Chamber room in Engineering to be right next to the double airlocks.
 * tweak: Boxstation: Removed a redundant station intercom in the TEG room in Engineering.
 * tweak: Boxstation: Nudged an intercom south at the entrance of Tcomms so it doesn't overlap with the turret control panel.
 * tweak: Boxstation: Moved the light switch in the atmos control room to be over a computer (instead of having to open a locker in order to be able to toggle it).

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Would you mind taking a look at the box kitchen please? The table with the soap and nutriment snack bar is also inaccessible unless you move the locker.

**Comment by Eneocho** [comment]
> Would you mind taking a look at the box kitchen please? The table with the soap and nutriment snack bar is also inaccessible unless you move the locker.

This post was written by Dessert, the kitchen mouse. I see your attempt at trying to eat the Nutriment snack bar.

**Comment by Irradiation** [comment]
I'm not touching Box's kitchen because Dessert is NOT touching the snack bar.

**Comment by SonixApache** [comment]
change :cl: to format `xx: BoxStation: changes made`

**Comment by Irradiation** [comment]
Done.

**Pull request merged**
