### PR TITLE
Supply Consoles no longer require cargo access to use 2: SOLDERING EDITION.

### PR DESCRIPTION
**Pull request by Irradiation**
See #22008
As per comments made in the last PR which was made in badwrongevilsatan web editor, soldering the cargo supply console (the one inside the cargo office, not the one in the hallway) will now remove the cargo access required to approve/deny/call the supply shuttle/return it/etc.

tl;dr current access code a shit and soldering the board has been deemed an okay compromise for a way to (temporarily) delete the access bottleneck of cargo, featuring 1 dead miner and the spare being hidden somewhere.

[controversial][balance]

:cl:
 * tweak: Soldering the Cargo Supply Console board will remove the access requirement to approve/deny orders and to call/return the supply shuttle.

### CODE REVIEW

**Comment by bathosbathtime** [comment]
hackerman strikes again

**Comment by Kitfox88** [comment]
greytide buff and furthermore,

**Comment by SonixApache** [comment]
Did you test if the access reqs come back when you unsolder the board and such?

**Comment by Irradiation** [comment]
I used an assistant ID and when I unsoldered the board, I was once 
access cucked.

**Comment by SonixApache** [comment]
And of course you also checked if the cargo IDs still worked after that.

**Comment by Irradiation** [comment]
Cargo ID still functions after unsoldering and anybody else gets cucked, yes.

**Comment by Kurfursten** [comment]
I think you should add a line in the GUI that tells you if it has been hacked, that way it is more obvious when you show up late than combing the list for a specific item.

**Comment by Irradiation** [comment]
I agree, but I think that could be thrown into a separate PR or something.

**Comment by Kurfursten** [comment]
I don't really think it's necessary in this case to split it into two PRs since before now since including feedback for the hacking action is important. If you insist though link it here and assuming it doesn't get a ton of downvotes I'll merge them both at the same time.

**Comment by Irradiation** [comment]
You do get some feedback from hacking. Well, "you connect/unconnect the mysterious fuse" is a bit dubious to be fair.

**Comment by Kurfursten** [comment]
That's fine, it just needs to be identifiable to someone who latejoins that the console is hacked in a user friendly way. You can add this anywhere in the GUI. If it were me, I might put it in red font near the permissions button where you currently are able to turn on/off access requirements if you know the PIN.

**Comment by SonixApache** [comment]
There's already user feedback in the form of the contraband crates suddenly showing up for selection.
Should just leave it at that and move on.

**Comment by Kurfursten** [comment]
It's one line of code to make the GUI display a message when it's hacked, or even just change the sprite of the computer, I'm not picky.

I think the obvious place to have a message would be by the QM "set access" button since access wouldn't matter if hacked.

**Comment by Irradiation** [comment]
I can't into GUI code, could you point where I'd have to modify the thing to say "hey nerd it's hacked"?

**Comment by Kurfursten** [comment]
At L531 create a new data entry to contain information about whether it has been hacked, e.g.:

`data["hacked"] = can_order_contraband`

Then in supply_console.tmpl, at L15 you should see the permissions button. You could add something like this right after it:

```{{if data.hacked}}}
   <span class='bad'>ACCESS OVERRIDDEN</span>```

**Comment by PaulRitter** [comment]
finish your pr reee

**Pull request closed without merging**
