### PR TITLE
Bagelstation fixes

### LINKED ISSUE #14870: extra airlock?
(WEB REPORT BY: sandysand REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

>General description of the issue
there seems to be an extra airlock in science outpost near the conveyor belts

>What you expected to happen

one
>What actually happened

there's a deconstructed one on the floor
>Steps to reproduce if possible

merge bagel

### LINKED ISSUE #14874: Bagel gulag issues/requests
The Bagel perma gulag is neat, but I think it needs a second warden slot so there's one to watch over it and one to watch over the station prisoners.
I also personally reckon the mining area should have air, but be cold so there's an excuse to have the sec and prisoner coats there instead of hardsuits.
In actual issue news however, the air injector near the north basketball hoop kills you if you stand on it too long, 10 seconds was enough to pass out and break a foot.
And the escape pod's two north corners bug out in transit, see the screenshot for details.
bagshuttle

### LINKED ISSUE #14878: Bagel: Solars initial setup problems.
(WEB REPORT BY: uristmcstouthorn REMOTE: 172.93.109.202:7777)
>Revision 
f2cea69adc0cb5e92550f5a17de3d16ddd6bb84c

>General description of the issue
Setting up solars (as I've done on boxstation a bajillion times) and they refuse to actually turn once set up.  Auto-tracking, manual tracking, even manual manually clicking the -/+ and the cosole says it's turned, the picture on the monitor says turned, but the solars don't actually turn.

>What you expected to happen
Solars, tracking the light as they should, and turning toward it, to produce power.

>What actually happened
The solars don't turn toward the light, nor anything else for that matter.

>Steps to reproduce if possible
Head out of maint, to the southwest (I'm assuming UP from player orientation is North) solar array and try to set them up.

### LINKED ISSUE #14881: Bagel holodeck
(WEB REPORT BY: codenameb REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
194a6f92635fe0b68e590fe8fbb622e0b5dc61b2

>General description of the issue
The doors on either side of the holodeck are in a bad position, resulting in the doors being blocked off in the "maze" and "zoo" settings.

>What you expected to happen
The doors to be in the same position they are on Box

>What actually happened
The doors on the right side on setting "maze" are blocked. All four doors on the "zoo" setting are blocked and it is impossible to enter.

>Steps to reproduce if possible
Go to the holodeck on Bagelstation and press "zoo"

### LINKED ISSUE #14883: Bagel: Atmos Distro off by default
#### Description of issue
Bagel distribution atmospherics is off by default, unsure if intended to be this way by map design. From memory I can recall that the gas mixer for oxygen and nitrogen is off, as well as several digital valves connecting the air supply to distro. This would explain a lot of air problems I have noticed when the map was chosen previously.

#### Difference between expected and actual behavior
Expected distribution air to be at least on, like other maps. Please ignore this issue if this is part of the map design.

### LINKED ISSUE #14884: Bagel Cargo (primarily belts)
The loading/unloading belts in cargo both load off the shuttle, instead of one loading on, and the other loading off like on every other map. I assume this is unintentional.

While I'm at it, and because I have no idea where else to put them beyond getting them lost in thread, I might as well mention a couple of minor problems with the cargo. The lack of a monitor displaying shuttle status is kind of a pain; the delivery chute leading to the mail section runs around the whole loop of the station before dropoff, making it rather pointless when the mail room door is a whole two tiles away; and shutters on the cargo ship but none stationside is pretty useless. Those are all minor gripes though.

### LINKED ISSUE #14885: Bagel: Bar Unpowered
There is a missing wire under the bar backroom airlock, so the bar APC can't charge

### LINKED ISSUE #14886: Bagel: Medbay shuttle defib and medbay airlock access
Doctors don't have access to the medbay treatment center, so they can't leave their spawn area.

Also, the shuttle medbay has a defib recharger but no defib.

### LINKED ISSUE #14899: Bagelstation missing a Scrubber
Despite having a manifold here (I forget where this is on the map), it has no accompanying scrubber.
scrnshot1

There's also a vent laid over a scrubber line somewhere in engineering, which is going to trigger someone fierce when they find it.

### LINKED ISSUE #14907: bagel RCD in eva and camera name
mourge

Camera name for morgue is misspelled.

rcd

The RCD in bagel EVA doesnt work. Doesnt allow for deconstruction or construction.

### LINKED ISSUE #14908: [BAGEL] AI High-Risk module Module Storage has no camera
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

71a6e4dc152a7c5825cdb0f9a5a5cab175e524c6 

>General description of the issue

There's no damn camera in the room, it's a dark space.

### LINKED ISSUE #14910: [BAGEL] Hydrophonics does not appear to have a light switch
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

71a6e4dc152a7c5825cdb0f9a5a5cab175e524c6

### LINKED ISSUE #14911: [BAGEL] HoP office doesn't have a PDA Painter
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

71a6e4dc152a7c5825cdb0f9a5a5cab175e524c6

### LINKED ISSUE #14912: [BAGEL] Hydrophonics puddle describes itself as sink
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

71a6e4dc152a7c5825cdb0f9a5a5cab175e524c6 

>General description of the issue

https://puu.sh/vUqGR/7cec949b29.png

### LINKED ISSUE #14913: [BAGEL] Secure Armory has combat shotguns instead of (riot) shotguns
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

71a6e4dc152a7c5825cdb0f9a5a5cab175e524c6 

>General description of the issue

why would you do this

### LINKED ISSUE #14914: [BAGEL] Not enough holopads in the brig
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

71a6e4dc152a7c5825cdb0f9a5a5cab175e524c6 

>General description of the issue

There's not enough holopads in the brig. I could find a grand total of zero.
Lobby, HoS office, Warden's office, security office and brig medbay  would be good places for them. Warden's office especially.

### PR DESCRIPTION
**Pull request by CptWad**
fixes #14914
fixes #14911
fixes #14913
fixes #14910
fixes #14908
fixes #14907
fixes #14899
fixes #14886
fixes #14883
fixes #14878
fixes #14885
fixes #14881
fixes #14870
fixes #14912
fixes #14884
fixes #14874
New SOFTsuits for prisoners on gulag. Currently use orange syndie suit sprites since I have no sprite talent and someone who does and wants to make one can easily change it.

:cl:
- bugfix: Various bugfixes on Bagelstation
- rscadd: Added new Prisoner Space suits that have terrible protection and are orange.
- rscadd: Gave puddles a description since they were lacking such before.
- experimental: Vox traders now have no ion pistols and secvendor but now have a pimped out medbay good for experimenting on catbeasts

### CODE REVIEW

**Comment by CptWad** [comment]
hold on dont merge it quite yet I forgot something

**Comment by CptWad** [comment]
ok now its ready

**Comment by Kurfursten** [comment]
The content change to the outpost is weird since now they enjoy all the perks of both the Box outpost (big botany, xenobotany, bees, good kitchen) AND Meta outpost (chem dispenser, DNA splicers)

**Comment by SonixApache** [comment]
good idea on the ion pistols, what a mistake that was

**Pull request merged**
