### PR TITLE
Ghetto spacesuit helmets now have flashbang protection (again?)

### PR DESCRIPTION
**Pull request by Irradiation**
<s>
According to pic related and the word of older players, ghetto spacesuit helmets once protected you from bangers, but sanity fucked it all up and they got dropped to</s> 
EDIT: they always had 0 eye_protection, which is imperative in order to not get megafucked by a flashbang (even if you have ear protection). While flashbangs are the main problem (Huge-ass range that IGNORES WALLS & 1 second fuse time), the current statu quo is that unless you've got a hardsuit (and softsuit?) helmet or a security helmet, get fucked because you're going to eat the (nigh) full force of the banger. 

Thus, I propose this change so basically anyone that doesn't get a free gibs as part of their job can have an amount of protection against bangerbois (Read: greyshits, cultists, revs, etc).

Also Shifty said something about maybe looking into making it so flashbangs can't work through walls, so that's a thought for the future.

:cl:
 * tweak: Ghetto spacesuit helmets now grant eye (flashbang) protection.

### CODE REVIEW

**Comment by SonixApache** [comment]
>Firefighter helmet and a gasmask
>eyeprot

wear sunglasses or get a real helmet

**Comment by jknpj** [comment]
I may be wrong since #19224 was about blindness and deafness

**Comment by DamianX** [comment]
Voxperson is right, it used to give ear protection only.

**Comment by iFlashYou** [comment]
It's simple, we just remove flashbangs

**Comment by ShiftyRail** [comment]
@Irradiation I've looked into the issue of it ignoring walls, and apparently, it doesn't on my machine
If you're in "view" of the banger, you get the stun. If you're completely separated by walls, then you don't get it.

There probably was an open airlock that you didn't noticed.

I'm indifferent to the PR itself ; I think that the flashbang usage has severely decreased now that the stun after 3 tiles has gone from 14 seconds to 4 seconds.

**Comment by NigglyWiggly** [comment]
Why is the ghetto suit even a rig 
Why would it protect your eyes at all

**Comment by jknpj** [comment]
If you're hell-bent into keeping this open ping me on the discord or irc or whatever, closing it for now.

**Pull request closed without merging**
