### PR TITLE
Lets Captain/HoP/HoS/Warden hats and more be washed without upgrading

### LINKED ISSUE #25896: HoPs hat does not fit in the washing machine
(WEB REPORT BY: jameswbigmac REMOTE: 206.221.180.138:7777)
# Revision
8ff8703263072dc377ce53cda5fe0abadf98566c

# Description
HoPs hat does not fit in the washing machine
# Steps to Reproduce
Attempt to put the hat in the washing machine.
# What you Expected
A washed, plasma free hat
# What Actually Happened
Dirty hat

### PR DESCRIPTION
**Pull request by RaccoonBro**
[tweak]
fixes #25896

Because the Captain's, HoP's, HoS's, and Warden's caps are all considered helmets, they couldn't be washed without upgrading the machine to second tier matter bins, and who even does that. This doesn't let space helmets and stuff be washed.

The entire helmet and helmet/tactical sections need to be re-done at some point honestly, it's a bit of a mess. This PR has the side effect of letting tactical and swat helmets washed, which shouldn't be that big an issue. Fixing it would be changing basically every map and that sounds like a bother.

:cl:
 * tweak: You can now wash the Captain/HoS/HoP/Warden caps in washing machines without upgrading them.

### CODE REVIEW

**Comment by Kurfursten** [comment]
I don't think this is the right approach, it has weird results like you can wash all combat helmets and even construction helmets now. Maybe a whitelist for exceptions.

**Comment by RaccoonBro** [comment]
As far as I'm aware, construction helmets have always been allowed in washing machines (they're head/hardhat/, not head/helmet/).

As for the other stuff, I'll mess with the washing machine's whitelist to see if I can get a decent setup going. Why the various caps weren't just added to head/jobs.dm is a mystery.

**Comment by RaccoonBro** [comment]
That was easier than I thought it'd be.

This doesn't fuck with the inheritance any that I can tell, and it feels better for head caps to be in jobs.dm instead of sprawled over three files.

**Comment by Kurfursten** [comment]
Nice. You made sure nothing important was being inherited and there's nothing else in the game that worries about helmets right?

I know building e_chairs looks for helmets but frankly you should not build an electric chair with a hopcap

**Comment by RaccoonBro** [comment]
Nothing should be inherited that isn't that I can tell, and I can't imagine anything that would need to specifically look for helmets and make sense to use a hopcap or whatnot. Like you said it'll stop working with shock_kits, but that isn't a great loss.

**Comment by ShiftyRail** [comment]
This probably removes the ability to attach tac lights to the HoS cap, and removes flashbang protection too from HoP/HoS caps.

**Comment by Kurfursten** [comment]
Taclights can attach to any /obj/item/clothing/head
You are correct though, you need to be a /helmet/ to get +1 ear safety from bangers

**Comment by RaccoonBro** [comment]
Taclights aren't affected, but it doesnt cover the ears. I'll fix in the morning

**Comment by RaccoonBro** [comment]
Alrighty, that's all good to go. It only applies to the HoS/Warden caps unless there's some reason the Captain or HoP need to be shielded too

**Pull request merged**
