### PR TITLE
Increase suffocation damage for blacks

### PR DESCRIPTION
**Pull request by s-h-d**
This PR modifies the oxygen loss of black humans to be 5% greater. Non-blacks should not be affected.

[<controversial>]
:cl:
 * tweak: Black humans receive 5% more suffocation damage

### CODE REVIEW

**Comment by aceedex** [comment]
Merge this man!

**Comment by aceedex** [comment]
This is why we must kill the eternal collab

**Comment by s-h-d** [comment]
I can't breathe

**Comment by ComradeDispenser** [comment]
>closed
Cowards.

**Comment by gurfan** [comment]
hero

**Pull request closed without merging**
