### PR TITLE
All types of clothing items may now have SLOWDOWN

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Nothing uses this yet, so no changelog. But in the future we could have a very heavy belt that slows you down when worn for example. Or a jet belt that speeds you up or something

### CODE REVIEW

**Comment by Kurfursten** [comment]
>get_clothing_items()

Legcuff slowdown wasn't being applied before? This might have significant applications

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Legcuffs don't have slowdown, not sure what weird-ass slowdown method they use

**Comment by bathosbathtime** [comment]
Don't they force walking

**Comment by Dacendeth** [comment]
yeah they force walking.

**Comment by Irradiation** [comment]
How about making it so security knives can make you go even FASTER?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Why are people hearting this shit it doesn't even do anything yet

**Comment by jknpj** [comment]
:thinking: hmm

**Pull request merged**
