### PR TITLE
Wizard: Staff of Polymorph and Pollywogs

### PR DESCRIPTION
**Pull request by tinysaturn**
**---------------------ORIGINAL PR POST-----------------------------------**
https://github.com/vgstation-coders/vgstation13/pull/21570

Considering how easy it is to turbo'gunk' a station using the staff of change, I've opted to make an alternate that's 'just as fun' but not as round destroying as setting the staff of change to 'xeno'.

    Wand of Polymorph
        Two settings: Minor and Major. Minor turns the afflicted into a harmless simple animal for a short time, Major turns the afflicted into a somewhat more dangerous animal for a longer period of time
        Trying to shoot yourself with the wand of polymorph turns you into a...

    Pollywog
        A strange mass of alchemical inconsistency, that transmogrifies every so often into something else.

🆑

    rscadd Adds the Staff of Polymorph, available via wizard spellbooks
    rscdel: Removes the staff of change from the wizard spellbooks
--------------------------**END OF RINE**------------------------------------

Original PR intended to replace the beloved Staff of Change with the mildly annoying Staff of Polymorph.
This PR adds pollywogs and adds the Staff of Polymorph to the spellbook, priced at 20 spell points while keeping SoC.

Additionally, it gives the Staff of Polymorph a unique (and lazy) sprite and blacklists pollywogs from amorphous mask mob pool and the menagerie artifact effect.

[content]
[tested]
:cl:
 * rscadd: Adds Staff of Polymorph to the spellbook, Adds new mob: Pollywog

### CODE REVIEW

**Comment by angryturnip** [comment]
I'm glad it's not replacing the staff of change. While yes, the original creates gunk, that's kind of the point. That's your main gimmick item for your wizard build. The polymorph wand sounds like a good utility buy for evading crew.

**Comment by Eneocho** [comment]
I'll pay you half a pomfcoin if you also make a staff of poly-morph that turns anyone into poly. And maybe a "Poly"-wog that looks like a deformed parrot.

**Comment by Eneocho** [comment]
polywog
This is how a pollywog would look like by the way.

**Comment by tinysaturn** [comment]
> I'll pay you half a pomfcoin if you also make a staff of poly-morph that turns anyone into poly. And maybe a "Poly"-wog that looks like a deformed parrot.

There's already a spell in the game called "Poly-morph" that turns the victim into an invincible Poly for two minutes. You get it the same way you get EI NATH, from a book of forgotten knowledge that can spawn in a spellbook bundle.

**Comment by Eneocho** [comment]
I know, that's why I suggested it. Staff of poly-morph, a ranged version of the poly-morph spell, either kept as adminbus or as a 1/50 chance when buying the staff of polymorph.

**Comment by Eneocho** [comment]
The original PR's changelog got merged instead of the actual changelog.

**Pull request merged**
