### PR TITLE
new braindamage line

### PR DESCRIPTION
**Pull request by pedr69**
mommi dance

:cl:
 * rscadd: a new braindamage keeper has been added

### CODE REVIEW

**Comment by ErrorsWindows** [comment]
tasteful, urbane

**Comment by Eneocho** [comment]
kino but it doesn't quite feel braindamagey enough, it could legitimately be misunderstood as a legitimate question
try "wahts a keper"

**Comment by Securitymain** [comment]
thumbsdown by discord neverplayers like s*nix who should not have a single say in prs

**Comment by pedr69** [comment]
i've just had a thought
why don't we have shit like this in a config file
especially catbeast names - if we're adamant on not letting niggermen in the code having them in a config file would let us get around this
unless deity removes it again to pwn the rightoids

**Comment by Eneocho** [comment]
a fair point
also beware as your post might get autojannied by github and all your posts hidden until you do the needful

**Comment by Eneocho** [comment]
i'm saying that it has happened to several people, pedr, better be safe than lose the account, especially after github has proven to be with the finger on the trigger

**Pull request merged**
