### PR TITLE
Removes the anti-tamper device from the Tactical Assault Gear crate.

### LINKED ISSUE #18479: Random acid grenades in security crates
When did this happen, how did this happen, and most importantly, why did this happen?

If cargo is busting open weapon crates, they're violating space law and prone to having their shit pushed in by either Security or RoboCop borgs. It creates drama and interaction between players, and has always been a part of the game. Cargo gets belligerent and arms up, they get raided, that's the way things go.

Discuss.

### PR DESCRIPTION
**Pull request by Irradiation**
Closes #18479

As previously mentioned in the issue, considering that no other cargo crate does this and the fact that Pomf presumably said one time that crates and lockboxes shouldn't be booby-trapped (I don't have a log for that claim, so take it with a grain of salt), I and others believe that cargonians (and other folks) shouldn't have the content of the TACTICOOL ASSAULT GEAR crate get dissolved bya blend of sulphuric acid smoke and capsaicin because they decided to very illegally bust it open for very legitimate reasons.

:cl: 
 * tweak: NT decided to cut their budget allocation for anti-tampering device for the Tactical Assault Gear crate.

### CODE REVIEW

**Comment by Pathid** [comment]
>Pomf presumably said one time that crates and lockboxes shouldn't be booby-trapped 

If you mean this https://github.com/vgstation-coders/vgstation13/pull/11753#issuecomment-252637019 it was more like more an objection to adding more RNG to the game and it was about lockboxes, not crates, so take that with a _big_ grain of salt.

**Comment by Irradiation** [comment]
I'll take it with *two* grains of salt, then.

**Comment by iFlashYou** [comment]
cargo buffs...

**Comment by jknpj** [comment]
cargonia...

**Comment by Irradiation** [comment]
@iFlashYou In order to be fair, I'll remove this PR and make it so every locked crate (and lockbox) will have sulph-acid smoke. Everybody gets it!

**Comment by Aurx** [comment]
Should be pacid and spiritbreaker smoke, you casual.

**Comment by Irradiation** [comment]
@Aurx >pacid and spiritbreaker
What are you, some kind of scrub? It should also include blood that's infected with one of the most annoying symptoms, along with Cryptobiolin and Impedrezene.

**Comment by Aurx** [comment]
ONLY one?

**Comment by Irradiation** [comment]
Sorry, I meant infected with at least _*four*_ viruses each containing the worst symptoms ever devised by the c*ders addled brains.

**Pull request merged**
