### PR TITLE
Nerfs health of all types of Windoor

### PR DESCRIPTION
**Pull request by Irradiation**
Because jesus fuck, for what is essentially just a reinforced window, even the most basic of windoors manages to have 100 HP while a normal reinforced window has 40 HP.

Current window values:
Window = 10 HP
Reinforced window = 40 HP
Plasma window = 120 HP
Reinforced plasma window = 160 HP

Old values:
Normal windoor = 100 HP
Secure/brigdoor (requires inserting plasteel) = 200 HP
Plasma windoor = 300 HP
Secure plasma windoor = 400 HP

New values:
Normal windoor = 60 HP
Secure/brigdoor (requires inserting plasteel) = 100 HP
Plasma windoor = 150 HP
Secure plasma windoor = 200 HP

[balance][qol][tweak]

:cl:
 * tweak: Nerfs health of all types of Windoors by 40-50% depending on type.

### CODE REVIEW

**Comment by Lunstra** [comment]
These motherfuckers literally have 10x the hp of the window they derived from there or thereabout. Fuck windoors.

**Comment by dylanstrategie** [comment]
Windoor health is really fucking gay, yeah. Fuck that noise

**Comment by SonixApache** [comment]
seems fair

**Comment by spoonylove** [comment]
Good shit 👌👌👌👌👌

**Comment by ShiftyRail** [comment]
It was a feature

**Pull request merged**
