### PR TITLE
Makes rollerbeds not shit

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
See changelog
Small problem: Rollerbeds count as dense when locked so sometimes it seems like it doesn't work
dreamseeker_2018-07-20_00-33-11
because technically the rollerbed blocks you

:cl:
 * rscadd: Rollerbeds now auto-unbuckle patients when trying to put them inside Medbay machinery via clickdrag (meaning you don't have to unbuckle them anymore before loading them).
 * rscadd: Rollerbeds now auto-buckle patients when ejecting them from Medbay machinery via clickdrag (meaning the patient comes out already buckled).

### CODE REVIEW

**Comment by DamianX** [comment]
>How would people feel if ejecting people via clickdrag onto a rollerbed also insta-buckled them?

yes please

**Comment by Blithering** [comment]
This and the insta-buckle would make avoiding harmdrag much less of a hassle for parameds and docs in general

**Comment by Exxion** [comment]
People were theorizing that this account was Bauds but that branch title pretty much confirms it

**Comment by Blithering** [comment]
I for one welcome our new meme-named overbauds

**Pull request merged**
