### PR TITLE
Wizard Doppelgangers now have 40 HP.

### PR DESCRIPTION
**Pull request by Irradiation**
I didn't quite die, but it turns out that unstunnable mobs that can almost chainstun people and deal mild damage at the same time, all the while being spammable on a 30/20/10 seconds cooldown is a bit iffy. All that done with a nice 100 HP. These things might be the tankiest, spammable & incosequential pest I've seen in a while.

[balance][tweak][gamemode][role]

:cl:
 * tweak: Wizard Doppelgangers now have 40 HP, down from 100 HP.

### CODE REVIEW

**Comment by DamianX** [comment]
Can you show proof you haven't died?

**Comment by Irradiation** [comment]
I'd have to pull out the logs of me not being on the server for the past 2 rounds, hm.

**Comment by Blithering** [comment]
I would say have them die and do their fake teleport when hit by stuns, that way they actually can be mildly convincing as decoys, rather than combat mobs

**Comment by Caboozles** [comment]
Make it 20/30/40.

**Comment by codeungabunga** [comment]
Are there any sanity checks for amount of clones? What's preventing a wizard from sitting in a room making a clone every 10 seconds until it's filled, then releasing it?

**Comment by Irradiation** [comment]
Supposedly there's a 26 doppel limit.

**Comment by Kitfox88** [comment]
give them 1hp or make them do no damage and stun, they're supposed to be decoys not attack drones

**Comment by Intigracy** [comment]
I don't wanna hamfist smash doppel all at once, if it continues being an issue after the MM removal we can revisit the health later

**Pull request closed without merging**
