### PR TITLE
emaggable clown soundsynth(take 3)

### PR DESCRIPTION
**Pull request by pedr69**
i kneel, but i will not grovel at the feet of the Gestapo

## What this does
adds the discord sound to the emagged sound list(among other less controversial ones)
the bwoink plays on april fools or if a shitmin decides to varedit the thing

## Why it's good
moar sounds for traitor clowns

## Changelog

:cl:
 * rscadd: sound synthesizers can now be emagged

### CODE REVIEW

**Comment by adacovsk** [comment]
Updoot for the discord sound

**Comment by Eneocho** [comment]
>ooc in ic

That's not OOC in IC, this is OOC in IC:

**Comment by pedr69** [comment]
hmmmm, how would i add 1 braindamage every time a player who has discord installed hears the sound in game?

**Comment by Eneocho** [comment]
> hmmmm, how would i add 1 braindamage every time a player who has discord installed hears the sound in game?

Unfathomably based, demonically based even.

**Comment by djkramer123** [comment]
weird hill to die on

**Comment by Pastamadness** [comment]
I am forced to upvote this PR because of its unyielding attitude.

**Comment by ConfusedCactus** [comment]
god just fuckin stop trying to add cringe ooc jokes like this, it's really not as funny as you think it is

**Comment by gurfan** [comment]
VG

**Comment by ShiftyRail** [comment]
Non, no, nein, nej, no, no, nyet. OOC in IC.

**Comment by pedr69** [comment]
one day when the war is over the collab gestapo will pay for the six gorillion closed PR's
one day...

**Comment by Eneocho** [comment]
Now this is just lame. He bent the knee and took the bwoink out. Are you seriously that addicted to shitcord that hearing the sound ingame would trigger a response?

**Comment by Eneocho** [comment]
>one day when the war is over the collab gestapo will pay for the six gorillion closed PR's
one day...

Make PDA messages make the shitcord notification sound when you receive the message. Then it is no longer an OOC sound and they would have no excuse.

**Comment by pedr69** [comment]
>PDA messages

hmmmmmmmmm
how many maps have the PTECH pda cartridge vendors? just roid?

**Comment by Eneocho** [comment]
>how many maps have the PTECH pda cartridge vendors? just roid?

The one in the HoP office? Packed has one, lowfat bagel too, I think synergy and meta have it as well.
Just make it so sending or receiving a pda text makes the shitcord sound, so it's an IC sound.

**Pull request closed without merging**
