### PR TITLE
ablative, bulletproof and antichrist helmets(adminspawn only)

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
adds 2 useful and one gimmick helmet types: ablative(laser resist), bulletproof(bullet resist) and UN blue helmets(like sec helmets but worse)
they're adminspawn only for now, don't want to ruin b*lance and get infinite downvotes
image

now with less shitty sprites!

## Why it's good
moar useful helmets, as opposed to riot helmets, the HOS hats and advanced EOD hoods

## Changelog

:cl:
 * rscadd: ablative, bulletproof and UN helmets
 * imageadd: sprites for ablative, bulletproof and UN helmets

### CODE REVIEW

**Comment by pedr69** [comment]
uh oh why is the hats.dmi smaller than it was at the beginning what did i fuck up

**Comment by Hinaichigo** [comment]
Maybe change the UN letters to something else/something illegible so it's a little less explicit.. just my immulsions taste though.

**Comment by Exxion** [comment]
>uh oh why is the hats.dmi smaller than it was at the beginning what did i fuck up

Nothing IconDiffBot detects, at least. Just happens sometimes. I assume it has to do with PNG's compression algorithm.

>Maybe change the UN letters to something else/something illegible so it's a little less explicit.. just my immulsions taste though.

If you want, but it's an admin-only meme item anyway

**Comment by Kurfursten** [comment]
Keep in mind that ALL non blacklisted clothing can appear in spessmart, cheap too

**Comment by pedr69** [comment]
another thing when testing the resistances, the ablative one seems to only work 75% of the time or so - most hits will do reduced damage, but every once in a while it'll do full damage still
this doesn't seem to happen with the bulletproof one(except when it randomly decides to shoot another limb instead of the head that i'm targeting)

**Comment by Eneocho** [comment]
I HATE THE ANTICHRIST!!!!
Change from UN to NT, so the immulsions stay intact.

**Comment by Anton-Kr** [comment]
Bay might have less fugly sprites for these

**Comment by pedr69** [comment]
oh yeah the sprites were made in half an hour by painting over the riot and stahlhelms
if you have ones that don't look like shit pls post

**Comment by Blithering** [comment]
I have some sprites for bulletproof and ablative helmets, will post when im back at my PC

**Comment by ManopolisJones** [comment]
I don't know bros, ancient UN helmet? Nothing ruining the immulsions for me.

**Comment by Blithering** [comment]
helmetss

**Comment by pedr69** [comment]
you got worn sprites for those too?

**Comment by tuypo1** [comment]
My emulsions don't really have a problem with a UN helmet, it's not that far in the future they would be forgotten

**Comment by Eneocho** [comment]
500 years is a huge timeskip though.

**Comment by Hinaichigo** [comment]
There is Cold War and WWII stuff so I guess that's true.

**Comment by Kurfursten** [comment]
We already have roman armor, it's fine

Not to mention our theatervend... do we really think people will remember Robbie Rotten in 500 years?

**Comment by Blithering** [comment]
> you got worn sprites for those too?

Yes, its all there. You want me to send you the dmi?

**Comment by Kurfursten** [comment]
Icondiff bot shows the worn states, no need

**Comment by Kurfursten** [comment]
Let me know if you can't figure out what's causing the damage resist bug after a couple days; at least try to repro the issue and let me know so we can bugfix it

**Comment by pedr69** [comment]
>damage resist bug

i have no fucking clue what's causing it, but it seems to be when a projectile hits armor(couldnt get it to happen by toolboxing a riotgear man)
it seems to happen more often when you target the head(~20%) vs torso(~1%)
doesn't seem to be caused by get_zone_with_miss_chance(), although the percentages are roughly similar to the chance you hit another limb
i'm now stuck, have no clue how to trace where the bullets(or beams) actually apply damage, other than it's not in projectile.dm
>Icondiff bot shows the worn states, no need

so where do i get the dmi for the nonshit sprites?

**Comment by Kurfursten** [comment]
re: non shit sprites - completely forgot who was PRing this and thought the exchange was in reverse, my bad

re: bug - try inserting debug statements that send an admin_message() in the code for clues that send info about current state of variables; see if this gets us a lead

**Comment by pedr69** [comment]
>insert debug statements

thing is i don't even know where to insert, because i don't know where the damage gets applied
tried searching for on_bullet_act for mobs and carbons but didn't find anything and have no idea where to go from here

**Comment by Kurfursten** [comment]
This isn't really your fault so it's not your obligation to solve it, but I wish we could figure it out. I'll wait on the new sprites to merge and see if I can find anything in the code.

**Comment by Blithering** [comment]
If you're on either of the discords, I've sent the dmi on both.

**Comment by Blithering** [comment]
If not, have a shady link instead. https://file.io/5iP4ieHx00A6

**Comment by pedr69** [comment]
i recommend catbox
image

**Comment by Blithering** [comment]
> i recommend catbox image

https://files.catbox.moe/p3yleh.dmi

**Comment by pedr69** [comment]
thinken of removing the eyeprot but making them mask your mouth since that's how the nusprites look

**Comment by Eneocho** [comment]
> thinken of removing the eyeprot but making them mask your mouth since that's how the nusprites look

The coder cabal nerfing stuff via spritework. Impressive.

**Comment by Kurfursten** [comment]
Let me know some time in the next day if you want to change the stats on them, otherwise this looks fine for merge

**Comment by tuypo1** [comment]
> Obviously. Clowns remember their history and great icons get remembered.

is the united nations not a great icon of buffoonery

**Comment by Eneocho** [comment]
>is the united nations not a great icon of buffoonery

It's not? Either way I was referring to Robbie Rotten. The character was an icon of comedy and the clown culture would remember him, thus explaining why the rotten costume is still a thing 500 years later.

**Comment by pedr69** [comment]
i think the stats are fine? copied them over from the ablative/bulletproof vests
you can survive a 357/lasergun magdump if you get lucky and have the damage resists actually get applied

**Comment by Kurfursten** [comment]
I meant regarding your comment on eyeprot, but you actually did that immediately after the comment

**Pull request merged**
