### PR TITLE
Adds a ghost verb to hide other ghosts without having to toggle darkness

### LINKED ISSUE #9693: Add 'toggle ghosts' button for ghosts
We can do this now more easily because of planes! Woo!

### LINKED ISSUE #13229: Add a ghost option to hide other ghosts without toggling darkness
I think someone said this would be possible with planes

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Tested with two clients and nothing seemed to break catastrophically

Closes #9693
Closes #13229
:cl:
 * rscadd: Added a ghost verb to hide other ghosts without having to toggle darkness.

### CODE REVIEW

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
>No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

wwhy is travis die

**Comment by DamianX** [comment]
Does this work correctly for things that used see_invisible like cultists making ghosts visible?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Yeah it uses ✈

There was the concern that somebody would toggle ghosts when dead, then get revived, then not see cult ghosts forever after that so the ✈ gets reset on every login()

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Don't merge yet, for some reason this makes you unable to admin clickdrag your ghost and only your ghost and I have no idea why

**Comment by Exxion** [comment]
But `PLANE_MASTER`s aren't rendered
If it blocked clicks, that sounds like a BYOND bug

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Just chalk it up to a BYOND bug then

**Comment by Exxion** [comment]
Why didn't MoMMI add [Secret repo conflict.]?

**Pull request merged**
