### PR TITLE
makes discount dan's special sauce a real condiment

### LINKED ISSUE #33241: discount dan sauce packet
[bugfix]
image
why is the discount sauce packet a child of drinks, not condiments

### PR DESCRIPTION
**Pull request by pedr69**
[sprites]
image

## What this does
makes the discount dan packets you can buy from the vendor real condiments, letting you apply them onto food
adds an empty dansauce packet trash item
adds a dansauce condiment bottle, available in the "exotic garnishes" crate
closes #33241

## Why it's good
lets you smear more shit on the chef's food

## Changelog

:cl:
 * tweak: advancements in discount packaging technology allowed Discount Dan to overhaul his Special Sauce packets, letting you apply them to food!
 * rscadd: enthusiasts have heard rumors about Discount Dan expanding into the "exotic garnishes" scene

### CODE REVIEW

**Comment by Eneocho** [comment]
I'll try to make a Dan's Sauce bottle for you.

**Comment by ManopolisJones** [comment]
oh god the green shit, this'll be good

**Comment by Eneocho** [comment]
Here, both as a DMI file and as a png @pedr69.
https://files.catbox.moe/18o5th.dmi
dansauce

**Comment by Eneocho** [comment]
Requesting that you can buy a full condiment bottle on the Discount Dan and Groans Soda hacked or premium tab.

**Comment by jwhitak** [comment]
I was gonna do this but forgot lmao thanks

**Comment by Optimism333** [comment]
Luv the additions to Dan content

**Comment by Eneocho** [comment]
Please man, add the big condiment bottle to the premium tab on the Discount Dan's vendor.

**Comment by pedr69** [comment]
don't wanna add too much dancreep, you have sauce in the danvend already
i think items like this should be added to the maint loot pool and space vaults instead, god knows they need more variety

**Comment by Eneocho** [comment]
It wouldn't really be creep. You already get the small dan sauce packets, sauce in mann's drink, most groans drinks, all dan's food. If nothing else it would be a good way to get condiment bottles as non-cargo non-service.

**Comment by NigglyWiggly** [comment]
l m a o 
this dude fucked up his icon_states what a nerd

**Comment by pedr69** [comment]
how did i fuck it up
i had it compiled and working, as per the OP pic, but fucked up before i uploaded it to github

**Pull request merged**
