### PR TITLE
Removes reagent scanner from Toxins PDA cartridge

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
#### Reasoning for change
I assume this is a leftover from the days where Chemistry was part of Science. Toxin's job hasn't had to do with chemicals for a very long time.
:cl:
 * tweak: Removed reagent scanner from Toxins PDA cartridge.

### CODE REVIEW

**Comment by Irradiation** [comment]
Woah there lad, just because I posted about it on the thread to indicate that R&D is the powergaming department doesn't mean you can do this PR.

Haha, who the fuck am I kidding, any scientist should be able to have access to what only a chemist & CMO gets at roundstart. For science.

**Comment by Irradiation** [comment]
R&D can already build a Mass Spectrometer to check for reagents, so uuh yeah.

**Comment by Exxion** [comment]
Does the mass spectrometer work on non-mobs?

**Comment by Pathid** [comment]
@Exxion Uh, no. I don't think it does. You can manually inject a sample into it, but it will give you an error instead of anything useful.

**Comment by Exxion** [comment]
That's what I thought
So no @Irradiation they can't

**Comment by DeityLink** [comment]
I'm ok with this nerf. But science should be able to craft a tool that reproduces this behavior, just not have it by default. mass spectrometer is designed for reagents that are inside the bloodstream.

Such an item would be useful for Botany as well, as it'd allow them to check on the composition of an apiary's honey without having to grind a comb first. And R&D being more useful to the rest of the station is always good.

**Pull request merged**
