### PR TITLE
pulse demon tweaks

### PR DESCRIPTION
**Pull request by pedr69**
[balance]

## What this does
- reverts the max charge upgrade mechanic added in #33124 - you now get up to 200KW in an SMES, and 5KW per APC sucked(instead of the old "idle inside the SMES while clicking the upgrade button")
- selfsustaining charge is now much cheaper but with a much bigger slowdown
- prevents you from turning off selfsustaining charge when not in a cable - this used to be an instant suicide button
- removes "empower" from most spells, so you can't make them virtually free to cast anymore
- changes the spell unlock and upgrade costs
**new unlock costs**
image

**new upgrade costs**
image

## Why it's good
i ded nerf pulsedemon NOW

## Changelog

:cl:

 * tweak: pulse demons must now suck APC's/SMES to get more power
 * tweak: pulsedemon spell unlock and upgrade costs

### CODE REVIEW

**Comment by Hinaichigo** [comment]
Instead of removing the spell quicken and empower, maybe consider removing the malf explode. It doesn't really fit with the rest of the pulse demon's gameplay I feel like.

**Comment by pedr69** [comment]
making it less spammable is better than removing in my opinion
the upgrades themselves don't add much, apart from time spent waiting in an SMES and clicking "quicken/empower" - i feel there's way too many of them
instead of removal, making the upgrades more expensive might be better - give everything a quicken but with a high unlock cost
and an empower to freemove to let you move faster out of cables, while making it slowdown MUCH more by default(and making it cheaper to unlock the ability itself)


would also like to add the malfhack glow overlay gurfan added but i have no idea how

**Comment by pedr69** [comment]
god damn i hate balance because everyone wants something different
i am considering removing the emag/emp/malf quicken cooldowns

**Comment by Kurfursten** [comment]
I feel a little uncertain about so many tweaks with so few voters, but I guess we'll give it a try.

**Pull request merged**
