### PR TITLE
IV Drips now give/succ 12 units of blood.

### PR DESCRIPTION
**Pull request by Irradiation**
They used to give/succ 4u per tick. This will affect only blood transfers, not chemical transfers, so meme IVs won't get changed by this.

As most people that ever handled an IV drip will attest, IVs are quite slow at transfering blood. Combined with a general lack of blood bags, medbay will prefer to resort to cloning to "fix" a corpse that's low on blood, as refilling the blood takes quite a while. Maybe possibly this will get people to use IV drips more for salvaging otherwise defibbable corpses. Maybe the transfer rate can be upped more, we'll see if people like the new transfer rate.

[tweak][balance]

:cl:
 * tweak: IV Drips now transfer 12 units of blood per tick, previously they transfered 4 units.

### CODE REVIEW

**Comment by Caboozles** [comment]
I’m excited to be able to use IVs as a weapon now.

**Comment by boy2mantwicethefam** [comment]
I'm boy2mantwicethefam, and this is my favorite pull request on /vg/.

**Comment by SirSkeleto** [comment]
I'm against this for two reasons.
Firstly, this won't fix medbay's ability to "fix" a body that has no blood. "100%" blood requires 3 bloodbags to reach, so it will make it faster, but given medbay's roundstart blood supply, this still doesn't help much. In addition to this, types O-, O+, A-, and B- don't even have enough compatible blood types to receive 3 blood bags.
The second reason is simple. If you're using an IV to stabilize someone who's losing blood at a comparable rate, this is going to grossly overcompensate. When a patient has 600 blood, they cannot get any more, and the remaining blood is jettisoned into the aether.

**Comment by Caboozles** [comment]
Who the fuck uses IVs to compensate for someone missing a little blood and some internal bleeding? That’s what iron is for. Blood packs are for dangerous levels of blood loss.

**Comment by brndd** [comment]
>When a patient has 600 blood, they cannot get any more, and the remaining blood is jettisoned into the aether.

Make IV drips stop inserting blood when the patient is full, then.

**Pull request merged**
