### PR TITLE
Reduces overall vending machine prices

### PR DESCRIPTION
**Pull request by yclatious**
Because fuck 60 credit raisins, fuck 50 dollars soda, and fuck the baloney bullshit of wanabee economists in spess that can't be assed to do 3 minutes of work changing numbers to make people be able to afford more than 3 soda poppies or 2 bags of raisins per paycheck.

No changes to Vox or Cargo vending machines. I am retarded, not stupid.

:cl:
 * rscadd: Changed around some prices so this shit isn't worse than the Great Depression.

### CODE REVIEW

**Comment by Kurfursten** [comment]
@Angry Duck#5312 The problem with free food is that it makes the chef irrelevant. I remember the days of free syndie cakes where no one (certainly not me) ever went to the kitchen. Like why would you when there's a vending machine right inside the engie lobby on box?

Vending machines are
>closer
>have 0% chance of having poison in them

Unless there's some cost to using them, there is no point in having a chef at all, they cause players to not congregate in food places, and lower interaction. It would be like it we did away with the emergency shuttle and put pods all over the station. That'd be awful - people don't move into the same space to interact. It's a social game.

>"But Cargo can order pizza!"

That's fine, that's another job doing it's role if so, and it hardly happens every shift unless there isn't a chef - and even if they do, you have to go to the cargo pizza - which is again usually in the bar or at cargo - a location that causes places to congregate. Cargo pizza, too, could be tampered with. It's not sitting in the same spot every shift inside your department or 2 steps out of it for the silent shuffle crew to move toward robotically.

**Comment by 9percents** [comment]
also, 20 credits for gunko cola isn't good, there is a reason it costs 50

**Comment by yclatious** [comment]
The same old argument, the same 50 times, the same thing in order to endlessly justify 60 dollars for raisins, while remaining silly as always.

Buzz off with the Chef excuse. People congregate to the Chef if the Chef is good or the Chef is around. If the food is poisoned, they lynch him then break in to eat Chef Burgers, and even if he is not, they find other sources. The gathering spots won't stop being gathering spots and some decent food in the vending machines that doesn't make our economy a joke won't stop folks from going to the Kitchen for pizza, cake and deep fried donut box salads.

I do not give a singular shit about Cargo. Food is overall a non issue for 99% of the shift and the congregations of likeminded individuals are not compromised due to food in the vendors being cheaper. If someone wants pizza, they will get it from cargo, but raisins being 60 bucks when you people insist on economic systems is, being honest, fucking retarded.

The focus points of interaction in the social game will not be compromised just because shitty food is now more available, we are not in constant hardmode and the kitchen remains one of the biggest focuses of most maps in terms of traffic. It just means the economy you guys so wish to force upon us in the name of "balance" is no longer a joke

So buzz off. Fair point on the gunko soda however, might have gotten a little too overboard.

**Comment by Dacendeth** [comment]
You want some ridiculous prices look at the merch computer, 900 credits I think for a painting when all I want to just decorate my autism fort is too much.

**Comment by bathosbathtime** [comment]
The food in the vending machines is limited by the total amount of food in the machine just as much as it is limited by the price. While the chef can make food nigh infinitely with a half competent botany, cargo would need to restock the vending machines after not too long, which itself is "interaction."
I also believe you are overselling the interaction between the chef and the crew, which is in my experience: people shuffling up, grabbing food, and eating it before leaving without saying a word.
They're are not scheduled meal times where everyone gathers in the mess to grab a bite, there's a hunger timer that players reset so they can get back to actually playing the game.

This is all irrelevant, however, because anyone that even mildly cares about avoiding the chef will hack the throw wire on vending machines for free food. Do as you please.

**Comment by yclatious** [comment]
A solid 60% of the reason I am doing this is due to the sheer lunacy of hyper inflation on food and 60 credits raisins triggering my autism to a boiling point. 30% is my personal beef with things costing too much to just have and sip around as a rp item like a soda can. The most important 10% is how fucking expensive it is to decorate stuff with food as a human and instead having to be a damn MoMMI to buy any decent amount of smokes, soda cans or whatever for a project, so don't you worry Dace, I am gonna be hitting that one next.

**Comment by Kurfursten** [comment]
What you're paying for is not the raisins themselves, but the convenience and security of getting a full meal without having to go to the kitchen (exposing yourself to other people) or eating food you didn't see prepared. If it's a matter of a immersions for you, e.g: "space inflation will never get so bad raisins will be $60!" - we should first ask why 2 boxes of raisins make a full meal from starving to sated in the first place. If raisins gave you 0.5 nutriment, I'd have no problem with them being $3.

@bathosbathtime Stock count isn't really a limiting factor. The 1 Getmore can easily feed 24 crewmen for a couple hours. I'm not even looking at the gimmick food items like gum or chococoins - only the main food items. 
Throw wire does at least cost you time: you need to either set up a monkey chair or sit next to it while it throws food at your face. It could be better, I've raised concerns, but it's not the worst thing ever.

**Comment by yclatious** [comment]
>but the convenience and security of getting a full meal without having to go to the kitchen (exposing yourself to other people) or eating food you didn't see prepared
What kind of powergaying moron do you take me for when you actually try and say that 60 bucks for a pack of raisins is legitimately worth it because I avoid playing socially in a social game. What kind of player do you assume me to be where you legitimately think I won't eat the chefs food and instead go on some paranoid shenanigan train of thought where I have to puree everything to make sure it doesn't have the spicy hot sauce. 

Do you legitimately consider this some kind of covert powergay powermove to encourage silent shuffling? Are you that dense?

FUCK OFF, MY IMMERSION IS RUINED THAT GODDAMN DRIED GRAPES COST 60 FUCKING CREDITS, I DON'T GIVE A SHIT ABOUT THEM MECHANICALLY BEING BETTER THAN FUCKING HONKIE CHIPS OR CANDY, IT IS FUCKING RETARDED, ENOUGH WITH YOUR FUCKING SHIT OF NUTRIMENT CASH RATIOS, ITS FUCKING DRIED GRAPES, ALLOW PEOPLE TO ATLEAST BE ABLE TO PAY 2 FUCKING PACKS OF DRIED GRAPES PER PAYCHECK YOU CUNT.

You do good work on Vox kurf, but you are mad retarded on this. Let the fucking grapes go. Let them fucking go. Let people have a technically decent source of fucking nutriment that isn't the chef, nobody but the most absolutely sweaty retards will ever go and become anti-social raisin munching NEETs in maintenance.

**Comment by Kurfursten** [comment]
I don't think it's a move *to* encourage silent shuffling, I think it *will* encourage silent shuffling. I believe your intentions are entirely good, which is why we can have this conversation without typing like we're ZaNy and comically pretend to be mad or something. Why not make raisins actually give you a nutrition level more consistent with actual box of raisins instead of a 2 course meal? Then we could have cheap RP raisins that you can pop just for fun.

FYI: I actually don't have a problem with lowering the price on sodas at all.

**Comment by bathosbathtime** [comment]
I don't think we need to go to the extreme of reducing them to 1 nutriment. 3-4 nutriments seems like a better alternative from the 6 nutriment they currently give, but I do agree that reducing the effectiveness of the vending machine food is a possible solution.
Suggesting that it be reduced to 1, however, seems intentionally inflammatory.

**Comment by Kurfursten** [comment]
If you want the price to be sixthed (60->10) it makes sense to sixth the nutriment, too. I don't see how it's inflammatory at all, it's symmetry.

**Comment by yclatious** [comment]
Who will it encourage silent shuffling _to_? Who do we actually have that would legitimately start checking the Github in order to find the optimal way of getting nutriment without ever touching the Kitchen? If you go and start by this logic, go and remove the donuts from the sec vending machine, free for everyone, and enough to stave off the hunger and even heal a little, optimal chef avoidance right there. Several vending machines in Box too, donuts for the whole shift, 0 cost.

That line of reasoning is silly. The chef won't stop being the pitstop for munchies and any powergamer of that calibre is already on the brink of being banned for rule 0 or several notes of bad play.

If you want to make a PR to reduce the damn fucking raisin nutriment after this, fine, I will even upvote it. Just get the damn hangup on raisins being good out of the way if it means you'l let the rest of it slip, but for Gods sake, stop defending actual 60 credits raisins. It is just so bloody stupid.

**Comment by Kurfursten** [comment]
>Who will it encourage silent shuffling to?

No one centralized place, that's the point. I feel like there's been a breakdown in communication at some point, like maybe you're skimming my posts. I'm saying what I'm saying based on a lot of experience - I was eating syndie cakes along with everybody else during that era. It's not something comical and dramatic like epic food strats or something, it's people doing what's convenient for them: staying in their department and getting the food that's closest instead of crossing the station.

**Comment by yclatious** [comment]
Raisins are 60% of the reason I am making this PR and I will not let go of the dehydrated grapes, it's about principles and standards and we ain't in AnarchoSyndicate yet, just good old Nanotransia.

Speaking seriously for 15 seconds, this ain't that era, we don't have players with the same habits of that era and giving players some !FUN! is good once in a while. Let them eat rais-Cake. Let them eat Cake. If it does create those bad habits you mention, you got full on ability and my non important permission to nerf this back into whatever you think reasonable and get it merged.

**Comment by RaccoonBro** [comment]
Doesn't eating too much vending machine food make you sick or am I thinking of another server? I know some have that to balance out cheap prices.

**Comment by yclatious** [comment]
Only some of the Dans food does that, but otherwise, no, not unless you drink the forbidden polytrinic juice.

**Comment by RaccoonBro** [comment]
Just make it apply to all of the vending machine food, ez

**Comment by PrimeDSS13** [comment]
what's the point of Discount Dan food if it's the same price as normal food
where's the SALE

**Comment by Kurfursten** [comment]
Confusingly this PR makes unpoisoned food cheaper than the poisonous dan food. Dan food used to be a bargain at 1/6 the price, now it's just a newbie trap.

**Comment by yclatious** [comment]
Alrighty then, dirtu cheapu darty dan, coming right up

**Comment by BomberBro** [comment]
I initially supported this PR thinking it was going to make the expensive garbage like raisins half price so there's a reason to buy them, but making all the food items from the getmore 10 or less to make just makes the chef irrelevant (even moreso) and has the epic effect of making "Discount" Dan's now a vendor for the rich and wealthy.  Making Dan's stuff cost 1 credit to compensate a going out of business sale is missing the entire point of the issue.

**Comment by GreatBigFailure** [comment]
Keep all vendor prices the same
Increase cargo prices
Drastically increase crew salary 
Leave starting money untouched

**Comment by Zach720** [comment]
> The problem with free food is that it makes the chef irrelevant. I remember the days of abundant syndie cakes where no one (certainly not me) ever went to the kitchen. Like why would you when there's a vending machine right inside the engie lobby on box?

The chefs already irrelevent, stop pulling things out ya ass, I want to see this merged, any change is a good change, fuck the status quo anarchism NOW!

**Comment by SonixApache** [comment]
the reason yclat was screaming about raisins so much
is because raisins are literally the powergamer's choice
they are the most efficient nutrition-to-price ratio

merging this has been a blow against good, honest, hardworking spessmen
may the powergay light the way

**Pull request merged**
