### PR TITLE
Braindamage gives you opinions on braindamage - Adds a brain damage line.

### PR DESCRIPTION
**Pull request by WindowsErrors**
Let us acknowledge our future, spacemen.

:cl:
 * rscadd: Add new brain damag lien.

### CODE REVIEW

**Comment by ancientpower** [comment]
I know why but please stop

**Comment by gurfan** [comment]
must be in all caps 👎

**Comment by NigglyWiggly** [comment]
None of the brain damage lines have ever been funny or good so I don't see what the big deal is

**Comment by Hinaichigo** [comment]
immulsions therefore downvote

**Comment by Exxion** [comment]
Why is this still open

**Pull request closed without merging**
