### PR TITLE
Box tweaks, bug fixes etc.

### LINKED ISSUE #22157: Boxstation's EVA has science suits, but scientists/RD don't have access to EVA.
(WEB REPORT BY: irradiation REMOTE: 206.221.180.138:7777)
# Revision
ced5d4a70e0cbc1f9de443cd82ef3b984bd4566d

# Description
See title.

# Steps to Reproduce
1 - Be a scinigger.
2 - Try to get into EVA to acquire the sweet gibsmedat science suit.
3 - Get cucked by lack of access to open the EVA door.
4 - Thanks, mappers.

# What you Expected
To get me gibsmedat suits.

# What Actually Happened
A scinigger had to nigger his way to get the gibsmedat.

### LINKED ISSUE #26586: Some wires that should be yellow are red
In #26471 I search-and-replaced for `/obj/structure/cable{` in order to avoid replacing cables of different colors such as `/obj/structure/cable/white`. I did not consider that south-facing knots would not have any vars overridden and therefore not have a `{` after the type.
image

### LINKED ISSUE #26602: The status displays in Cargo aren't set to show the cargo shuttle timer anymore
[box]
Starts as blank unless you go in and change them manually, someone messed up.

### PR DESCRIPTION
**Pull request by CptWad**
First PR back. Decided to try out this new map editor. Sweet.
Hit up some boxstation bugs to see what was poppin. 
box no longer applies to #26586
all instances of red wires were replaced.

After having a look through other maps I realized how behind box was in the atmos and wires presentability and consistency. At its inception the idea of "Keep wires and pipes in maint" and "Maintain a major grid that can split off into departments" were not really that high priority. On top of that box has had a history of being frankenstiens feature monster as new rooms are added and moved around. I started with wires here
Before
before

After
after

Ive turned the spaghetti into something more sensible. In addition each department can be directly tampered with for good or bad. (Genetics gets to be special for obvious reasons). If you want to attach an SMES directly to science you can do that now without complete rewiring of the entire department. Same goes with sabotage.

EVA
closes #22157

image

Adding suits to EVA that scientists cant access is silly. Though the remedy was to just add one of them to the box outpost (as it was missing one) I returned the old shitty space suits back to EVA as they were long missed on box. Six in total with the new emergency suit access button.

image

I moved the medical hardsuits to Medical.

image

Some extra shielding for xenobiology. A stray meteor could totally fuck xenobio due to the unprotected nature of its airtanks meaning that 1-3 meteors could total it requiring a tech to repipe the thing straight to the distro which for XENOBIOLOGY is a horrible idea. If you want to break in/out however its still easily done just closer to the soft inner center.

image

Many places on the station with electrified windows were not fully windowed. Seeing full windows as a form of (danger dont touch) is a kind of consistency I would like to keep so now the red squares have added full rwindows. Since all these do is add time to breaking in/out of places the only place I didn't touch is inner EVA since that revolves more around the time crunch/desperation.

also close  #26602

<box> <bugfix> <tested> <consistency>

:cl:
 * bugfix: Boxstation: removed the stray red wires from the station and replaced them with yellow ones
 * bugfix: Removed an extra pipe under another pipe.
 * tweak: Added an extra layer of shielding against meteors for xenobio. If someone wants to break in our out to space its still easy but now a single meteor can't own xenobios air supply requiring atmos techs to repipe the entire wing of science.
 * tweak: Rewired the station adding more redundancy to keep box up to par with other maps. Adjusted some areas to have wire paths prefer maintenance tunnels. Each department in box now has load bearing wires that can be improved via SMES addition or antagonized via cutting.
 * tweak: Added some distro pipe redundancy near the AI core. Thank me later pipe dwellers. Maybe ill repipe the hellscape that is box atmos some day.
 * tweak: Wherever electrified (or secure area) windows exist, a full rwindow has been placed for consistency reasons. All except EVA.
 * imageadd: Xenoarch gets one more hardsuit bringing the outposts count to 3 suits like every other station.
 * tweak: EVA tune up. Swapped the science and medical hardsuits with some 6 cheaper alternatives. 
 * tweak: Medical hardsuits moved to medbay storage.

### CODE REVIEW

**Comment by gurfan** [comment]
>tweak: Medical hardsuits moved to medbay storage.
👎  to this

**Comment by kernikov** [comment]
Completely fucked that you drew all the wires on box IMO

**Comment by CptWad** [comment]
if outlining insanity in order to redesign into sanity is necessary then fucked I am.

**Comment by CptWad** [comment]
already fixed a bunch of bugs on meta/deff/packed and now working on roid
im a dumbass and pushed through my bleeding edge so I cant make a separate PR till this one is closed lmao
unless I just staple 20-30 more bugfixes into a more general map bugfix pr I guess

**Comment by DeityLink** [comment]
> tweak: Medical hardsuits moved to medbay storage.

Welcome back home 😌 

> imageadd: Xenoarch gets one more hardsuit bringing the outposts count to 3 suits like every other station.

Thinking back on it it's crazy how over the past 8 years I just accepted that there being only 2 suits available despite there being 3 excavation tool closets was just a normal state of affair.

**Pull request merged**
