### PR TITLE
Return of the freeform jecties

### PR DESCRIPTION
**Pull request by Allspice**
Server vote had a plurality vote in favour of freeforms. No good to count "change but not this way" with "no change" when no other change is really being proposed in a robust fashion.

Anyway I guess I was asked for an emoji vote or some shit? so thumbs up for "merge this" and thumbs down for "don't merge this". And if this vote is legit I guess it ends 7 days from now. Not including a "change a different way" option because someone can do that in their PR when they implement that change.

:cl:
* tweak: Return of freeform objectives

### CODE REVIEW

**Comment by ammy55** [comment]
The server poll was pretty clear on not having freeform objectives. Don't go trying to ram this shit in just because the poll split the base, "not this way" is still "not freeform".

**Comment by Allspice** [comment]
"Not this way" implies that someone will put something in the works in the foreseeable future. So far as I know nobody is working on such a thing, and I'd rather not wait a year or more for someone to hopefully get the gumption to produce a more interesting system. If you (or other people) want an alternative, I would be interested to see your pull request.

Would have been better if I pointed out that the poll was fucked before it concluded, but spess was too broken for me to play until after the poll ended so o well.

**Comment by ammy55** [comment]
> I'd rather not wait a year or more 

if only we had some way to get a community opinion. Perhaps a poll. On what they'd preffer. In fact, i seem to recall something like that, and it said "don't fucking do this" and "Don't fucking do this, do something else though"

**Comment by Allspice** [comment]
1. Polls do not make code.
2. "Change but not this" presumably split the base of freeform jecties just as much as it did status quo, since it's sort of a rejection of both. So if you drop that option (since it's useless until someone steps up to their text editor and cranks something out) then freeform had more votes than no-change. And just to repeat, using the "change but not this" to support no-change is a bit silly since they're explicitly saying no to no-change.

Anyway instant-runoff voting would have averted this dumbness but O WELL.

**Comment by ammy55** [comment]
If you're not going to respect polls then why have them at all. Just self go full fucking self speedmerge  cowboycoder.
Change but not this is explicitly anti-freeform, and if you'd read the thread most of the "Change but not this" was just for better jecties, which is about as far from freeform as you can get. Change but not this would absolutely not be evenly split between freeform and status quo.
Agree though, single transferable vote when?

P.s \>polls don't make code
\>literally changes a 1 to a 0

**Comment by Tehsapper** [comment]
>"Not this way" implies that someone will put something in the works in the foreseeable future.
then drop it and wait until someone presents something that is accepted by the majority.
>So far as I know nobody is working on such a thing, and I'd rather not wait a year or more for someone to hopefully get the gumption to produce a more interesting system
smells like speedmerge spirit

**Comment by ShiftyRail** [comment]
Objectives are so dumb I'm surprised there is some actual debate on this
This screencap is a good example of what I mean
image
Rather than actually doing anything funny or interesting whilst sec was busy, the guy here just masturbated over some blueprints out of fear of losing his greentext

Objectives are shit

**Comment by Gringonius** [comment]
Clearly removing objectives will suddenly make new players do interesting things.
This is a pointless PR unless admins start acting like DMs to freeform traitors, giving them some purpose with a little directnarrate like how chaplains often are treated.

**Comment by DeityLink** [comment]
Not every players are creative, some perform better with complete freedom, others perform better with concrete guidelines (I personally identify as the latter). Ideally traitors could choose either when assigned, except server rules already permit traitors to ignore their objectives, therefore there is no good reason to force freeform jecties for everyone, unless alienating a good chunk of our playerbase be considered one.

I think this issue should be tackled in a different way, stop reverting this change every few days for fucks sake.

**Comment by morenaaa** [comment]
Why are you all still ignoring one of the most thumbs-up comment on any of the PRs about this, it's here: https://github.com/vgstation-coders/vgstation13/issues/19489#issuecomment-416048770
And if you don't want to open it I'll just post it in full here.

> Why objectives are bad:
> 
>     They rely on a binary fail/succeed which limits them severely because more complex objectives would be a nightmare/impossible for the code to check for failure/completion. Example: Minimize casualties is 100% impossible to code in satisfactorily, and so would be anything with a broad scope or anything that requires quantifying player interaction which is 90% of the game.
>     They have no awareness of what's going on in the round. You can have the most interesting bus/gimmick/court case going on and the code will never have any hope of detecting it, it will just pick a random thing to do. It's entirely fair to say that objectives are an entirely separate minigame running on top of the real game.
>     They're extremely concrete with a narrow scope (mostly because of point 1). Because of this it's only natural for the player to focus inside this narrow scope to get the result they need in a simple/safe way. Compare "steal X item" to "steal from X department": In the former the player will probably focus on stealing that specific item and then consider it done and fuck off. In the latter the player will start to think what would be the most interesting/helpful thing to steal, and after they get it, they have a motivation to keep stealing. A broader scope greatly improves how the task gets approached (and also, has a much better chance of being relevant to what's going on in the current round, as opposed to "steal this specific item that might not even be in use").
> 
> How to improve them:
> 
>     Just ditch the success/fail conditions. You don't need extremely complex and finicky code to determine if you really made the RD mad or not. Do you feel like you won? Then good, you won.
>     Write them to be more of a motivation/guideline than an objective. "Kill the CMO" = bad, "The CMO ruined your life" = good because there's a million ways to go about getting your revenge and even extend it to other people.
>     Make it common for players and admins to make new motivations/guidelines mid-game. They'll naturally try to pick something they think will work based on the current round. Really, you should be able to make and edit your own motivations/guidelines if you wanted.
>     At roundstart give players the choice between 3 different motivations/guidelines, if you get one you don't care about or that you know wouldn't be interesting because of playercount/manifest/whatever, you should be able to reroll it, why not?
> 

Deity, we do not need people being tracked & rewarded for completing objectives, especially in the case of traitors and mixed types. Each antagonist type is powerful enough as is, and continually giving them more and more goodies as the round goes on because they did the thing is broken, especially when they already start out with high strength potential. We already bitch about Changeling and Vampire becoming too strong later on, you're essentially arguing traitors should be exactly the same.
Imagine giving a wizard more points his his spellbook as he "completed objectives". Within ten minutes you'd have something so overpowered it would be an instant shuttle call. This is all you're suggesting, but with a traitor instead. You're just giving people more incentive to play like shit, not less. 

Removing objectives isn't going to fix one of the core issues with the server: the players.
If you want people to be better antagonists, to be more engaging or interesting, you need to lead them towards it and not leave it wholly up to them. Without objectives, you'll get an influx of players who will just kill people and call the shuttle. Because this is their internal win condition for the game, and they are playing it to win. Admittedly, we don't have a lot, but it will increase as people run out of ideas and guidance for what to do when an antag. And you see this on the flipside, with our current objectives system, people bragging in OOC or deadchat that they completed their objectives and got "greentext", as well as people talking about how they are the reason for someones "redtext". They're internalized win conditions from the endscreen providing the reward of validation. 

This is a roleplaying game, you create a character, pick a class and have job to do as things start to fall apart around you. This isn't a top down shooter, it's not a bloodbath action game, and while we admittedly don't hold ourselves to super high standards, we should at least hold ourselves to some standard, on all fronts, including antagonists.

**Comment by DeityLink** [comment]
Redeeming the points was just an idea, I'm not planning to fight for it if people don't like it. That being said

>At roundstart give players the choice between 3 different motivations/guidelines, if you get one you don't care about or that you know wouldn't be interesting because of playercount/manifest/whatever, you should be able to reroll it, why not?

is pretty close from what I had in mind.

**Comment by Allspice** [comment]
Imgur

**Comment by Shadowmech88** [comment]
>No good to count "change but not this way" with "no change" when no other change is really being proposed in a robust fashion.

Then it sounds like what you need to do is propose another change, not reintroduce the same change that a majority of people did not want.

**Comment by Exxion** [comment]
That's a spicy sampling bias
*But* the actual answer to the question is that, while a *majority* may not want the change, more people want the change than want no change
(Probably)
(Can't know for certain because of how the poll was structured)

**Comment by Shadowmech88** [comment]
>more people want the change than want no change

I don't think that's a good reason to add a change that most people don't want, rather than just coming up with a different change.

**Comment by Exxion** [comment]
So come up with a different change, then

**Comment by Shadowmech88** [comment]
I never said I wanted any change at all. The onus to come up with a different change is on those who want it changed.

**Comment by Exxion** [comment]
But why would it make sense to stick with the *least* popular option until someone comes up with such a change? It's not like closing this will make someone come up with one any faster.

**Comment by Shadowmech88** [comment]
It may, if it causes those advocating for this to work at coming up with a new change that is acceptable to more people, instead of doing nothing once this is merged due a change having already been made to their satisfaction.

**Comment by Allspice** [comment]
It seems to me that any such change would be subject to `yet another fucking vote`; if you want to drum up the patch, you can do that, but I'd really rather not be stonewalled by having to go through three votes for approval. And what I super really rather prefer not to have, is to go through sixteen freejecties majority/plurality/whatever and for the seventeenth to be in favour of status quo and coincidentally the will of the people.

**Comment by DamianX** [comment]
50/50 are ALWAYS closed

**Pull request closed without merging**
