### PR TITLE
Fixing a bunch of metaclub issues

### PR DESCRIPTION
**Pull request by Duny-**
Fixes https://github.com/vgstation-coders/vgstation13/issues/15715
Doesn't stop the atmospherics computer from not working though
Fixes https://github.com/vgstation-coders/vgstation13/issues/16551
image
I just made an exact copy of box's permabotany
Fixes https://github.com/vgstation-coders/vgstation13/issues/18437
image
Fixes https://github.com/vgstation-coders/vgstation13/issues/18685
image

This doesn't look like a mapping issue to me famjam:
https://github.com/vgstation-coders/vgstation13/issues/16686
https://github.com/vgstation-coders/vgstation13/issues/14809

:cl:
 * wip: The following map changes apply to Metaclub.
 * bugfix: Fixed the vent in xenobiology specimen cage 1 not linking to the air alarm.
 * tweak: Moved the scanner and sleeper in front of the defibrillator in medbay one tile to the right.
 * bugfix: Gave perma the same botany area as Box.
 * tweak: Made the security airlock into an actual (cycling) airlock.

### CODE REVIEW

**Comment by DrSnips** [comment]
If you're doing tweaks to meta could you please make the Xenobio cycling airlock match box's? It's been a while but I remember having issues letting out borers and having to leave the doors to maint open.

**Comment by Duny-** [comment]
What's wrong with this airlock :thinking: 
image

**Comment by DrSnips** [comment]
I forget what the exact issue was but I recall borers saying they had issues vent crawling out. All I'm asking for is a simple nudge south 3 tiles and an airlock to seperate the maint intersection and cycling airlock area.

**Comment by DamianX** [comment]
I removed the mapping (meta) label from #16686 but I've only ever seen #14809 happen on meta, multiple times. Doesn't necessarily prove anything but the tag is staying for now.

**Pull request merged**
