### PR TITLE
Remove blood boil

### PR DESCRIPTION
**Pull request by Allspice**
the compromise for #18561
apparently >100 damage in an aoe makes people unhappy or some thing
:cl:
* tweak: Removes blood boil.

### CODE REVIEW

**Comment by Shadowmech88** [comment]
Replace it with blood freeze, makes people pass out from hypothermia.

**Comment by Reviire** [comment]
Replace it with something that actually boils blood, they lose half their current blood and it creates blood smoke

**Comment by Pathid** [comment]
Could have it rapidly raise their body temp while consuming their blood. Would fail entirely against plasmamen but hey, better than nothing, right?

**Comment by Kurfursten** [comment]
Blood coil

Removes 5% of the target's blood but creates a full cable coil stack at their location

**Comment by Shadowmech88** [comment]
Blood oil: Removes blood from the targets and coats the floor in a mixture of blood and space lube.

**Comment by Diavill** [comment]
Blood soil: creates red sand in a 9x9 aoe for your Nar Nar summoning needs

**Comment by Accipitermaris** [comment]
rune that makes your screen freeze and forces you to downgrade to 510

**Comment by Shadowmech88** [comment]
Blood gargoyle: Takes half a target's blood and turns it into a hostile gargoyle mob that attacks them.

**Comment by RealestEstate** [comment]
Blood Boil: Makes the victim develop a red bloodied boil on their skin that periodically irritates them until it pops and then they lose 1% of their blood

**Comment by DamianX** [comment]
Blood Boi: a blood boi shows up and links with you in parabiosis

**Comment by Irradiation** [comment]
Blood Fist: A non-cultist in your field of vision gets punched by a fist of blood, draining him of blood and staining his clothes with blood.

**Comment by SonixApache** [comment]
Blood Noill: Summons emagged bootyborgs that drain you of your precious bodily fluids.

**Comment by Durgen** [comment]
Blood Moyle: A rabbi appears and circumcises all non cultists nearby, doing 100 brute damage to their groins.

**Comment by Blithering** [comment]
Blood foil: victims lose 5% blood and can't be microwaved

**Comment by MusgardTiger** [comment]
Don't you need three cultists to use blood boil rune?

**Comment by Killette2** [comment]
Blood spoil: rots all the food in an AoE and covers them with blood

**Comment by Exxion** [comment]
Also blood foil: Removes some blood and gives them a fencing sword

**Comment by icantthinkofanameritenow** [comment]
@MusgardTiger Yes, and it's much easier to kill someone the old fashioned way rather than dicking around with two other people to stand next to a rune hoping that your victim's stun doesn't wear off before the thing can activate.

I have never actually seen this rune being used at any point in time.

**Comment by Blithering** [comment]
@icantthinkofanameritenow  You've never seen a cult trader shuttle then, blood boil rune hidden under the desk, two traders and a random pretending to browse. instantly kills anyone that approaches.

**Comment by Pathid** [comment]
You know, maybe first we could fix it so the area of effect is the view of the rune like all the other runes, instead of the view of the user.

**Comment by SonixApache** [comment]
no compromises

**Comment by Exxion** [comment]
@Pathid You still die then
You just get to see what killed you

**Comment by DeityLink** [comment]
I got no complaints here, this rune is imbalanced and has to go.

However I'd rather it being commented out than outright removed from the code.

**Comment by SonixApache** [comment]
whaaaaat

**Comment by Blithering** [comment]
@SonixApache I assume this is related to cult 2.0 datums, could be wrong though.

**Comment by Exxion** [comment]
Yeah @jknpj could you clarify?

**Pull request closed without merging**
