### PR TITLE
Fix issue 26013 (age restriction for borging)

### LINKED ISSUE #26013: no age restriction for becoming a borg midround
#### Description of issue
cyborg has a minimum age requirement of 10
last round, I saw a borg with a player age of 2.
when the borg died and ghosted, it was a posibrain.

presumably, the minimum age restriction doesn't count things like being manually placed into a silicon shell.

#### Difference between expected and actual behavior
people who are so new that they can't possibly be expected to know the nuances of laws can become silicon roles despite not being supposed to

#### Steps to reproduce
seize the means of reproduction

#### Specific information for locating

https://github.com/vgstation-coders/vgstation13/blob/e603182c409877ff384caba0d4afe988c810ab17/code/game/jobs/job/silicon.dm#L30

#### Length of time in which bug has been known to occur

probably forever, honestly.

#### Server revision

45f86bad83ef8acb1674171915208b09b08bd2f5

### PR DESCRIPTION
**Pull request by s-h-d**
closes #26013
Tested locally with a DB and 2 PCs. Tested borging via MMI, posibrain, and malf AI autoborg.

:cl:
 * bugfix: Enforcing the age restriction when getting borged

### CODE REVIEW

**Comment by ShiftyRail** [comment]
as a note : you don't need 2 PCs to test that. Make a 2nd byond account, host the game, join with your main account (with the button), log off the pager, and log on with your 2nd account, and join again.

You can do that with a guest account too, but you won't be able to test stuff as silicon or head roles.

**Comment by s-h-d** [comment]
When I logged on a 2nd time on the same PC as a guest, it recognized that the guest has the same IP as the host and linked it to the host cdkey. I wasn't sure if it would affect the test so I said "fuck it" and used a 2nd PC.

**Comment by ShiftyRail** [comment]
there's no consequence. this warning is just meant for people who are trying to multikey. you can disable it `_compile_options.dm`.

**Comment by SonixApache** [comment]
Title: Put something descriptive in the title, preferably what the PR actually does 
(eg. "`Fixes age restriction for borgs`")

Body: put your linked issue here **with** powerword. 
Powerwords are `closes`, `fixes`, `resolves`. 
(eg `closes #26013` )

🆑: Put something descriptive **for the players** here
(eg "`The 10 day account age requirement for borgs is now properly enforced`")
Also may want to change it to either `bugfix:` or `tweak:` but that's mostly fluff

Good PR! :+1:

**Comment by Kurfursten** [comment]
In the CL, change it to `* bugfix:`, it's just good practice

**Comment by tuypo1** [comment]
So those of us who like borging our victims as traitor are just gonna get fucked by them failing to borg more often? and going into robotics to print the borgs is already a high risk thing so getting the reward less often is gonna hurt
And doing it with malf autoborgers is especially retarded, if the concern is that they don't understand silicon laws that's not really important when under a freaking malf ai

**Comment by Kurfursten** [comment]
Could make brains examinable text, "This one is not certified to be used for silicon life!"

**Comment by tuypo1** [comment]
I suppose that would work, still have to go to the trouble and risk of getting the brain out but it's always at least a few seconds saved meaning getting the fuck out of robotics and out of the eyes of science and the ai faster

But I still think it makes no sense to restrict malf autoborgers

**Comment by s-h-d** [comment]
Well as it stands you can't autoborg someone who is banned from playing borgs, presumably because they are shit at following their laws (like a new player)

**Comment by Kurfursten** [comment]
@tuypo1 Also, if you knew in advance that you could examine the brain, maybe you could debrain your victim somewhere else like ghetto surgery or in maint and then throw their brain into an MMI if it is borgable. Then carry that into robotics. (Or better yet... bring the borg frame out of robotics to surgery - you can fit a whole borg frame in your backpack)

**Pull request merged**
