### PR TITLE
Removes duplicate tank icons that have haunted the map editor for years

### PR DESCRIPTION
**Pull request by Irradiation**
Back in 2019 when I made the PR for barrels (https://github.com/vgstation-coders/vgstation13/pull/24696), I had accidentally included duplicate icons for welder/water/silicate tanks. They aren't seen anywhere ingame, but for whatever reason, the map editor uses their icons instead of the normal tanks that we see ingame.

Dupe 1
Dupe 2

## Why it's good
I felt bad about it for years and finally owned up to my mistake.

## Changelog
:cl:
 * rscdel: Removed duplicate icon files for tanks that were only seen in the map editor.

### CODE REVIEW

**Comment by Eneocho** [comment]
just rename them to __tankOLD and map them in the ejected core vault for that EXTRA bit of ancient stuff like the old canisters

**Comment by Irradiation** [comment]
I'll leave that to the ideaguys, these sprites never should have been added into the codebase in the first place as they don't gel well with the sprite style that we have.

**Comment by angryturnip** [comment]
Humiliation ritual

**Comment by toomykins** [comment]
sad because i love these little guys

**Pull request merged**
