### PR TITLE
Pops economic inflation like a balloon

### PR DESCRIPTION
**Pull request by yclatious**
Because no, 700 bucks for a painting, 200 for snowflake items or 150 for crayons were never acceptable prices and were always stupid. If you do an economic reform, don't forget to pop the inflation down to actual purchaseable prices.

:cl:
 * tweak: Popped the economic inflation into normalized levels in the Merch Computer.

### CODE REVIEW

**Comment by BomberBro** [comment]
Gonna make any normal source of food irrelevant when you can pay 25 bucks from an infinite vendor for a large meal, the fast food was justifiably expensive because you can get as much as you want.

**Comment by SageOfLight** [comment]
Fill all cargo food with heart destroying corn oil.

**Comment by DeityLink** [comment]
Thanks, that's usually where I get my meals from. Also Disquette boxes.

**Comment by SonixApache** [comment]
thank you for supporting hard-working delivery food workers

**Comment by yclatious** [comment]
Sorry Diety, Bomber had a point with the price slashing. Its kind of stupid, but he does have a point and I do go a bit overboard with it.

**Comment by DeityLink** [comment]
@yclatious Objection your honor! Allow me to defend my point:

Exhibit A: this spreadsheet

image

As you can see the Fast Food Menus boasted a really decent Nutrition per Dollar (NpD) until now, but while it is an "infinite" food source, it still requires you to walk all the way to cargo, and not benefit from the proximity of vending machines. Cargo techs themselves have infinite pizzas anyway. Remember that time is money. I expect more nutrition per dollar for taking the time to walk all this way.

Secondly, Bomber's point of it being an infinite vendor is moot as many other food sources in the game are infinite. Keeping the prices high to prevent abuse will just cause people to stop using it altogether. Fast Food is meant to be cheap, not a luxury, and keeping the old prices gives it the worst NpD by a large margin, only beaten by that joke of a food item that are space twinkies.

By keeping their new prices of 25$ and 50$ respectively, the vending machine snacks are still boasting an already superior NpD (except the twinkies again lol) which gives incentive to use them should they be closer.

**Comment by yclatious** [comment]
I cannot argue with a man that bring spreadsheets to his arguments in order to make fast food cheaper, nor would I ever want to cross that man.

Reverting prices back to original nerf values.

**Comment by streaki** [comment]
I'm considering a serious tweak to all food items from vending machines after these "economy repair" PRs pass. As is, junk foods can completely replace a full meal with no consequence at all, which makes chef even more cucked than before.
I think they should contain more corn oil and sugar than nutriment.

**Comment by DeityLink** [comment]
Also there's an inaccuracy in my spreadsheet: soda and other juices have a custom metabolism twice that of nutriments/sugar, so they actually translate to half less nutrition. Sodas basically don't give you any calories in spess. For shame. I want my sodas sickenly sweet.

**Comment by DeityLink** [comment]
Also @streaki 1 corn oil translates to 4 nutrition, so it's actually more nutritive than pure nutriments.

**Comment by streaki** [comment]
@DeityLink I know, but I thought it had *some* health effects. If it's not enough, then new reagents can still be discovered.

**Comment by BomberBro** [comment]
Many other sources of food in the game are infinite, true, but they require some form of interaction between people (ie botany or cargo) to acquire, which personally I don't see an issue with. The vending machines having high nutriment per item is a pretty lame metric to go by regardless since the vending machines have relatively small stock, which combined with cheaper prices is quickly going to go out most rounds, and I've never ever seen those vendors refilled. The merch computer is an infinite source of sabotage-free food which requires no interaction and can't be messed with (unlike cargo pizza, or any food you get from the chef/botanist). 

Walking to cargo being a downside is a joke, cargo is consistently in the most walked places in maps, with every single map except horizon having the department and its vendor smack in the middle of a major hallway you're going to pass anyway (especially true on deff, where it's next to medbay, the bar, science, and the mining/science shuttle). The only time you wouldn't be in a position to constantly pass cargo is if you're playing a NEET job like virology, but those have their own roundstart survival rations that are likely to last them the game given that they don't move much.

**Comment by BomberBro** [comment]
Applies to Roid as well and Meta (to an extent). I'd be perfectly fine with this PR if the do not tip backdoor also pozzed the merch food, but my main point against this is that it's an infinite, instant, relatively cheap (with the PR) source of food that you know is always going to be safe. There's no danger involved for this, and it feels pretty unfair when comparing to the honest, regular joes who slave away in the kitchen to bring you deep fried donk pockets.

**Comment by ancientpower** [comment]
In regards to the "this is going to make chef obsolete" argument: you can already survive just fine off of vending machine food at its current prices. Most players eat the chef's food not because it's efficient but rather because they're at least trying to roleplay and interact with other players. Nobody cares about money except "muh economy" coders so I can guarantee most players aren't going to exclusively eat vending machine food because it's cheap.

**Comment by BomberBro** [comment]
food

**Comment by yclatious** [comment]
Fukken beautiful.

**Comment by bathosbathtime** [comment]
why does the merch computer offer food to begin with

**Comment by yclatious** [comment]
Why were paintings 700 credits?
Why were crayolas 150?
Why did some snowflake clothes for a very angry man with a llama fursona cost 200?
Why were pens so absurdly costly?
Why were beach balls breaking the bank when they are beach balls?

Beats the fuck outta me brotha, I'm just playing with the deck of cards people provided me. I don't care if it has about 3 jokers, a MtG black lotus, a pot of greed and atleast 3 minor arcana from classical tarrot, I'm just here to play calvinball.

**Comment by SonixApache** [comment]
:cl: should be `tweak` imo

**Pull request merged**
