### PR TITLE
Floorpills

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
1 is guaranteed to spawn in ghetto surgery, an average of 1.6 will spawn in the rest of maint (especially in maint close to Medbay)

Almost all of these are guaranteed to have a noticeable effect upon eating
It may be good, it may be bad, it may simply be weird, but it's never something out of this world like slimetoxin or nanobots or some shit like that
Some have very uncommon chemicals that otherwise almost never see the light of day
Not all of these are safe to just crush into a soda can to identify the contents. Be careful.

:cl:
 * rscadd: Mysterious pills have started appearing in Maintenance. Be very careful.

### CODE REVIEW

**Comment by Irradiation** [comment]
Isn't the waterpotass pill going to immediately blow up since the pills aren't no-react?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
But they are

**Comment by Irradiation** [comment]
*shrug

Also I like how you're 100000000% more likely to find the following chems in pills as opposed to people actually manufacturing those

>LITHOTORCRAZINE 
HEMOSCYANINE

**Comment by Exxion** [comment]
Remember that black food coloring exists, if you want to up the mystery factor a bit

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I tried that but it only works for drink glasses and soda cans, so what's the point if people will just crush them into beakers instead

**Comment by Exxion** [comment]
They'd have to go through the trouble of getting an actual beaker
Certainly not hard, but harder than a can

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Or a mortar or a syringe from any blue medkit

Also that gives easier access to food coloring in general, so I'm not sure it's worth it for what little it will accomplish

**Comment by Exxion** [comment]
A mortar's honestly harder than a beaker, but you got me on the syringe
Anyway, I did say "if you want"

**Comment by Durgen** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE i double dog dare you to throw xenomicrobes in there

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
@Durgen done

**Comment by Durgen** [comment]
@I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE based

**Pull request merged**
