### PR TITLE
morgue light for "dead and potentially revivable"

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
adds a little green light to the morgue if the body is dead and ghosted
image
this does not activate the big neonblue morgue door lights, those only light up if you return-to-body and get the normal full green light

changes the morgue descriptions

## Why it's good
did you just ... put a dead body into the morgue? and the ghost didn't reenter his body? you should really know better, i'm giving you a fine and noting this in your security records

## Changelog
 * rscadd: morgue light for potentially revivable bodies
 * tweak: changed the green morgue light's description

### CODE REVIEW

**Comment by jwhitak** [comment]
Make it yellow! Stoplight colors.......

**Comment by pedr69** [comment]
i tried both yellow and purple, and they're both too similar to existing lights (orange for items and no body and red for unrevivable)
post a PNG you think works better if you can make one

**Comment by gallywix4** [comment]
>put a body in the morgue
>one green light shows up
>try to revive him but he was afk

the whole point of putting bodies on the morgue is to be sure they want to come back, adding a false positive is a bad idea.

**Comment by pedr69** [comment]
that's what i thought too until i spent half an hour screaming at a trialmin
PR'd this just so i can go picrelated incase it gets merged
image

**Comment by gallywix4** [comment]
> that's what i thought too until i spent half an hour screaming at a trialmin PR'd this just so i can go picrelated incase it gets merged image

Make admin feedback insted of a PR, It's not a big deal going inside the morgue considering the place lights up with the click of one (1) button, and the argument that you can't see the round is stupid since you only need to enter and leave the body inside the morgue to get the attention of a doctor

**Comment by pedr69** [comment]
i will leave this up because i see it being potentially useful and also because i spent an hour testing it
the chef prioritising the unrevivable bodies comes to mind

**Comment by djkramer123** [comment]
dumb and unneeded, just reenter your body

**Comment by kilozombie** [comment]
I was the dumb trialmin advocating for this, the main reason is because I personally don't like sitting in my body for very long. Obviously though there are downsides to this approach, the false positives would suck ass

Intense, admirable cajones in actually fucking programming this instead of just letting it be a stupid idea. I'm proud and a little scared.

**Comment by SonixApache** [comment]
i rike this

**Comment by cloutcode** [comment]
i steal bodies from the morgue

**Comment by Servalfang** [comment]
it's not a false positive though. it's just signing that you may want to check up on them in like five minutes.

**Comment by Kurfursten** [comment]
I have weighed the competing opinions giving preference to administrators in this case. I think this is interesting enough to at least try it out. If you hate it, at least give it a week before the revert PR.

**Comment by pedr69** [comment]
what wiki? the morgue lights are only ever mentioned in the examine text

**Comment by Kurfursten** [comment]
Doctor page please

**Comment by pedr69** [comment]
the one mention of "morgue" in http://ss13.moe/wiki/index.php/Medical_Doctor is a link to the morgue which also doesn't mention the lights at all

**Comment by Kurfursten** [comment]
I am just asking you to add a section to the wiki explaining morgue lights. Isn't this exactly the issue that motivated you to make the PR and argue with trialmin to begin with - ambiguity over lights?

**Comment by pedr69** [comment]
image
;AI update the wiki instead of me law 2 thanks

**Comment by Kurfursten** [comment]
It was easier to just do it myself than have this dumb back and forth

**Pull request merged**
