### PR TITLE
More bagel bugfixes

### LINKED ISSUE #14920: Bagel doesn't have the fancy surgery crate
It was added in https://github.com/vgstation-coders/vgstation13/pull/14854, which was merged after Bagel's PR was created. No biggie.

### LINKED ISSUE #14922: It's impossible to reach the flaming death machines on Bagel's shuttle
I of course mean the thruster heaters.

Every other map has plasma glass separating them from the shuttle, meaning if you break the glass the shuttle gets flooded with the flames that are produced.

### LINKED ISSUE #14924: No Autopsy Scanner on Bagel
#### Description of issue
Bagelstation does not have autopsy equipment in the morgue or in medbay anywhere, autopsy equipment cannot be created

#### Difference between expected and actual behavior
Autopsy scanner at the very least available in morgue

#### Steps to reproduce 
Play Bagelstation

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of not being yelled at by every contributor.

- [x] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/d3athrow/vgstation13/issues)

### LINKED ISSUE #14932: [BAGEL] Mech bay has no button for shutters
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

18c70c3580745a3b020fbab1ddd4c2ed8e1954f6 
>General description of the issue

DOOR STUCK

### LINKED ISSUE #14934: [BAGEL] Research Director office APC isn't connected to the power grid
#### Server revision

18c70c3580745a3b020fbab1ddd4c2ed8e1954f6

### LINKED ISSUE #14936: Bagel: no head of staff console in the HoS office
i'm not sure if they are missing from other offices as well

### LINKED ISSUE #14951: Nuke ops shuttle
(WEB REPORT BY: blitzikaze REMOTE: 172.93.109.202:7777)
The nuke ops shuttle is stupidly close to the station on bagel. Anyone walking the perimeter of the station can clearly see it.

### LINKED ISSUE #14954: Aft port maintainence APC still floating in midair
(WEB REPORT BY: icantthinkofanameritenow REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)
49653a6c429e458aeb69b7381295370245b7f68b 
>General description of the issue
See the name

>What you expected to happen
That the APC is fixed since I already reported this once before. 

>What actually happened
It's not fixed at all. 

>Steps to reproduce if possible
Play Bagelstation.

### PR DESCRIPTION
**Pull request by CptWad**
fixes #14920
fixes #14924
fixes #14922
fixes #14932
fixes #14936
fixes #14934
fixes #14951
fixes #14954

:cl:
- bugfix: More Bagel Bugfixes

### CODE REVIEW

**Comment by CptWad** [comment]
ready now

**Comment by CptWad** [comment]
haha my mapmerge didnt work

**Comment by Intigracy** [comment]
Probably forgot to clean map bruh

**Comment by CptWad** [comment]
cleanmap does nothing

**Comment by CptWad** [comment]
just merge it tbh what could go wrong

**Comment by CptWad** [comment]
actually nevermind ill just remake it, while I was passed out from extreme sickness a lot more bugs cropped up

**Pull request closed without merging**
