### PR TITLE
Radials 0.21.3_c

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Adds radials for microwave and grinder

Adds a way to add tooltips for slices (currently unused)
dreamseeker_2018-10-03_20-00-46

TODO:
Tooltip positioning works 100% perfect for the cult forge but weird for the bunsen burner, investigate why (EDIT it's because tooltips are hardcoded to always snap to a tile isn't that great and good)

@DeityLink 

:cl:
 * rscadd: Added a radial menu to the microwave and grinder alt+click. Ctrl+click shortcut for fast-turn-on is still available for max speed.

### CODE REVIEW

**Comment by DrSnips** [comment]
Could you please give the chem heater and cooler a similar menu to the Bunsen burner?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Those don't even have a fuelport, what shortcuts would there be? Turn on and examine?

**Comment by DeityLink** [comment]
Can I set custom colors for the tooltip's box and text?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Tooltips have that functionality yes but I haven't added a way to customize it via radial yet

**Comment by DeityLink** [comment]
do it do it do it do it do it do it do it do it

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
By the way is it intended that the cult forge turns the room into a fucking gas chamber

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
dreamseeker_2018-10-04_03-10-52

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
firefox_2018-10-04_15-08-59
God dammit Deity

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Makes it scarier

I couldn't test the tatoos menu because I don't know how to manually advance the cult stage or whatever but it should work

**Comment by DeityLink** [comment]
There's a button under the Special Verbs tab to set the veil thickness. Right now it's set to 5 by default, (which is cult victory, so all tattoos are available)

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
dreamseeker_2018-10-04_16-35-47
Tattoos work but there's the issue that for radials that have off-grid options (basically an amount of choices that is not 2 or 4) the tooltip will snap to grid and I haven't been able to disable that yet because radials work weird.

**Comment by Kurfursten** [comment]
I don't know about adding these radials on alt click since it just introduces an extra click if you are a botanist or chef who needs to detach that beaker a lot (e.g.: you're making condiments).

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
The most common shortcut (turn on) is always available and don't forget that the grinder forcibly opens its window in your face every time it's done

**Comment by DeityLink** [comment]
>list("Forge Armor", "radial_armor", "The quote originates from the Spider-Man 2 video game released in June 2004. Near the beginning of the game, Peter Parker as Spider-Man is given free roam through New York City. The first mission is to make it to Doctor Connors' class on time, which is emphasized in a quote spoken by Parker before having to get to class.")

u wot

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I wanted to test what it looked like with multiple lines

**Pull request merged**
