### PR TITLE
Reagent tank costs are a bit more sensible

### PR DESCRIPTION
**Pull request by WindowsErrors**
[tweak]

a response to #30403 and #30365

30 feels too high for such an order, that's more expensive than the crate of surgical tools and the crate with the fireaxe, you can literally get security weapons for the same amount of money that you can get a single fuel tank for

Water and silicate decreased to 10 per tank, 15 for fuel and acid

as an aside, I have not noted a single mass fueltank gimmick between now and the cost increase

:cl:
* tweak: reagent tanks cost less

### CODE REVIEW

**Comment by Eneocho** [comment]
Poorly inserted changelog. Use:
`:cl:`
`* tweak`

**Comment by WindowsErrors** [comment]
ok fine

**Comment by DamianX** [comment]
I think they're fine as they are. No one ever needs them, but when they do need them, they're expensive enough that you can't get stupid amounts of them, yet cheap enough that you can get all the reagents you realistically need.

**Comment by WindowsErrors** [comment]
Yea, well, you know, that's just, like, your opinion, man

**Comment by WindowsErrors** [comment]
someone told me that they use welding fuel as rocket fuel for the ships which explains why it's so retardedly expensive from cargo

**Comment by Kurfursten** [comment]
We have been back and forth on tanks more than they probably merit.

**Pull request merged**
