### PR TITLE
MALF AIs now have a chance to roll midround with very low odds.

### PR DESCRIPTION
**Pull request by Irradiation**
capture
MALFIE makes more sense as a midround antag than roundstart for a few reasons:
1 - AIs somehow manage to be instantly malfunctioning when the shift begins.
2 - Nobody likes the very likely instant or soon-to-be instant plasmaflood before anybody can prepare or whatever.
3 - MALF AIs aren't supposed to occur often, so the requirements to roll it will follow that logic.
3.5 - I got dared to do this, sort of.

[balance][gamemode][tweak][controversial]

:cl:
 * tweak: Malfunctioning AIs can now occur dynamically midround with incredibly low odds. Dead/Low Lowpop can't roll midround MALF.

### CODE REVIEW

**Comment by yclatious** [comment]
Fuck roundstart AIs, fuck blasma and fuck s*licons.

On a serious note, this is probably a hell of a lot better than actual roundstart by the reasons the op listed. Lemme atleast get my choco coin and my shades before you braaap on me.

**Comment by boy2mantwicethefam** [comment]
>that much threat requirement for a mid-round antag
>that low of a weight for a mid-round antag
Chances are the threat will, most of the time, be used for something else instead of malf. Lower the threat cost and maybe nudge the weight by +1 and you're set

**Comment by ValkyrieSkies** [comment]
Heavily discourages making more than one AI ever, not sure I'm a fan of this.

Does Malf death still end the round?

**Comment by Irradiation** [comment]
Clearly the nuclear option is to make it like Newcops
>name = "Nuclear Assault"
	role_category = /datum/role/nuclear_operative
	my_fac = /datum/faction/syndicate/nuke_op/
	enemy_jobs = list("AI", "Cyborg", "Security Officer", "Warden","Detective","Head of Security", "Captain")
	required_enemies = list(3,3,3,3,3,2,1,1,0,0)
	required_candidates = 5
	weight = 5
	cost = 35
	requirements = list(90,90,90,80,60,40,30,20,10,10)
	var/operative_cap = list(2,2,3,3,4,5,5,5,5,5)

**Comment by Kurfursten** [comment]
I actually don't think that [35 threat won't ever be present midround] is the case. 30 threat is getting regularly spent on spaceblob as we can see.

**Comment by Irradiation** [comment]
>Heavily discourages making more than one AI ever, not sure I'm a fan of this.

Notice how Bleb rolls often and look at the aforementioned comparison with Newcops. This will roll very, VERY rarely.

>Does Malf death still end the round?

I believe so.

**Comment by boy2mantwicethefam** [comment]
@Kurfursten Mid-round blob has a weight of 5 and a cost of 15 threat
Malf AI has a weight of 1 and a cost of 35 threat
That 30 threat might get spent on roundstart blob, but that's roundstart when the amount of threat is filled up

**Comment by Irradiation** [comment]
That sounds more like a Bleb problem than a MALF problem, seeing how midround Blebs have a super high chance to roll.

**Comment by Kurfursten** [comment]
Let me put this another way, as someone who watches the threatlog rise and fall often, it is very common to see more than 30 threat laying around in midround if the mode isn't autotraitor (roundstart). If roundstart autotraitor fires it tends to sap all the threat by continuing to fill up the shift with more tots if possible, but in other game modes there is a lot to spare.

**Comment by ValkyrieSkies** [comment]
The round ending should be removed if this is to become a thing, it could lead to some very abrupt round ends otherwise.

**Comment by Irradiation** [comment]
I don't think I've ever heard of anybody complaining about MALF ending abruptly, especially considering the standard MALF strategy of killing the crew.

**Comment by Kurfursten** [comment]
I agree with Valkyrie (we should segue to a system that might autocall the shuttle based number of dead or something) - but that's not in the scope of this PR

**Comment by Irradiation** [comment]
What Kurfurst said, basically.

**Comment by boy2mantwicethefam** [comment]
Yes. On blob's defense though they're announced and their spawn location is RNG at the edge of whatever they collide with
But the point is that the malf is very rare and will almost never get rolled. With weight 1 (lowest it can get without not even being considered) and a big cost of 35, malf will be an extremely rare roll. It requires 4 enemy jobs for threat levels up to 60 and there are 9 enemy jobs and they are either Security or people who can usually get to the AI. Plasma flooding has become weak with the addition of inflatable shelters out of every fire alarm.
Malf AIs are far less of a threat than they appear to be, and the only time they can get powerful is when they have silicons and they play their cards right

**Comment by Intigracy** [comment]
Malf should at the least not end the round on death if this is going to happen.
Nothing wrong with pushing other possible changes to later, like changing the victory conditions so a malf that DOESN'T nuke the station doesn't end the round.

**Comment by Kurfursten** [comment]
I do not think it does anymore. Malf died in round today

**Comment by agentofzog2** [comment]
Wish we got traitor AI back instead, being able to let the crew leave gave you a lot more room for gimmicks since you didn't have to go to war with the carbons if you didn't want to.

**Pull request merged**
