### PR TITLE
Tome radials

### PR DESCRIPTION
**Pull request by Allspice**
Talisman radial

To do:
1. Make a radial icon for each talisman type. The current icons were borrowed from the cult 2 talisman icon revamp, so the new types default to '?' icon.
~~2. Sanity to prevent talisman-getting from tomes in your pocket i geuss~~

:cl:
* rscadd: Alt-click tome to make a radial of all talismans in that tome; click one of them to put that in your hand.

### CODE REVIEW

**Comment by DeityLink** [comment]
>Those awful talisman icons I thought we were finally rid of

over my dead body

**Comment by DeityLink** [comment]
I'm ok with this if all this does is placing the talisman in your hand instead of immediately activating it.
Use the talisman's icon and add a thumbnail with the talisman's name when hovering over it

Words are no longer random, which means a talisman for a specific spell will always have the same sprite. Even if the sprite isn't explicit in what the talisman does (intentional) cultists should quickly memorize what drawing corresponds to which spell.

**Comment by bathosbathtime** [comment]
Avoiding bad ui is always blessed

**Comment by DeityLink** [comment]
Mind if I branch off your branch and make you a PR with my suggestions in?

**Comment by jknpj** [comment]
go for it, this looks rather derelict

**Comment by DeityLink** [comment]
oh god what

**Comment by Allspice** [comment]
Fetching from upstream in a certain order made it shit the bed. I guess I'll re-make the PR.

**Pull request closed without merging**
