### PR TITLE
TRAINS

### PR DESCRIPTION
**Pull request by clusterfack**
Why did I do this? Celt said that it needed done one day by someone. I had nothing better to do today.

Adds a few new trains and put their respective stuff in the maps. Pretty straightforward. A move away from bags nonsense.
image

- Touches a lot of files which interact with trains and train objects
- Train rails
- Train cars
- Train locomotives
- Train forks
- Trains running into other trains
- Trains also can have inserters take stuff from the trains and put them on conveyor belts
- Its just like factorio except not

Is this tested? like, at all?
yes. I can't guarantee there are no bugs but after a day of testing I fixed all the bugs I found. See the comments for proof.

Some sprites
thomas
carts

### CODE REVIEW

**Comment by clusterfack** [comment]
Proof

**Comment by Intigracy** [comment]
I'm glad you added a preference for what color trains appear as.

**Comment by Arthurdentist** [comment]
Does this include a steam engine for engineering? What about Train Station?

**Comment by clusterfack** [comment]
We're working on an asteroid that has a number of stations connected by train, we're also thinking about an energy wagon that works like an smes and can be attached to the train

**Comment by Duny-** [comment]
Can't wait to see all the casuals fail to use these trains while I'm steaming around and stopping human harm with my comfy old loco.

**Comment by JustSumBody** [comment]
https://www.youtube.com/watch?v=q2_I0EGhcB4

**Comment by kilozombie** [comment]
Look, honestly-- if TG wasn't jealous yet, they will be now.
Fucking plebs.

**Comment by Kurfursten** [comment]
This is the most elaborate April Fools content I've ever seen

**Comment by PJB3005** [comment]
But, it's not April's fools content?

**Comment by Kurfursten** [comment]
Right, sorry, just "content", I'll edit my post

**Comment by eplgr** [comment]
why
why would you do this to us
why?

**Comment by PJB3005** [comment]
How can somebody *not* like trains?

**Comment by Probe1** [comment]
Finally we're going to have parity with every other server and will have trains.

**Comment by Aurx** [comment]
Not atomic.  
I want my nuclear powered unshielded murdertrains damnit, add atomic trains!

**Comment by DrCelt** [comment]
Hold on a gosh darn second these aren't trains

**Comment by clusterfack** [comment]
SAYS THE MAN WHO ADDED PLANES, WHERE ARE MY PLANES CELT

**Comment by Ephx1** [comment]
Finally, Planes, Trains, and Automobiles.

**Comment by Intigracy** [comment]
Choo choo.

**Comment by adu6oo** [comment]
i have been informed i got pranked and i am going to have to kill cluster now

**Comment by Kammerjunk** [comment]
💯 %

**Comment by ihadtoregisterforthis** [comment]
Well April fool's is done, where's the revert?

**Comment by Exxion** [comment]
In your preferences menu

**Comment by SarahJohnson489** [comment]
Revert when? It's the 2nd.

**Comment by PJB3005** [comment]
I'm gonna shoot everybody calling for a revert holy shit.

**Comment by Riekland** [comment]
🤔

**Comment by Skullyton** [comment]
but why

**Pull request merged**
