### PR TITLE
gradual blindness

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
nearsighted gene now adds some "nearsightedness"
welding goggles now add some "nearsightedness"
eye damage now adds some "nearsightedness"
prescription glasses remove some, so they now have an effect that isn't just based on genetics
removes eyeblur when your eyes are hurt
applies an overlay lowering your vision range, scaling with "nearsightedness"

image

image

image

image

## Why it's good
i was shocked to see this almost compile, the only thing i got wrong on the first try was the inbuilt `Ceiling()` proc

## Changelog

:cl:
 * rscadd: eye damage, genetics and eyewear can now affect your vision range
 * tweak: prescription goggles now help you see better if your eyes are damaged
 * imageadd: more shorter vision overlays

### CODE REVIEW

**Comment by gurfan** [comment]
>rscadd: eye damage, genetics and eyewear can now affect your vision range
ehhhhhhhhhhhhhhhhhh

**Comment by pedr69** [comment]
if you think it's worded poorly, please suggest improvements
upon rereading, i think the `can` should be removed but i doub't that's what caught your eye

also, what the fuck is an unathi space suit

**Comment by Servalfang** [comment]
What about hardsuits? Do they hurt your vision? They provide welding protection, so...

**Comment by pedr69** [comment]
only unathi ones do at the moment
adding slight vision loss to hardsuit helmets would be trivial, just a `nearsighted_modifier = 1` on the parent hardsuit helmet
but i feel that the rigbaby cabal would go nuts
should probably do that in another PR

**Comment by tinysaturn** [comment]
Should prescription glasses really be able to undo the welding masks' penalty?

**Comment by BomberBro** [comment]
Does this remove cumvision entirely?

**Comment by pedr69** [comment]
removes permanent cumvision if your eyes are hurt

you still get temporary cum if you weld without glasses, drink gloral, get plasma in your eyes, have braindamage etc

**Comment by boy2mantwicethefam** [comment]
Please test if you can still interact with objects next to you.

**Comment by pedr69** [comment]
please elaborate?
you can still pick stuff up that's in the dark area, and you can still right click the darkness to see what's there if that's what you mean
image

**Comment by boy2mantwicethefam** [comment]
That's good then

**Comment by Eneocho** [comment]
Does the farsighted gene decrease your "nearsightedness" value?

**Comment by pedr69** [comment]
farsighted makes the overlay stretch over the entire screen
so it doesn't cover the entire tile but just one portion
image
otherwise it doesn't interact at all, except that you can't have both farsighted and nearsighted genes active

**Comment by Eneocho** [comment]
I'd much rather for Farsight to counteract "nearsightedness" (the value), so you can still see at normal values with farsight+welding goggles, for example. Your eyesight is so good you can still see like a normal guy would even if wearing protective eyewear.

**Comment by pedr69** [comment]
the mice make nervegas if you equip them on your hat
```
[19:11:57]ACCESS: Logout: *no key*/(plague mouse) <span title='plague mouse'>(A)</span> (Cargo Office - 252,217,1)
[19:11:57]ACCESS: Login: HerrytheafroHeadcrab/(plague mouse) <span title='plague mouse'>(A)</span> from [NOPE] || BYOND v514
[19:11:59]DEBUG: Runtime in <b>standard_damage_overlay_updates.dm</b>, line <b>128</b>: <b>undefined variable /obj/item/weapon/holder/animal/mouse/var/nearsighted_modifier</b> <a href='?_src_=holder;viewruntime=[0x21033e63]'>[view]</a>
```

**Comment by DeityLink** [comment]
A consequence of this PR is that the "prescription" var on glasses does strictly nothing now, as even if it is set to 0, the nearsighted_modifier's bonuses will be applied. I'll remove the var entirely so other coders aren't tricked into thinking it does something.

**Pull request merged**
