### PR TITLE
pulse demon bugfixing

### LINKED ISSUE #32219: Pulse demons collide with people on harm intent
(WEB REPORT BY: mastercasual REMOTE: 206.221.180.138:7777)
# Revision
c5f22132166d1de934f94537484f696ae8e628b5

# Description
Pulse demons will be shoved back if someone is in harm intent and they are under the tile
# Steps to Reproduce
run into a pulse demon
# What you Expected
it slide under me
# What Actually Happened
it kept getting pushed BACK

### LINKED ISSUE #32572: powercreep neuters pulse demon
(WEB REPORT BY: jeremopolis REMOTE: 206.221.180.138:7777)
# Revision
532018a78fb4a500f989fbccaf46683302a3a73e

# Description
a pulse demon entering a tile with powercreep (maybe just uncovered tile not sure) covers creep with vines, creep can no longer move, enter apcs, do anything.
# Steps to Reproduce
be pulse demon enter tile with vine
# What you Expected
for the vines to wear off or not be essentially death, as you can still wire warp but not enter any devices.
# What Actually Happened
made me unable to act

### LINKED ISSUE #32693: Negative power as pulse demon
(WEB REPORT BY: uchla REMOTE: 206.221.180.138:7777)
# Revision
c598c167831449d3d9c694e73cdfed32dc0f1445

# Description
when upgrading my cable jump I went into the negatives and was unable to even turn on my power draining ability to regain power
# Steps to Reproduce
I'm not sure it's never happened before when I upgraded cable hop?
# What you Expected
to have a better cable hop
# What Actually Happened
no power forever

### PR DESCRIPTION
**Pull request by pedr69**
]bugfix]

## What this does
closes #32693 
closes #32572 
closes #32219 

not sure if merging this and the other PR would make github gas, since they both touch the same lines

## Why it's good
reduces the number of active issues from 2933 to 2930

## Changelog
 * bugfix: pulse demons no longer collide with people
 * bugfix: pulse demons can no longer get negative power
 * bugfix: pulse demons no longer die to powercreep

### CODE REVIEW

**Comment by pedr69** [comment]
might fix #32389 too?
i'm not sure how to spawn in kudzu to test

**Comment by adacovsk** [comment]
> might fix #32389 too? i'm not sure how to spawn in kudzu to test

go to spawn under admin panel, then type in kudzu and look for the vine

**Comment by Eneocho** [comment]
>pulse demons no longer collide with people

The end of an era.

**Comment by pedr69** [comment]
>go to spawn under admin panel, then type in kudzu and look for the vine

it's actually called /obj/effect/plantsegment
regarding vine grabbing, did you know that having active magboots prevent you from being grabbed?
and that vine_protected() only applies to humanoids

**Comment by Eneocho** [comment]
You can also spawn a kudzu seed, VV it to give it maturation and production of 1 and plant, it should turn into a vine hellscape within a minute.

**Comment by Kurfursten** [comment]
It would be a good thing to move vine_protected() up another level, however that is another bugfix request and not required for this to merge

**Pull request merged**
