### PR TITLE
Ports radial menu improvements, adds radial menu to the Bunsen Burner

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Ports the improvements to radial menus from https://github.com/tgstation/tgstation/pull/40350
Namely, prevents a radial menu from being opened twice
Adds an event handler so you can, for example, not have the radial menu hang around forever until closed manually

Plus: My coder art that TG should steal, and I also added a semitransparent square to the center of the reticle so the radial menu can be easily closed without pixelsniping
onofflockunlock1

:cl:
 * rscadd: Added a simple radial menu to the Bunsen Burner altclick.

### CODE REVIEW

**Comment by DeityLink** [comment]
AHHHHHHHHHHHHHH

I already made some of those changes myself in my next datums PR

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
np friend :)

**Comment by DeityLink** [comment]
So hold on, does this mean the menu automatically closes after two seconds? or only if you moved away?

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
The radial menu allows for an event that gets checked every 2 seconds, which can be any proc

For this example I made a new bunsen burner proc that just checks adjacency and incapacitated but the proc could be anything.

**Comment by DeityLink** [comment]
Hey, in that case you could have a check for the anchor's location, and close (or move maybe) the menu if it got displaced.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I had a bit of fun making new icons
dreammaker_2018-09-28_03-08-58
dreamseeker_2018-09-28_03-07-23
None of them are used but they'll be useful in the future

**Pull request merged**
