### PR TITLE
Zombies created by the Stubborn Brain virus syndrome are now player-controlled.

### PR DESCRIPTION
**Pull request by Irradiation**
Fixes [#22384]

Like it says on the tin. While the syndrome is technically possible to get in random virus dishes, the "main" way to get this syndrome is by being a Traitor and purchasing it from the uplink at an exorbitant cost (12 TC if Virologist, 20 TC if not). 

If you're going to spend that much TCs on a virus syndrome, it might as well not be a complete joke. This is also taking into account the fact that viruses getting cured is a crapshoot (depends on who's in medbay/virology). 

In addition, the syndrome "threat level" is now at "DEADLY", previously "ANNOYING".
    -This will make it so maintenance mice won't have the zombie syndrome at all.
    -It'll properly reflect how dangerous player-controlled zombies are.

[balance][tweak]

:cl:
 * tweak: The Stubborn Brain ("Zombie Virus") stage 4 virus syndrome will now create player-controlled zombies, as opposed to making NPC zombies.
 * tweak: Said syndrome will no longer occur in maintenance mice viruses.

### CODE REVIEW

**Comment by Gazathor** [comment]
I for one welcome our new zombie overlords

**Comment by boy2mantwicethefam** [comment]
Is it possible to have the resulting zombie sapiency depend on the strength of the symptom? That way virologists could tweak whether they'd want a thinking undead army or a brainless one

**Comment by cloutcode** [comment]
Can the zombies get cured by chaplains like wizard zombies

**Comment by Irradiation** [comment]
Wizard zombies are created in the same way as this modification, so yes, Chaplains should be able to "fix" zombies.

**Comment by gurfan** [comment]
Do the zombies created by the virus have a "master" like wizard zombies do?

**Comment by Irradiation** [comment]
Nein, no gods, no masters. Do whatever the fuck you want. I'm not exactly sure I'd go around deciding who's the "master" in a simple way. What if you got infected by a random dude who passed around? How're you supposed to instinctively know that XYZ is your master?

**Comment by SonixApache** [comment]
Did you fix all the issues with the zombies and zombification or did you just tack on some code?

**Comment by Irradiation** [comment]
As the code changes imply, I've only "tacked on some code". That said, fixing the (many) issues that zombies have is definitely a future prospect.

**Comment by ShiftyRail** [comment]
Make sure that whatever rules zombies have is properly announced to player-controlled zombies.
As far as I know :

- they're free to antag or not
- but they must always listen to whomever created them (a wizard, virologist, etc)

You can also create player-controlled zombies by getting a zombie on your master trainer belt, and I believe this too should be tracked and announced to the player.

**Comment by SonixApache** [comment]
fix issues with zombies FIRST, then tack on code
instead of amplifying the prevalence of extremely broken features

**Comment by Tokanova** [comment]
merge it and get people to see how fucked up zombies are to create more discussion of how they want issues with zombies fixed to increase the hype for the coder that does fix it :)

**Comment by SonixApache** [comment]
alternatively, don't merge it until someone unfucks the zombie mind transfer code so we don't fill the rsc with even *more* broken shitcode

**Comment by Irradiation** [comment]
I've been testing zombie code so far on my own and with players on the serb and I can't say I've been experiencing the issues that I've found in regards to mind-transfer so far.

(Still working on assorted Zombie QOL changes and fixes, though).

**Comment by SonixApache** [comment]
🤔

**Pull request merged**
