### PR TITLE
Box hotfix

### PR DESCRIPTION
**Pull request by CptWad**
image

I got called a shitter for this

### CODE REVIEW

**Comment by MadmanMartian** [comment]
what was wrong?

**Comment by CptWad** [comment]
unknown

**Comment by MadmanMartian** [comment]
To be fair, that's where they were originally. The windows have been pushed down somewhat

**Comment by CptWad** [comment]
that doesn't stop me from being blamed
shoulda seen it though
tile thing is weird. For whatever reason the mapper and ingame results are different

**Comment by MadmanMartian** [comment]
something's probably fucking with the dir after gamestart

**Comment by SonixApache** [comment]
did you really move the firelocks so that if there's a plasmafire the fire just goes around the firelocks through the windows instead of keeping the walled-off double airlock safe

**Pull request merged**
