### PR TITLE
Ports colorful reagent from TG.

### PR DESCRIPTION
**Pull request by Allspice**
Mescaline psilocybin amatoxin. What could possibly go wrong.

Colorful reagent

:cl: 
* rscadd: Ports colorful reagent from TG, mescaline psilocybin amatoxin.

### CODE REVIEW

**Comment by Allspice** [comment]
yep

**Comment by Irradiation** [comment]
Overdose on colorful juice making you druggy WHEN?

**Comment by Allspice** [comment]
Right, one thing I almost forgot

colorful reagent

The stuff turns on proper rainbow mode until lighting updates (a light is moved or whatever). Hmm.

**Comment by Exxion** [comment]
Holy fuck I'm 99% sure that `reaction_obj()` is getting called on the fucking lighting overlays
This is in no way your fault but it's kind of a big problem

**Comment by AutismSpider** [comment]
does this work on cyborgs?

**Comment by Allspice** [comment]
yes

**Comment by Ratvar** [comment]
A way to permanently mark stealthy changelings/vampires/traitors/wizards? Yey

**Comment by DamianX** [comment]
I thought paint already served a similar purpose?

**Comment by Allspice** [comment]
reagent is a bit more "vibrant," and importantly, paint does not appear to color mobs.

**Comment by DamianX** [comment]
Sure, but it seems like we don't need paint anymore if this one does everything paint does and more?

**Comment by Allspice** [comment]
Paint lets you choose your preferred colour instead of faffing with RNG, and can be ordered from cargo, $10 for 7*150u of the stuff across all seven colours.

**Comment by DamianX** [comment]
okay then!

**Comment by DamianX** [comment]
🤔 Do we want a way to undo the effects of this?

**Comment by Irradiation** [comment]
Yes we fucking want a way to undo this. I propose spess cleaner & bleach.

**Comment by DamianX** [comment]
What about turfs?

**Comment by Allspice** [comment]
The first line in the commit is in reation_turfs. It removes the new colour.

**Comment by Irradiation** [comment]
Unless I'm wrong, you just need 0.2u to start making your very own Rainbow Road, right? KARTS FOR EVERYBODY WHEN?

**Pull request merged**
