### PR TITLE
Small fixes for Deff and addition of the pressure regulator to fix mass drivers.

### PR DESCRIPTION
**Pull request by Duny-**
Fixed cargo shuttle buttons opening the wrong door.
Fixes https://github.com/vgstation-coders/vgstation13/issues/15430

Fixed Ian spawning as christmas Ian. It's fucking september.
Fixes https://github.com/vgstation-coders/vgstation13/issues/15099

The salvage shuttle's inner airlocks now start unbolted.
Resolves https://github.com/vgstation-coders/vgstation13/issues/15059

Now for starting to fix https://github.com/vgstation-coders/vgstation13/issues/14675 and https://github.com/vgstation-coders/vgstation13/issues/14354:
- Added the pressure regulator, an embedded controller used only to depressurize or pressurize a room on demand using vents and an airlock sensor (Has only 3 buttons: Pressurize, Depressurize and Abort; can't be linked to airlocks). Can be built using an airlock controller frame and an Embedded Controller Board (Pressure Regulator).

A shame the frame is not named embedded controller and not airlock controller frame even though the circuit boards are properly named. Kinda dumb to build something that doesn't control airlock with an "airlock controller frame". Not sure if changing that will break anything so I didn't do it.

- The chapel's mass driver now has a pressure regulator, with its own air canister and a passive gate linked to distro (already set up correctly) both situated in the crematorium, allowing the chaplain to quickly depressurize the room before activating the mass driver/re-pressurize it afterwards and therefore avoid ZAS shenanigans. 

The mass driver's room has been outfitted with a large dual port vent for this, sucks from canister/distro and towards waste.

Adding some magical plastic flaps which somehow don't let air through even though they're just plastic flaps is lazy and pretty much the same as just making floors magically unsimulated near every airlock and pretending space doesn't exist to not have to learn how to map proper airlocks and make sure the playerbase never learns how pressure differences work; so I went ahead and fixed the problem in a way befitting a space station.

The airlock controller was too complicated and misleading for the simple task of depressurizing the mass driver's room before use, and just adding a vent would have made waiting for re-pressurization a nightmare similar to when we first switched to baycode and had poorly mapped airlocks which took 5 whole minutes to depressurize. So I added the pressure regulator in order to provide a simpler UI and retain the fast depressurization/re-pressurization. If I could byond code for shit I probably would have automated the process but this is good enough.

image
image

If that solution pleases our chaplains I will do the same on the other maps.

### CODE REVIEW

**Comment by Kurfursten** [comment]
The Christmas Ian thing was an 'easter egg' Probe left in on purpose. Not that I object.

Are you thinking about remapping Medbay? Deff's long narrow medbay is considered to be one of the worst, and I know it's a problem you inherited rather than created. Probe's "fix" was a step up but never got merged and also still suffered from long medbay. Fixing it will require an unfortunate amount of work, and it's far from a quick fix. I've been toying with some designs in the six months since his PR, nothing serious, but I wanted to hear if you had any plans for working on it.

**Comment by Duny-** [comment]
I think christmas Ian should only be around in december. Not like I have strong feelings about it.

Honestly fixing deff's medbay is so much work I don't think it's worth the trouble. I tried before and just gave up because of the sheer amount of things you have to move around while maintaining a semblance of coherence in deff's design. It _works_, it's shit, but it _works_ and the horrible torture that fixing it entails doesn't sound worth it just to make it work better.
That said if you can whip out a magic wand and make medbay less shitty while retaining chem's position next to rnd, a way from and to science in genetics, a way to and from the morgue from the hallway, a way into maintenance that doesn't require any special access, two surgery tables and paramedics near cloning all while not moving anything towards toxins testing (though testing could probably be moved away actually) and without completely annihilating everything to the west of medbay I would be pleased to see what you have in mind.
Removing the fucking mancrowave would already be a step in the right direction and that I am considering doing.

**Comment by Kurfursten** [comment]
I had a design that matches that description but no genetics-R&D connection. Instead, it involves swapping telescience and toxins (which is super painful because it involves swapping the direction of a lot of equipment in the toxins room) and combining paramedics office with telescience because they're the same job anyway. The goal is to make all of medbay served from a central area to reduce the walking and maximize open space. On the plus side it reduces a lot of clunkiness and preserves the morgue, reception, chemistry, and morgue locations which you seem very attached to.

untitled

It wouldn't be easy - no good fix will be. I know better than anyone because like I said, I've tinkered on it for six months and obviously and progress I made is way out of date with minor map updates. So I hope you understand I sympathize with how massive an undertaking this much remapping would be, and why  a project this large needs to be planned out before it's actually mapped.

**Comment by Duny-** [comment]
I hadn't thought of merging paramedics and telesci, it does make sense on top of making paramedics relevant again after Rei decided to make them completely useless by forcing the addition of a crew monitoring computer for public medbay usage on every map. I'm going to take a look at just how painful what you're proposing would be, might actually do it, yell at everyone not to touch at deff until I'm done and hope I don't end up killing myself before it's over.

**Comment by BurntDevil** [comment]
Anything that fixes that god awful ZAS when trying to work the mass driver is S-rank in my book.

**Comment by N3X15** [comment]
Can I merge this first before you embark on the proposed layout change?

**Comment by Duny-** [comment]
Yes

**Pull request merged**
