### PR TITLE
Adds (silver) pears to botany

### PR DESCRIPTION
**Pull request by Irradiation**
Because we apparently didn't have a plant for silver and also pears.

Credits goes to :
TheBimmer231 for the pear sprites
RealestEstate for growing plant sprites
Blithering for the seed pack sprites

EDIT: deleted Hydroponics.dmi from the PR. It was added to my initial commit by accident.

capture

[content][sprites]

:cl:
 * rscadd: Added (Silver) pears to botany.

### CODE REVIEW

**Comment by DrSnips** [comment]
What are they used in or for?

**Comment by Irradiation** [comment]
Currently nothing, they occupy the same purpose as golden apples, which is to say, getting gold.

**Comment by DrSnips** [comment]
The silver ones are understandable but the basic ones feel lacking. Don't get me wrong I'd love to have them I'd just like to know if they have any plans yet.

**Comment by Irradiation** [comment]
No plans for now, like I said.

**Comment by SonixApache** [comment]
we have pear flavored suckers, that's good enough

**Comment by codeungabunga** [comment]
More plants is good.

I also suggest ignoring the issue where this PR makes `hydroponics.dmi` actually editable in dreammaker by removing the excess sprites added by a 3rd party tool. The sprites can be later add back in once they are actually being used, many other codebases have those sprites available.

**Comment by Kurfursten** [comment]
More plants with no food items is bad though
We have so many plants that are seriously underutilized in recipes and end up being a grown fruit

At least if they were pickles instead of pears we'd finally have a way to make relish.

**Comment by codeungabunga** [comment]
There's many crayon colors that have no other purpose but being a color, they all have the same purpose too. If I added a new crayon color, would it be color creep since that new color doesn't have a new unique use? It wouldn't because not everything needs a unique use.

**Comment by Kurfursten** [comment]
We've got 6 crayon colors in the box (plus 2 special crayons). We've got 40 seeds in the vendor (plus 19 mutants, 8 vox, 7 xenoarch, and infinite exotic).

The real question is if when you post it counts as stupidity creep.

**Comment by codeungabunga** [comment]
I recommend consulting github TOS if you intend on using ad hominem on the site, it would be a shame to lose coders over silly tantrums.

**Comment by Kurfursten** [comment]
You're confused, ad hominem attacks the character of someone to undermine their argument. It would be ad hominem if I said
>You are stupid, therefore you are wrong

My logical flow is the opposite
>You've made a comparison that makes no sense. Crayons too would be bloated if we had 70+ colors. Making that comparison makes you stupid. Also, let me style on you by making a mockery of your "color creep".

Although, just to be clear here, I find your threat to call the feelings police so laughable that I will make an explicitly ad hominem argument as well:

>You are so much of an outsider to 4chan culture that you have no place here.

**Comment by codeungabunga** [comment]
Friend, I do not care for your conduct, I just don't want you to self destruct over what is in essence a new color.

**Comment by boy2mantwicethefam** [comment]
hahaha how is fruit sprite overdose real just make a second dmi file

**Comment by SonixApache** [comment]
purifying one of the fabled 13 cursed .dmi files would be good, though I'm not sure how hard splitting off the sprite files would be codewise.

**Comment by bathosbathtime** [comment]
It serves the purpose of giving botany access to silver, I do believe that justifies it being in the code well enough.

**Comment by Kurfursten** [comment]
Sure, as long as there's a suitable reason for botanists to grow pears other than as an intermediary to silver pears. The more unique the better, we already have a whole stack of pies.

Baked pear, pear puree, pear upside down cake, pear salad, pickled pears and bulgogi are all ideas. I can donate a couple codersprites too for the cause.

**Comment by SonixApache** [comment]
make a (purges .dmi) PR, get that merged first, then merge this

**Comment by Kurfursten** [comment]
As promised, my codersprites where my mouth is. Here's 2 sprites for pear bulgogi and a jar of pickled pears.

sprites

**Comment by Irradiation** [comment]
I am a lazy, gitlet & non-clever man and thus I will use the nuclear option to fix this whole hydroponics.dmi thing whilst adding the recipe for Kurfurst's food.

**Pull request closed without merging**
