### PR TITLE
Flashbangpowder revert changelog

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Oldchangelogs it is #22908

### CODE REVIEW

**Comment by bathosbathtime** [comment]
For what purpose would you attribute the change to another person

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
So the removal entry would be right under the addition entry

**Comment by SonixApache** [comment]
I mean better would be to just remove it from the changelog tbh

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I thought the same considering it was only up for 8 hours anyways but whatever

**Comment by kilozombie** [comment]
@Intigracy @I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE 
Just so you know this triumvirate changelog fuckery screwed up changelogs for my PR https://github.com/vgstation-coders/vgstation13/pull/22859 and https://github.com/vgstation-coders/vgstation13/pull/22852 and https://github.com/vgstation-coders/vgstation13/pull/22861 because none of them show up ingame at all
Every PR after this one was merged has had broken changelogs, it seems.

broken

**Pull request merged**
