### PR TITLE
Fuckup boots

### PR DESCRIPTION
**Pull request by Allspice**
what could possibly go wrong

:cl:
* rscadd: Add some "magboots" to the wizard spellbook. Two steps every three seconds, but breach where you walk.

Sounds and sprites courtesy of @RealestEstate (same for blindingspeed sprite since I forgot last time)

### CODE REVIEW

**Comment by ancientpower** [comment]
based

**Comment by BomberBro** [comment]
it's gonna be cancer to play against but goddamn I want it based on the name alone

**Comment by boy2mantwicethefam** [comment]
Those aren't magboots, they'd be pretty more rad if it was a toggleable action otherwise it's just wizard shoes that are annoying to handle cause they offer a permanent slowdo-yeah wait nevermind take blink and you're good to go, fuck me I love it

**Comment by Kurfursten** [comment]
I wanted the Manual Breathing spell more than this

**Comment by Probe1** [comment]
That sounds awful and instantly round destroying.

**Comment by robosperg** [comment]
still less gunky than dpush

**Comment by ShiftyRail** [comment]
Can see the "downside" being negated in a variety of ways, including

- crawling
- buddy-dragging
- chair-sliding
- janicart or any vehicle
- mechs

Granted a wizard isn't usually going to be found doing most of these but that's things to remember.

**Pull request merged**
