### PR TITLE
Glare/hypno now requires you to look the victim in the eyes

### PR DESCRIPTION
**Pull request by ShiftyRail**
See title.
The reasoning is simple : glare is a (very powerful) AoE stun. Maybe it would be better if you actually needed to look the vampire in the eye before it stunned you.
It also makes running away like crazy when you see a masked figure in maint a slighly more viable choice.

Glare as a range of 3 tiles, but people further away than 1 tile are barely affected by the stun.

[balance]

:cl:
- tweak: Vampire glare and hypnotise spells will no longer work if your victim is facing away from you.

### CODE REVIEW

**Comment by Accipitermaris** [comment]
I support nerfing glare BUT the direction ones sprite is facing is really really finicky. I don't even mean *spin either

I think it would be better if eye prot protected you in [insert reasonable balance capacity here] or if it was a straight up "melee" spell

**Comment by ShiftyRail** [comment]
I feed someone with gyro and tried to glare them, it worked relatively well (the spell doesn't go on cooldown if you "miss"). 

Spin is a bit faster, but out of the 4 direction, 3 of them are "valid".
By statistical arguments, if you spam glare while they spam "*spin", you'll hit them 75% of the time.
I made a mob that emote "*spin" every two seconds and I could glare him easily.

Using CTRL+OPP_DIR would be (in pure theory, as i can't test it, unlike the other two) much better at evading a vampire than spamming the `*spin` emote.

**Comment by SonixApache** [comment]
yes, let's make directionality matter, but only for this one super specific instance

what the fuck dude

**Comment by ShiftyRail** [comment]
"It didn't matter until now so it should never matter"

I don't understand this

**Comment by boy2mantwicethefam** [comment]
But vampires don't have many stun options until they get screech later
Vampire whiffs a 3 minute cooldown area stun (that requires the person to be close enough to the vampire) because they're running away from the vampire

**Comment by ShiftyRail** [comment]
>Vampire whiffs a 3 minute cooldown area stun

> (the spell doesn't go on cooldown if you "miss").

Please read before commenting

**Comment by boy2mantwicethefam** [comment]
That's hypnotise you dork
>glare just returns false if there is no one in the area

What the fuck?

**Comment by ShiftyRail** [comment]
Hypnotise doesn't go on cooldown either retard
I fucking know how these spells work. I coded them.

>glare just returns false if there is no one in the area

Like the old glare that'd notify you if they were no targets available...

**Comment by boy2mantwicethefam** [comment]
I know hypnotise doesn't go on cooldown moron, but I didn't know glare was babyproofed so if there wasn't any nearby target it didn't work

**Comment by ghost** [comment]
I hope you'll never be in a position of authority on any game design decisions.

**Comment by ShiftyRail** [comment]
>I hope you'll never be in a position of authority on any game design decisions.

That's fair and I don't intent to work in that field, but what's the motivation behind this comment

**Comment by ghost** [comment]
It's a joke because you're already a collaborator and it's too late.

**Comment by SonixApache** [comment]
Directionality mattering has been discussed a few times, but it's really just silly unintuitive shit.
If you want to rework everything to work with directionality (most import examples being vision and lighting) please be my guest, but until that keep it away from the general gameplay.

**Comment by boy2mantwicethefam** [comment]
Directionals are fucky because you can turn around to the opposite direction than the same direction of your target and it will count as if you're in front of them
<-O (target)
<-V (you)

<-O <-V (immune)
<-O V-> (connects)

**Comment by ShiftyRail** [comment]
><-O V-> (connects)

Amazing, didn't thought of that
Can be fixed rather easily though

**Comment by Caboozles** [comment]
The concept is better left in theory. Unless this means the person facing away gets no warning that a glare was attempted. This shouldn’t cuck a vampire.

**Comment by ShiftyRail** [comment]
>Unless this means the person facing away gets no warning that a glare was attempted. This shouldn’t cuck a vampire.

They aren't alerted. Glare explicitly tells you it couldn't find a target ; it's not cast nor does it costs you blood.

**Comment by Caboozles** [comment]
Then I don’t see a problem with it as long as it is only for those running directly away.

**Comment by ShiftyRail** [comment]
And that's done, it works now.

**Comment by Caboozles** [comment]
Could just give eyesight protection similar to a flashbang.

**Comment by ShiftyRail** [comment]
Maybe it's not the right way about it

**Comment by ShiftyRail** [comment]
>Directionality mattering has been discussed a few times, but it's really just silly unintuitive shit.
If you want to rework everything to work with directionality (most import examples being vision and lighting) please be my guest, but until that keep it away from the general gameplay.

That's a very silly way to present it.
Directionality in vision & lighting (aka vision cones and lighting cones) would be much harder to implement for once and would be pretty much against QoL.
They are vastly different gameplay elements from a spell anyways. I'd go as far as saying that it's completely unrelated. In most third-person games you can see around your character but directionality matters to an extent.

It's not really that intuitive if you can add a description at it. 
I just wanted to make it so running the opposite direction of a vampire or a suspected vampire actually works. Because right now it doesn't do jack shit to turn around.

Since people didn't like glare, that was how I thought it could be solved. I can understand it being extremely unpractical (and if people judge it too much of a nerf, then let's close it and leave it at that). However, "you're implanting directionality here so you should implement it in [completely unrelated gameplay elements]" is something that makes me go :thinking:

**Pull request closed without merging**
