### PR TITLE
Makes Station Rotate

### PR DESCRIPTION
**Pull request by clusterfack**
This is a brand new feature for people with parallax, through transform matrices we can make the entire station appear to rotate in space by rotating the parallax behind them.

How does it work
- We use a looping animate call in 2 parts which uses a cos/sin transform to rotation circularly
- Clever use of transform matrices allow us to desync and realign with the station when entering and leaving zlevel 1
- Adds possibility for cuhrazy shit to happen like station spinning out of control
- Also adds realistic sun simulation, lighting up one side of the station

### CODE REVIEW

**Comment by TheFriggenSawbones** [comment]
can we use this to simulate motion sickness, maybe make it a thing if you run for too long

**Comment by Probe1** [comment]
g-man_gmod

**Comment by Probe1** [comment]
@clusterfack Did you take into account the coriolis effect?  Too long have we gotten away with casually throwing objects and seeing them travel in a straight path to the observer.

**Comment by unusualcrow** [comment]
holy shit this is groundbreaking
just take a month off man you've been working too hard

**Comment by clusterfack** [comment]
Yes, which is why we've added a zone tracking system along with a coriolis_bresenham_step(), to determine the quantity and magnitude of the coriolis effect from the center of mass of the station, (calculated during roundstart initilization and modified periodication when mass zones merge).

**Comment by ihadtoregisterforthis** [comment]
Does the sun stay stationary then? 
The coding looks very very automated, surely nothing can go gamebreakingly wrong

**Comment by Kurfursten** [comment]
Now I understand

When people were asking for "map rotation" all these years, THIS is what they meant

**Comment by SangriaMonkey** [comment]
:b:ruh

**Comment by yclatious** [comment]
What's up with the Phoron?

**Comment by Kurfursten** [comment]
That's just a visual artifact in the change viewer caused by rebasing from Bay where he's porting station rotation from. Don't worry about it.

**Comment by kernikov** [comment]
2FAR

**Comment by yclatious** [comment]
So, plasma is still plasma and isn't replaced by phoron bull? Sounds good to me then, sorry to ask.

**Comment by NigglyWiggly** [comment]
**YOU DIDN'T CHANGE THE NAME OF THE PLASMA TEA DRINK ITSELF YOU ONLY CHANGED THE REAGENT YOU FUCKED IT ALL UP**

**Comment by TheFriggenSawbones** [comment]
revert please

**Comment by Kurfursten** [comment]
Fully Fooled

**Comment by kernikov** [comment]
>phoron mineral deposits are wall sprites
>phoron ore is literally the words "no sprite"
>cannot create phoron bars
>cannot create phoron glass
>cannot create reinforced phoron glass
>the ore doesn't have a value for cash pay outs

Literally KYS

**Pull request merged**
