### PR TITLE
Defibrillators no longer have a 25% chance to cause spicy heart damage upon use.

### PR DESCRIPTION
**Pull request by Irradiation**
You know, for all the yelling medbay gets about "muh kill and clone" and "speedcloning is gay", the alternatives sure feel like shit and punish you for using them.

Currently, defibs have a 25% chance to inflict 5 heart damage every time you shock somebody valid for revival. I sure hope you like shocking a guy 3 times because he wouldn't get back into his body fast enough, because now eat shit and spend some quality time in surgery with him. I sure _adore_ not picking speedcloning.

:cl:
 *tweak: Defibrillators no longer have a chance to cause heart damage when attempting to revive a corpse.

### CODE REVIEW

**Comment by Irradiation** [comment]
I dunno, even with having to wait for the clone to come out well-done to dodge heart damage, I'm fairly certain that going full hardcore mode to bring a guy back into defib range _with unupgraded tools_ would still be an option that nobody wishes to/has the time to take. But that's a question for another day.

**Comment by Killette2** [comment]
Sounds like the issue here is cloning being too good rather than defibs being too bad. Cloning is currently no work all reward, when those two should be more proportional

**Comment by Pathid** [comment]
Med system shallow and unforgiving at the same time -> medical brain drain -> need for simple cloning continues -> med system doesn't get fixed -> repeat.

**Comment by Kammerjunk** [comment]
@Killette2 no, the issue here is definitely defibs being bad. This makes cloning better by making defibbing so much worse. The source is defifbbing.

**Comment by iFlashYou** [comment]
And remove harmdrag while you at it

**Comment by ShiftyRail** [comment]
@iFlashYou How about making it so walk intent does not cause harmdrag ?

**Comment by Irradiation** [comment]
How about teaching people to shove corpses in lockers, chairs, bodybags or whatever instead? Or are we just going to assume that the general playbase is too dumb to understand why harmdragging is forcing their friend into the clonezone?

**Comment by Pathid** [comment]
You just think it's as simple as ignorance. With cloning being as consequence-free as it is most of the time, there's a mentality that they're actually doing the guy a favor by dragging him into raw hamburger land. And I can't really think of a practical counter-argument to that.

**Comment by iFlashYou** [comment]
People just dont care, they want to move the dead person asap to medbay. They dont have to fix the damage later, so they think their job is done by just harmdragging the dead through the entire station.

**Comment by Pathid** [comment]
>dead people

Or living people for that matter. I see a dude with broken leg, not even in crit, get rapidly dragged to death on the way to medbay. But then he gets speedcloned so what can you do or say at that point?

**Comment by Irradiation** [comment]
Currently, I see a guy with 30 brute, 7 broken bones and ZAS hell 2 rooms over and I propose to my patient the options:
-Kill & clone (sedate them first)
-Spend forever in surgery because I don't have upgraded surgery tools (Thank you, R&D with 4 scientists and plenty of mats)
-Give him enough painkillers and a promise to supply more painkillers to let him ignore the broken bones.

Guess which option the patient chooses?

**Comment by Pathid** [comment]
That's exactly the point. With kill and clone being superior anyway, drag damage is just speeding things along. Everything else is RP. Easy cloning is a self-perpetuating system.

**Comment by Killette2** [comment]
This is a good time to add that turning pod people into diona was a mistake, and it was great reviving people by injecting their blood into a cloning pod seed

**Comment by iFlashYou** [comment]
Stop, Stop. Pr here is about defib and heart damage and not harmdragging and cloning. Should have not started with my sentence about harmdrag first...

**Comment by jknpj** [comment]
there's only one way to stop the shitposting

**Comment by Killette2** [comment]
By shitmerging of course!

**Pull request merged**
