### PR TITLE
Switch the wonderful wardrobe to a predefined list of possible items.

### PR DESCRIPTION
**Pull request by Allspice**
Also permits bundling objects like suit-and-helmet together, so you're not left with only one or the other.
That said, I also took the lazy way out: Please and thank you spitball 20-30 "fun" and "exciting" options from the currently-existing clothing list.

:cl:
* tweak: Wonderful wardrobe spawns items from a predetermined list.

### CODE REVIEW

**Comment by DrSnips** [comment]
I've been meaning to add this for a while but it seems like it could be useful here. Vacuum packed clothing bundles that's always small in size but contains sets of clothes that get spawned upon opening it. Could be helpful to the trader so they can carry the set around in a bag rather than having to carry around several pieces that can clog their bag up.

**Comment by spoonylove** [comment]
1 time suit please.

**Comment by Irradiation** [comment]
Now make it so the vacuum-packed bag can't be resealed and we've got ourselves a deal.

**Comment by DrSnips** [comment]
That's pretty much the idea. It's just a wrapping paper thing.

**Comment by DamianX** [comment]
The reason this wasn't merged yet is because no one suggested a list of _fun_ items to add to it.

**Comment by Unknown-as-Captain** [comment]
Spawn 50 wonderful wardrobes in the bar, wait 15 minutes, see what people are wearing, add those

**Comment by DamianX** [comment]
that would imply admins

**Comment by DamianX** [comment]
Given the complete apathy shown in regards to this I merge it and wait for the complaints

**Comment by Allspice** [comment]
>"I hate Vox so much, I am going to replace all the items in the warddrobe with grey jumpsuits"
I do not remember stating what you said verbatim, so unless you have evidence I did the quotes are inappropriate. But I do remember distinctly asking multiple sources, including you (pretty sure I asked you directly) to drum up some toys that would be suitable for a fixed wardrobe list. I got no practical responses. So since I had no incentive otherwise, I took the easy way out.

If you want to make the wonder closet have different items, it's only a PR away.

**Comment by Kurfursten** [comment]
untitled

You planned from the start to include only useless items, made a bad faith PR, and got it successfully merged with zero (0) support.

untitled

There is simply no way to logically resolve the above quote with the fact that you LITERALLY made almost every item from the Wardrobe something the crew can get TEN OF FOR FREE. Explain. On what codebase are you playing that "aqua jumpsuits" get traded, Yred? You probably haven't touched /vg/ in a long time.

**Pull request merged**
