### PR TITLE
Makes tier 3 parts and the RPED cost plastic instead of mining materials

### PR DESCRIPTION
**Pull request by aceedex**
So we had it like this a long time ago and it got reverted because mechanics would simply go around niggering plastic flaps for their work. 
We now have a plastic crate at cargo so this shouldnt be so bad now
:cl:
 * rscadd: tier 3 parts and the RPED once again cost plastic

### CODE REVIEW

**Comment by DrSnips** [comment]
Go commit bathtub toaster.

**Comment by aceedex** [comment]
no u

**Comment by boy2mantwicethefam** [comment]
I'm a scientist player and I approve of this powercreep
Tier 4 parts in the protolathe that cost materials when

**Comment by boy2mantwicethefam** [comment]
I'm a scientist player and I oof because plastic never reaches R&D
But I still approve of it because plastic flaps
Just make it cheaper though, 300 plastic for one component?

**Comment by Hoshi-chan** [comment]
Woah, so you mean upgrading machines will be the domain of mechanics again, rather than R&D?

**Comment by codeungabunga** [comment]
Divide all plastic costs by 10. Unlisted change you tried to sneak in: RPED now costs 20000 plastic.

Overall terrible PR.

**Comment by Hoshi-chan** [comment]
> Miners at least have incentive to do their job because science can upgrade their tools. Botany and cargo have zero incentive to work with science or mechanics. Mechanics as a job is that of an assistant with free insulated gloves and science access, it should be completely reworked or removed.

Literally _the_ issue with mechanics right now is that they're reliant on science/mining to function, but everything they do can be done by science already, so neither science nor mining bothers cooperating with them.

Their domain seems to be printing (and, formerly, upgrading) machines more easily than science can, and their general lack of responsibilities and access to machine printing and construction tools allows them to engage in or assist with autism projects. 

Having been playing mechanic this past week, it doesn't matter how you bribe the miners, who you talk to, or how the course of the round goes: the miners will take _all_ of their shit to R&D, even if nobody's working R&D. The miners will get access from the HoP or captain and do R&D themselves before they hand anything over to a mechanic. Realistically though? Most rounds I just want to print an RPE and tier 3 parts to upgrade mine and medbay's machines. Everything else relevant to what I find myself wanting to do while playing mechanic is already provided for, as nothing else in their job description requires mining materials; just metal, glass, and plastic.

A solution that would satisfy everyone would be to give mechanics some sort of snowflake lathe that prints rapid parts exchangers and parts for plastic, while leaving the protolathe RPEs and parts as they are. Bluespace RPE would remain a science-exclusive upgrade that mechanics might bother the scientists for; the regular RPE is completely sufficient on its own.

**Comment by DrSnips** [comment]
I love when people claim that mechanics were good boys back when plastic was the cost where they wouldn't just be assholes who would hack into everywhere and act like assistant+++. They weren't and nothing has changed about how people play them.
We even made bluespace bins to bridge the gap of materials and, a true shocker, nothing has changed. Despite having the power to walk into research and hack past 1 door in order to make their rped and 4 bluespace bins the view of mechanics is the same. The excuse "They don't have access to materials, therefore mechanics just tide." is a weak one.

**Comment by SonixApache** [comment]
hey it's this PR again

**Comment by codeungabunga** [comment]
General fabricator prints should always cost only metal, glass and plastic. There now mechanics can be unique and useful by making cheap knockoff science creations without using special materials, just scan them first. Maybe have them start with blueprints for RPED.

I think the intent of mechanic was to copy goonstation mechanic job. But the problem with that is that goonstation has actual depth to machine interaction, packets, entire vendor just for various logic components, programmable computer scrips and credentials spoofing in addition to a device scanner. Here, you have a device scanner. That's literally it. A scanner is not enough for a job to be fun, that's why everyone uses it for assistant with gloves and personal lab.

**Comment by DrSnips** [comment]
The easiest way to go about this is too remove the current plastic cost on gen fab stuff and then have plastic be a "fill in" material for 1.5x to 2x the amount. Need gold but lack it? Plastic replaces it.
The RPED shouldn't have a material gate imo. What's the worst that could happen? Your machines get upgraded?

**Comment by SonixApache** [comment]
literally just make mechanic a science alt-title and move the machines to R&D

**Comment by GoodG1448** [comment]
What about just pre-mapping one of each 5 tier 3 parts in a table at the mechanic office so mechanics can scan them from the get go and start priting using the general fabricator?. Not sure if they require any mining materials in order to print them from the general fab.

**Comment by DrSnips** [comment]
I wish we could but I guarantee you will get "REEEE I want my own place and it's definitely not because I just want free gloves AND a proto."
Wait didn't we try that already?

**Comment by DrSnips** [comment]
As for the premapped parts. Let me give you a quick run down on how the gen fab works. When you go to make a blueprint it does the following in this order. Does it have a preexisting design datum? If not does it have a material cost (for recycle and such)? If not does it have research point values (if yes it does some rng bullshit for a random cost in relation to it's total research)? If not then no design is able to be made. If any of those in that order pass then it slaps on a plastic cost.
Since those parts all have an existing design datum which have a material cost it will have the same if not more expensive costs.
On a side note don't use the gan fab to make stuff from the protolathe because you have to use extra plastic 4noraisin.

**Comment by aceedex** [comment]
Mechanics as a job is fine as it is. Not every single job needs to have extensive responsibilities but with this PR I hope to move *some* responsibility back to it without locking anyone into jobbie autism if they dont want to be. I prefer this solution rather than "Go hack some doors to get it from science" specially since it would allow you to upgrade shit before the miners even come back.

The idea that the genfab should replace materials cost is a great one but its beyond me to do so if anyone would take a crack at it that'd be wonderful

**Comment by GoodG1448** [comment]
I mean, science requires actual mining mats. Mechanics can get them "for cheap" by using more common materials, cost shouldn't be a issue since you can always upgrade the general fab. For example: A pico manipulator cost 1500 metal, 1500 glass, 2000 plastic. Print 2 of them, then upgrade the general fab with them. Bam, reduced production cost.

**Comment by DrSnips** [comment]
Did you know that you can currently do that as well? They cost plasma which can be obtained from the literally never used pacman in engineering

**Comment by GoodG1448** [comment]
Plasma is pretty common, both in engineering, the research outpost or by the bulkload from mining. It just an example, imagine the same with phasic scanner or the ultra laser that require uranium/silver/gold, at least to give machanic an alternative if there aren't any miners/science being a cunt.

**Comment by DrSnips** [comment]
You want some solid proof why removing the off station materials won't make mechanics upgrade any more than they currently do? T2 parts.
They can be easily made with no special costs. A hand full of them are available at round start in tcomms/bridge teleporter (by taking apart the machines for them you can scan the parts). If not round start they are piss easy to research by 12:10.
Yet we never see mechanics upgrading stuff with them if not rarely. I think some maps even give mechanics a roundstart RPED or at least gold in the vault to make one. There are no excuses here on why you can't be upgrading. Mechanics aren't going to do it more no matter how you try.

**Comment by codeungabunga** [comment]
The entire T2 part tier is in a weird limbo that is always just 5 minutes away from being obsolete. Nobody bothers using those parts because you'll just replace them right after you're done upgrading things with them.

**Comment by SonixApache** [comment]
Last time, I tried to just place the mechanics, as their own job still, in the science wing. This got reverted due to popular vote.
What I'm proposing now is that we straight-up remove the mechanics job, and fold everything they ever had into R&D.

**Comment by codeungabunga** [comment]
Entire mechanics lab can be recreated in science with about 15 sheets of metal and some cable. The only unique features of mechanics is that they start with gloves and multi department access.

**Comment by aceedex** [comment]
case it was missed, changelog was fixed and part cost was lowered

**Comment by DrSnips** [comment]
@codeungabunga The whole point of this PR is to make the material cost an on station material so they are technically never without access to it just so they can do upgrades. Other people are also pointing out that it's not a 5 minute wait until mats and is closer to never so that statement doesn't hold. The T2 parts are easy to get, potent (most machines are roughtly twice as powerful with them), and cheap (just metal and glass). They are exactly what they are look to do with T3 parts in this PR more the 1st and 3rd ones. Despite these traits you never see them used to give others an upgrade.
So which is it for roid mats? Are they "just 5 minutes away" easy to get for mechanics or are they never ever?

**Comment by aceedex** [comment]
rounds are too short to bother with tier 2s. I'd rather spend the time and energy trying to hound miners or getting some extra access or stealing from science than bother with tier 2s.

Hacking into the vault for gold for an rped means jack when you have 0 parts to use em with

**Comment by DrSnips** [comment]
If mechanic was truely about upgrades and it mattered that much to them they would be passing their time by doing lesser upgrades. Med/sci don't just not do surgery and research until tools/mats come in. They see it as their job reguardless of what level of stuff they have to work with and they do that job as best they can. This is a clear sign that the problem isn't the material cost but rather the mechanic players not wanting to do their job.

**Comment by aceedex** [comment]
Mechanics by and large should be a freeform job, and upgrading is simply a part of it. Their job is non-integral and it allows for them to fill in for engineering/sci without having to forego any crucial responsibilities. A job without  strict responsibilities is a good thing to have.

Moreover, this PR is outside of the scope of what a mechanic does or doesnt do. All this allows for is for mechanics to use T3s without depending on mining. Rather they can depend on cargo or become self sufficient.  Why would this be argued against is beyond me

**Comment by Hoshi-chan** [comment]
>Why would this be argued against is beyond me

This makes it very, _very_ slightly more difficult for science to print thousands of guns, mechs, upgrades, and parts on a single mining delivery, so the science metaclub is reeling. You're not a collab, so you're not permitted to make controversial changes. That's why it's being argued against.

**Comment by SonixApache** [comment]
Mechanics can't fill in for science because they don't have the proper access.
Mechanics can't fill in for engineering because they don't have the proper access.
But hey, lets make Mechanics even more isolated, because relying on other departments is bad.

**Comment by aceedex** [comment]
Cmon sonix we have an rnd guide for mechanics on the wiki dont stick your head in the sand.

Believe it or not cargo and mining are in fact the same department. All this would add is the possibility of botany chipping in and the possibility for mechanics to be self sufficient

**Comment by DrSnips** [comment]
Except for the fact that people that play mining and crate pusher have completely different attitudes when it comes to the game. Techs are notorious for being absolutely garbage or newfags and their minds can only process how fast can they turn cargo into armory 2.
Mining and techs can hardly call themselves connected besides by location since they could never interact with one another and their job works completely fine.

**Comment by aceedex** [comment]
I dont think thats a fair assumption to make. I could just say that miners just want pokemon or science just wants guns. 

I still dont really have any precise reason as to why you dislike this PR/how it can be improved aside from closing it.  Cargo has a plain ol' plastic crate with 50 plastic no fuss with vending machine packs, and worse comes to worse you can ask an AI for one as well. Miners also have order approve access so why the fuzz? Its an all around improvement to accessibility and hardly does it take away options

**Comment by DrSnips** [comment]
I've tested something similar in the past where I would pda or face to face ask the miner to order and grab the NTE disk on their 2nd return. Can you guess how often I actually got a disk? If your answer was anything but extremely infrequently then you're incorrect.
But hey maybe 2019's miners are much better than 2018's with our huge amount of new players.

**Comment by Kurfursten** [comment]
Personally I like plastic parts but this doesn't look like it has support to pass.

**Comment by MadmanMartian** [comment]
I feel a sense of deja vu here

**Comment by aceedex** [comment]
higher on the street
and I know its my time to go

@Kurfursten give it a thumbs up then friend

**Comment by Killette2** [comment]
Plastic for everything is a pat on the back for all the lazy mechanics out there. If you really love plastic so much, why not make tier 3 parts cost both plastic and rare metals? Seriously how does adding a bunch of cheap plastic to an otherwise metal and glass part make it any better?

**Comment by FudgePucker** [comment]
Why not have the parts be printable both ways? Have a "prototype" tier three that requires g/s/u like now, and then have a "economical" tier three that requires plastic.

**Comment by Killette2** [comment]
What would be the difference?

**Comment by FudgePucker** [comment]
The materials used.
That's it

**Comment by aceedex** [comment]
thats actually a fairly decent change and I like it. Ripperino this for now but Ill be back

**Pull request closed without merging**
