### PR TITLE
Putrid zombies will no longer attack zombies that they create.

### PR DESCRIPTION
**Pull request by Irradiation**
Fixes [#25426]

Note that I tried fixing the faction attribution process, but that created another can of worms. Turns out that Wizards (or any other player that isn't a Cultist, apparently) is part of the Neutral faction. If said wizard necromancy staff's a corpse, the new zombie becomes part of the Neutral faction. Congrats, your newly-made NPC zombie won't attack the crew.

Keeping it like currently PR'd will make it so new zombies are allied to other zombies (so there's no random NPC undead war) and so only the necromancer/putrid stays the new zombie's friend.

[oversight][tweak]

:cl:
 * tweak: Putrid zombies will no longer attack the zombies they've created.

### CODE REVIEW

**Comment by ShiftyRail** [comment]
you could take a look at how the bats from the vamp spells are created to create simple mobs who don't attack each other.

**Comment by Irradiation** [comment]
Looking at how Bats interact with factions, they'll still go turbonuclear if they see a bat that isn't from their faction. And again, if a non-wizard uses the necromancy staff, the newly-created zombie will be passive towards random players, which isn't my intention.

**Comment by RealestEstate** [comment]
might get tricky with apprentices but that's another issue for another day

**Comment by Irradiation** [comment]
I mean, that's already the case. Necromancer apprentices already get munched by zombies belonging to their master, IIRC.

**Pull request merged**
