### PR TITLE
block DNA injector label

### LINKED ISSUE #10724: Feature Request - SE block Injectors showing their block Number
Just a general Feature request. Its a little annoying not being able to see what SE block an injector is, not sure if this is codable with the way DNA injectors are right now

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
adds a label to block injectors
image

## Why it's good
i was going through old issues and this seemed like a trivial one to fix
closes #10724

## Changelog
 * rscadd: DNA block injectors are now labelled more clearly

### CODE REVIEW

**Comment by angryturnip** [comment]
Does this remove my ability to leave monkey injectors named "powers" in the medbay lobby and trick people?

**Comment by pedr69** [comment]
only if you use a block injector
which you aren't gonna be using if you're putting blind+deaf+nervegas all into one syringe

**Comment by tinysaturn** [comment]
make everyone happy by making it a toggle button in the DNA machine

**Comment by Kurfursten** [comment]
Lack of support

**Pull request closed without merging**
