### PR TITLE
Removes the advanced lazarus, moves its functionality to the regular one

### PR DESCRIPTION
**Pull request by aceedex**
[balance]
a long time ago a collab told me "might as well remove the advanced lazarus and make the regular refresh drops, its stupid redundant tiering"
well, alright
:cl:
 * rscadd: lazarus injectors now behave as their adv counterparts
 * rscdel: the advanced lazarus injectors have been removed from the game

### CODE REVIEW

**Comment by boy2mantwicethefam** [comment]
don't forget to remove the icons

**Comment by MadmanMartian** [comment]
keep the icons, they can be used for the Advanced™️ Lazarus Injector that can be used thrice before discarding

**Comment by SonixApache** [comment]
pay the price for your plates, powercreep scum

**Comment by Hoshi-chan** [comment]
Raise the cost of the injector a lil bit.

**Comment by jknpj** [comment]
>someone removes the drop refresh from Lazarus, because easy and cheap and abusable It was 
>someone adds an advanced lazarus because they want their crutch back
>now someone is removing advanced lazarus and making the default one refresh loots because "useless tiering"

**Comment by aceedex** [comment]
Hey, merge it or not I dont feel strongly either way. But the collab the OP is quoting is you jkp.

Also, the PR that changed that was labeled a bug fix PR and at no point was balance discussion even considered by the collaborators when it was made

**Comment by jknpj** [comment]
That's bullshit but i believe it.

**Comment by MadmanMartian** [comment]
I dislike this change

**Comment by PJB3005** [comment]
Of course this is happening.

We've come full circle of powercreep.

**Comment by jknpj** [comment]
As hoshi said, at least make it more expensive.

**Comment by aceedex** [comment]
tbh I rather wait for kurf's economy shit before touching pricing even if this stays in the backburner for now

**Comment by SirSkeleto** [comment]
ded pr rip robo

**Comment by MadmanMartian** [comment]
Did Kurfs economy change ever happen?

That's why it's DNM

**Comment by PJB3005** [comment]
If I just want to lazarus Ian it shouldn't cost 2x more than before, so upping the price is a big no-no.

I am also extremely against even HAVING the advanced lazarus' capabilities, but that discussion has clearly been done already.

Keep these split and keep the paywall. The advanced lazarus is for miners who want instantly max tier armor the second they find a single goliath. The normal lazarus is for the rest of us.

**Comment by aceedex** [comment]
it aint *just* for goliaths. stuff like hivelord cores and basiliks work on it too. Its also if you want to take such a drop but also not make your pokemon useless since taking drops off simple mobs lowers their HP. 

melee armor isnt such a crazy thing either by the way, the riot suits sec start with are just 10 less points resistant than a maxed out mining armor. I see 0 issue with leaving the price as it, but any pricing discussion would go after kurf audits the miners

**Comment by SonixApache** [comment]
mining hardsuits are standard outfits for miners, they're not frowned upon for wearing them 24/7
riot gear is locked in the armory and generally only broken out for special circumstances

just pay the price for your plates and literal full insta-heals

**Comment by aceedex** [comment]
So with the mining cost shit merged and mining income being abysmall as it is now, not only do I not care for price changes but Id make em cheaper if just to offset how bad mining got it.

Please remove the DNM and merge

**Comment by SonixApache** [comment]
pay the price, powercreep scum

**Comment by aceedex** [comment]
Play a mining round sonix. None of this Theorycraft bullshit.
Id tell PJB to do it too, but he might have an allergic reaction. The PR Had the support from the get go without the travesty that are the mining changes, so I aint moving

**Comment by PJB3005** [comment]
The advanced lazarus is still the "crutch for people who don't want to have to grind goliaths for max armor". The default lazarus is still unaffected.

**Comment by SonixApache** [comment]
logged on at a random time, looked at mining, here's what i saw
faget
literally unnecessary PR

**Comment by MadmanMartian** [comment]
After just playing a round of mining, advanced lazarus is still way too cheap considering it's a full restore versus a revive. Skinning halves the health of something, so using an advanced laz restores that half health.

I dislike the advanced lazarus injector in general. If you're gonna butcher your pets, you should commit.

**Comment by aceedex** [comment]
Yes you can tie a mouse and wait an absurd ammount of time and maybe you get something you want or 20 canaries from a hacked machine
Play the game sonix.

Still, I like the idea and a lot of people seem to like it as well.

**Comment by MadmanMartian** [comment]
>play the game

The chance for a vending machine to throw an item is 3% per machine process tick. Moreso if the manipulator count is increased, up to 12% at tier 4.

That bypasses any price requirements. Not so impactful now as the price of the items in the dwarf vendor were dropped, but you can still acquire a fair amount of items if you leave a multitude of vending machines firing at a single mouse.

Why do you keep downplaying any argument against you, and pinging people to merge this?

**Comment by aceedex** [comment]
because most of these arguments are moot. Like that one about the machine upgrades.  T4s are pure RNG and are normally accessible post a diamond drill being acquired, as to drill into the vaults that have em. 
Furthermore a 12% chance to spit out something in the best possible scenario  divided against what, 20 item in the minivends?

Im also not pinging anyone since that'd be fucking annoying, just letting collabs know in the proper channels that this is ready for merging, has appropriate support, and the only reason the DNM tag was added in the first place was that I wanted to wait for the mining economy changes before deciding one way or another about pricing, in which  mining income got disproportionally affected relative to the vending machine's costs, so I dont see a reason to change anything about the pricing at all

**Comment by PJB3005** [comment]
> Im also not pinging anyone since that'd be fucking annoying, just letting collabs know in the proper channels that this is ready for merging

The collabs aren't dumb. 

If it has appropriate support, how come nobody except you seems to be arguing in favor? The only "support" you have is the emojiocracy. This is literal powercreep no matter how you put it so I am very skeptical we should trust just that.

I have still yet to see a good argument from anybody *for* this change. I'm fact I've seen none at all since half this thread went off topic about how the mining vendor is broken and shouldn't throw shit out.

**Comment by aceedex** [comment]
Thats the ticket right there, and why there isnt much discussion. Because its such a minuscule change and doesnt change anything about how current mining actually works that there is nothing TO argue.
Its a literal item prune that doesnt sacrifice functionality

Ill take the high road and not take the obvious joke there

**Comment by MadmanMartian** [comment]
>miniscule
>"hey, you know that patch we made so miners wouldn't end up with max-tier armor the moment they made a goliath? How about we revert it?"

**Comment by PJB3005** [comment]
I'm pretty sure you just argued that the price of a Lazarus is quite high for mining now. How can it be a miniscule change if the price gap is quite large now?

**Comment by aceedex** [comment]
I never said that. What I said that miner income is proportionally lower, so I dont care to change anything about pricing.  Doesnt even matter, as people were fine with this change back when it meant a 2000 dollar discount

Away with that gay shit robo. [12182]
6 to 8 votes for against, lots of arguing against in the change in the comments. Merged in the same day.

**Comment by SonixApache** [comment]
conflicts...

**Comment by Kurfursten** [comment]
This was discussed in the ivory tower and there's no support for it from any of the collaborator team.

Being able to use the same one goliath farmed repeatedly until your armor is at 90 (yes, 90) melee resist is bad game design™.

**Comment by aceedex** [comment]
thats a bitch made comment kurf.
That function is already in the game. I call bullshit

**Comment by bathosbathtime** [comment]
Currently, this change would make the current advance injectors 100 credits cheaper, add six more to the vending machine, and removes four revives overall from the vending machine.

While I agree that isn't chump change, the reason given that this was closed acts as if miners could not farm a single goliath currently.  I find that odd, and I also disagree that raising the price to compensate is nonviable.  Though it would hurt more to revive pets, I feel that making that a more expensive option is not the worst possible outcome.

What I find to be more worrisome is the fact that it gives the extra six injectors with total revive functionality.  Convenience of not having to hunt around for multiple vending machines combined with easier access due to a cheaper price means that we will almost certainly see many more miners using and abusing the lazarus injectors.

Certainly, however, we could discuss bringing the price up and/or reducing the total amount of injectors per vendor more than outright closing this pull request.  I believe the support given merits an attempt to discuss it further.

**Comment by PJB3005** [comment]
The reason for closing is not "as if they can't", it's "they can, it's terrible, but that's no excuse to make it worse".

**Comment by bathosbathtime** [comment]
Could've saved me a bit of time if that was said earlier, but thank you for saying it still

**Comment by Kurfursten** [comment]
If the worry is that there aren't always enough goliaths to max your armor, that's reasonable. We've talked about things like monster lures. If the worry is about being able to revive your pets at max health so they can go on fighting, why don't we add more methods of monster maintenance and care besides revival? Some real roid veterinarian stuff.

But we don't really know what the intent is here, since the author's only words on the matter are "Hey, merge it or not I dont feel strongly either way." Since he doesn't care, this one seemed safe to close.

**Pull request closed without merging**
