### PR TITLE
Bagel Clearwater: Revival

### PR DESCRIPTION
**Pull request by CptWad**
Working on:
Part 1: Front-end Improvements)
image

Now I just need to implement teleporters

Part 2: Add Teleporters
image
image
image

Part 3: Installing a RUST
image

Other possible tweaks:
Chapel improvements
Trader port near arrivals proper, move over escape as result.
Anything else

[bagel]
[dnm]
[qol]
[tweak]
[wip]

:cl:
 * experiment: The following applies to bagelstation
 * tweak: Adjusted some of the Dorms, reducing the size somewhat and made it more accessible, this should help make it feel less massive. 
<--
 * rscadd: Added teleporters. Enjoy zipping around the donut faster than ever!
 * experiment: Replaced the singlo with a R-UST
 * Tweak: Adjusted some wiring around engineering
--->

### CODE REVIEW

**Comment by FudgePucker** [comment]
Are these normal teleporters or some other type?

Normal teleporters have a chance of failure. I have ended up dead in space before using one.

**Comment by CptWad** [comment]
https://github.com/vgstation-coders/vgstation13/pull/21432

**Comment by FudgePucker** [comment]
Ah nice.

**Comment by CptWad** [comment]
image
Dorms edits complete
r8
also now to wait for some aid on the teleporter stuff


in other news I could also use some ideas for the RUST setup
Whats needed, what isnt, how to make it better than deff's etc.

**Comment by SonixApache** [comment]
A requested QoL: Change the vox dock shit so they have an actual AREA-WITH-TRAFFIC place to set up shop rather than their little shitbox in dorms

**Comment by CptWad** [comment]
Like an actual trade post on the dock itself?
alright ill add it to the list

**Comment by ShiftyRail** [comment]
Brig absolutely needs to be UNFATTEN

**Comment by aceedex** [comment]
Should let the middle setup be a bit more freeform for both rust and scrungulo

**Comment by Kharkov72** [comment]
Yeah okay but when are you reworking the hallways

**Comment by utilitas-** [comment]
Make the R-UST spot easily hot-swappable. There's no reason why you couldn't put a singulo there while sacrificing the piping of the original R-UST spot. Same for an SME.

**Comment by SonixApache** [comment]
I'd actually recommend moving the vox dock altogether. Maybe put it in the hallway just outside the sec checkpoint where escape is, and put the store in the little alcove in front of it.
Throw escape a bit to the left to compensate. Not like that's an important place anyway.

**Comment by kilozombie** [comment]
A Vox dock/shop in somewhere people actually go would be a fucking godsend

**Comment by SonixApache** [comment]
If you manage to unfuck bagel to the point where it gets added back to rotation, it'd be interesting to get some statistics on what areas are most travelled.

**Comment by cadaverouscoyote** [comment]
PUSH THE WHOPPER BUTTON

**Comment by FudgePucker** [comment]
I thought that the main gimmick behind donut and bagel was that when the singularity gets loose it's a guarantee to cause damage

**Comment by CptWad** [comment]
I guess the novelty wore off
though I simply included the singlo because it was in old donut not necessarily because I wanted it to be loosed every shift.

**Comment by ValkyrieSkies** [comment]
BASED

Also you could probably merge the laundry room into the east side of dorms and free up the old laundry room for something else.

**Comment by KingofHONK** [comment]
image

For funsies i decided to do a birds eye view of department entrances (red circles) relative to the teleporters (blue circles). Teleporters havent been live tested, but I suspect that the halls highlighted in yellow will become high traffic areas due to people choosing the quickest route (teleporter available.)

Cargo and engineering are going to see the least benefit from these being added, but even cargo will still have a quicker way of getting to medbay and bar now. 

The northwestern side of the station is going to see the least amount of traffic. Eva-holodeck-dorms-and escape especially.

**Comment by CptWad** [comment]
Theres also going to be a teleporter adjacent to dorms and in the "autolathe" room

>The northwestern side of the station is going to see the least amount of traffic. Eva-holodeck-dorms-and escape especially.

thats fine


in other news
image


I have freed up some space and reduced the roundness of the halls in this specific area Shuffling parts of EVA to reduce hallway space and turn number
While in there I freed some space for the magboot-jetpack closet so more than one person can loot it during an emergency.

The result is this weird one tile off hallway part next to arrivals. I think thats my next target in terms of

**Comment by CptWad** [comment]
and presto
image
As to how the teleporters work I guess I have to either code or hardmap them in
hmmmmmm

**Comment by CptWad** [comment]
Some more teleporter rooms
image


image


image

**Comment by CptWad** [comment]
I gather that a hot-swappable engine is wanted
but how should I implement that

If yall could just post som mspaint setups of each engine individually I could figure it out on my own
I sorta understand TEG but have no idea how the RUST works

**Comment by KingofHONK** [comment]
just make a room full of hand crankers

**Comment by FudgePucker** [comment]
Have two rooms on each side. One with the PA and radiation collectors, the other a control room for the rust, including fuel injector and all the computers, also a TEG. In between them have a chamber for the rust set up, scrubbers and injectors, the rust core. Out side of this have gyrotrons on the rust side, and surrounding the chamber have emitters and field generators. If somebody wanted to set up the singularity they would remove the core and replace it with a singularity generator.

Main concern with this is how much faster will it take for the singularity to get big because of it eating the chamber.

**Comment by CptWad** [comment]
I guess I have to note that the singularity is actually compacted in bagel at the moment
after looking at it I realized that my early tests required the current spacing of most of the departments because of the natural EMP and item pull range of the singlo through walls
Other maps have run into the problem before and I was sure to prevent it
Singlo takes up too much room.

Instead I could swap Shard and singlo, put singlo on the outside of the station and make the center a Rust/SME/TEG abomination

**Comment by utilitas-** [comment]
But that entirely invalidates the entire point of the map.

**Comment by SonixApache** [comment]
Throwing the singulo out of the core to replace it with a RUST wouldn't be a bad thing.
Power never ever, but that aside.

**Comment by Kurfursten** [comment]
Imagine wad pretending he was gonna come back

**Comment by Kurfursten** [comment]
You may request to have this reopened

**Pull request closed without merging**
