### PR TITLE
mousehat runtime fix

### PR DESCRIPTION
**Pull request by pedr69**
[tested][100%tested]
## What this does
fixes runtime
## Why it's good
left as an exercise to the reader

### CODE REVIEW

**Comment by Theophrastus1** [comment]
for you its on the mouse

**Comment by Exxion** [comment]
I do not think this fixes any runtimes.

**Comment by pedr69** [comment]
if you put an item in your hat slot that does not have a nearsightedness var(a mouse fore xample), sneed gas will be released

`[14:25:11] Runtime in standard_damage_overlay_updates.dm,128: undefined variable /obj/item/weapon/holder/animal/mouse/var/nearsighted_modifier
  proc name: get impaired vision range (/mob/living/proc/get_impaired_vision_range)
  src: Schlomo Gaskin (/mob/living/carbon/human)`

**Comment by Exxion** [comment]
This check will cause exactly the same runtime

**Comment by pedr69** [comment]
i think this also explains why i could see well even with welding goggles that one round and the admin couldn't reproduce it
i had put a mouse on my head earlier which broke `get_impaired_vision_range()`

**Pull request merged**
