### PR TITLE
Revert "The Rebalancing of Bones"

### PR DESCRIPTION
**Pull request by yclatious**
CRACK THE FUCKING ACK, WE AINT DONE PROVING THE RIG

### CODE REVIEW

**Comment by Exxion** [comment]
Stop
We can open the revert PR IF and WHEN we get proof

**Comment by PJB3005** [comment]
My gut.

Also quality control jesus christ there's a point at which we have to put our foot down.

Literally *all* the arguments in that pile of shit PR were either "remove, they're a shit race." OR "we already have them skeleton lives matter". None actually justifying their existence.

**Comment by Exxion** [comment]
There already was a server vote

**Comment by Exxion** [comment]
Oh yeah also a ruling from the chicken in inbound

**Comment by Riekland** [comment]
is pjb even a collab anymore I don't remember
Anyway whatever he says can be ignored because he's pjb
And it doesn't fucking matter what the arguements were because the vote said otherwise gaylord

**Comment by PJB3005** [comment]
@Riekland I still insist votes are glorified emojiocracy.

**Comment by Intigracy** [comment]
reminder

```
Like, is there a reason not to bring them back, at this point? I'm legit curious.

They've been nerfed to hell and back, and most of the other races already have become significantly more powerful in comparison. They're not going to be an 'optimal' choice for powergamers.

Is there any reason to hold back on bringing them back, other than 'muh meme races'?
```

**Comment by Kammerjunk** [comment]
>Skeletons get removed for being a meme shitter race
>Pomf eventually nerfs them into the ground
>Them being nerfed so bad is used as an excuse to bring them back because "all the skeleshitters would have to deal with the severe handicaps"
>#12418 #12390 #11287
>#14782 #14798

🤔

**Comment by Allspice** [comment]
Well, here's a compromise: Remove the speed thing, then people that propogate an actual SLIPPERY FUCKING SLOPE get blacklisted from the race that's getting sloped, sounds like a good policy to me.

**Comment by Exxion** [comment]
No need for a blacklist now that Pomf removed skeletons from roundstart again
: ^ )

**Comment by SonixApache** [comment]
the obvious answer is to remove skeletons

**Comment by Intigracy** [comment]
the obvious answer is we removed skeletons

**Comment by adu6oo** [comment]
the obvious answer is we removed skeletons

**Comment by SonixApache** [comment]
see? it works

**Comment by Unknown-as-Captain** [comment]
Learn from history or you're doomed to repeat it.

**Comment by Intigracy** [comment]
Hope the buffs were worth it tbh

**Pull request closed without merging**
