### PR TITLE
Cyborg module changes

### PR DESCRIPTION
**Pull request by aceedex**
This PR changes a bunch of robot modules. The first change is very benign. It replaces all the surgery tools a medborg has with a surgery switchtool, because medborgs have a 4 square high module list. 
The second is a little more eye grabbing. I gave the crisis module a maxed out switchtool, meaning it has all the upgraded surgery tools. Because If your job is doing surgery while getting shot at, I think you should be able to do it fast. The last change is I've removed the emag from the blitz module. I think the blitz module right now is a little crazy and is basically the jobbie killer 5000.  By removing it's emag I mean to make it stick more with the ops instead of going out to murderbone. It has a heat axe that can cut through normal walls so I don't think it has much risk of being stuck if it doesn't have one. 

:cl:
 * tweak: Medborgs have had all their tools combined into a switchtool
 * rscadd: Crisis module syndieborgs had their switchtools upgraded to have maxed tools
 * rscdel: blitz module syndieborgs no longer have emags

### CODE REVIEW

**Comment by Irradiation** [comment]
I personally find it faster to have a few surgery tools opened up instead of having to tab between the switchtool, so that's a "No" from me.

**Comment by jknpj** [comment]
> I think the blitz module right now is a little crazy

Remember when the syndieborgs were supposed to be expensive, but worth their price tag?

**Comment by aceedex** [comment]
Well, thats certainly not what the crisis module got. But I digress. Ive played it, Ive played against it, I think that its a very fair change, that it cant go off on its own, clear the station and drag back the cappy that has the disk on its back and instead has to support the ops. If it ends up downright neutering the module I'd be more than glad to revert it because blitz is fun

**Comment by Megautham** [comment]
Switchtool's interface is actually worse than alrady existant tool selection interface for two reasons. One - you can't have multiple tools open and switch between them, two - switchtool selection lacks icons, making it harder to use. I also suggest that the next time you pr something like this you split the changes to multiple pr's since even though it's all module changes each one of these changes can be assessed differently.

**Comment by Buchse** [comment]
I'm in favor of reworking mediborg stuff, honestly, but with the recent changes to how hands and timers work, having that big tool bar available for use, and being able to switch hands mid-timer is a giant boon. I'd personally like mediborgs to have some kind of pill tweezers or something by default, if I got my way.

**Comment by aceedex** [comment]
I uh, Im not sure if you guys have played crisis module before and if you haven't I dont 'blame you.
But this change does somewhat keep that functionality: you can in fact retract a tool and pick another one while a surgery step is going.

**Comment by PrimeDSS13** [comment]
these are two different changes, I feel like they should be two different PRs.

**Comment by Kurfursten** [comment]
This is going to suffer for its lack of atomicity. I, like others, prefer no switch tool. Don't care about the blitz and crisis changes.

**Comment by BomberBro** [comment]
I've always thought the crisis borg was kind of bad for its main job, which is saving quite possible the most difficult to save patients in the game. I like the idea of upgrading its tools so surgery is more feasible. As for the others, I'm pretty meh overall on the other two but I can see why the medborg changes would be disliked, there's an engineering switchtool usable by ERTs that's really annoying to use when a toolbelt swaps everything twice as fast and you can hold two (or three for borgs) tools at once instead of cycling around.

**Comment by aceedex** [comment]
Like I mentioned before, you can still do switching in the middle of a surgery step with the switchtool. Im surprised people take such a big issue with that change considering its wholly QoL

**Comment by ArchSunder** [comment]
You could give the switchtool as an extra module to the medborg maybe, so it suits both types of players

**Comment by Kammerjunk** [comment]
in addition to the whol "doing multiple steps at a time" thing, I just don't really like the switchtool

**Comment by tuypo1** [comment]
I think a switch tool would be overall better but still this PR is way too unatomic

**Comment by aceedex** [comment]
Well arch that would just be making more clutter which defeats the point

**Comment by aceedex** [comment]
the people want atoms

**Pull request closed without merging**
