### PR TITLE
Windows can now be rotated with alt-click.

### PR DESCRIPTION
**Pull request by Allspice**
yep

:cl:
* rscadd: Windows can now be rotated with alt-click.

### CODE REVIEW

**Comment by Reviire** [comment]
Alt clicking full windows should act as alt-clicking the tile tbhfamimho

**Comment by DamianX** [comment]
don't take away muh alt-clicking full windows

**Comment by Sooose** [comment]
Is it possible to move alt clicking a tile to another modifier key? These things should not be conflicting.

**Comment by Allspice** [comment]
Is the conflict with alt-click tile and alt-click fullwindow? If so: It's probably possible with enough jiggering, but I don't think it's a big enough issue to warrant messing with peoples' use of long-standing controls.

**Comment by DamianX** [comment]
Sure, why not

**Comment by Exxion** [comment]
BYOND only supports Ctrl, Shift and Alt as modifier keys
Which makes sense because those are the only ones on most Windows machines

**Pull request merged**
