### PR TITLE
Remove cult word research.

### PR DESCRIPTION
**Pull request by Allspice**
Apparently [a poll](http://ss13.moe/index.php/poll/123) regarding cult research removal passed or something while I wasn't looking. I guess I'll make a PR removing blood boil tomorrow in exchange.

Long time in coming, and cult 3 might be around the corner anyway, and datums might be merged soon anyway removing cult 2 with it, but might as well play with it in the meantime. The whole "communicate your word and things will turn out fine" hasn't really panned out with how frequently the weakest link writes a rune in maint or some shit and spills the beans; if that happens before research was even done, then it's near-crippling even for experienced cultists. While it would take perhaps a more radical PR to get new cultists to stop doing dumb things, I don't see a reason for research to keep bogging things down.

:cl:
* rscdel: Remove cult word research: Tomes and related paraphernelia use the english translations by default instead of jatkaa karazet et al.

### CODE REVIEW

**Comment by MadmanMartian** [comment]
I personally disagree with this PR, as you're just making game modes you are attributed to easier and easier.

**Comment by DamianX** [comment]
Research is boring, uninteresting, and is probably one of the main reasons some people don't like playing cult. This change will only make things more fun. If it proves to make things too easy for the cult we can always revert it, but I strongly believe we should give it a try.

**Comment by jknpj** [comment]
Why don't we make cultists play tetris to get words? Worked for research. :thinking:

**Comment by Irradiation** [comment]
>Worked for research
Good joke, people forgot to move the R&D console, so the research levels didn't get points from Tetris.

**Comment by Jubisloviu** [comment]
why not just add a nar-sie themed minigame to cult research?
pls

**Comment by Pathid** [comment]
>Tetris

If anything, cult research should be Picross.

**Comment by DeityLink** [comment]
Word research was meant to give the crew a bit of a head start, letting cultists have all runes available at round start is dangerous, and moves the game mode even further from the "cultist experience".

Don't get me wrong, I think word research sucks, and cult 3.0 is *soon* to get rid of it, but I don't think this is a balanced proposition.

**Comment by Blithering** [comment]
Perhaps instead of removing research and blood boil entirely, make the more extreme runes locked to objective stage or number of sacrifices to narnar. Manifest ghost could even make a comeback as an endgame rune that way

**Comment by Allspice** [comment]
I'm not sure that manifest ghost in its old form would be terribly fun to go up against as a crew member. And if you're considering changing it, well, perhaps. But I'll summarize my previous statement in various conversations about manifest in saying: It's either not very fun to go against or it's not very fun to use or it's useless unless you powergame out the dick.

As for research in general. It was sort of warranted when manifest ghost was existant, sure. But now that it's not, and especially if blood boil is removed in exchange, I think there's just not enough bullshit in the cultist arsenal to justify artificially bogging down the cult's progression. Especially considering that the cult progression is already relatively slow due to talisman/base preparation, and organizational speed due to cult comms being worse than most other team antags (even after comm talismans were buffed).

**Comment by DeityLink** [comment]
Worth noting that the poll you're referring to is a year old, and I used that as feedback for replacing word research in cult 3. I wish people would wait a bit longer rather than break the balance of cult 2 even further.

**Comment by Kammerjunk** [comment]
Only worth noting if the poll being a year old is an issue. Not worth noting if the poll is still relevant enough to use for either this PR or cult3
Getting caught in the first 15 minutes because you start with a mandatory downtime in which half the jobs are forced to risk standing still with antag gear in hand (and on the floor) isn't exciting gameplay and doesn't add anything to the conflict. Perhaps it's a larger issue with cult, but that in particular just kills the round because
- Sec knows there's a cult
- Cult doesn't (necessarily) know sec knows there's a cult
- Sec doesn't know the status of cult
- Sec is now justified to go on the crew until the cult is confirmed dead (which it can't be)

**Comment by DeityLink** [comment]
Funny how the Cult Armor talisman was purposefully removed from the supply talisman specifically so people couldn't just wipe out a cult sword & robe at roundstart, like, the supply talismans exists specifically to limit and cater the first spells that cultists are allowed to use, and this PR throws all of this out the window.

**Comment by Allspice** [comment]
```tree 43cb612fd552c579cdd3eea5b4ee11cafb45d570
parent e7782684844cbd2cbdd2af5f0694aa6170198db3
author dylanstrategie <dylanstrategie@hotmail.fr> Wed Aug 27 20:54:44 2014 +0200
committer dylanstrategie <dylanstrategie@hotmail.fr> Wed Aug 27 20:54:44 2014 +0200

Remove armor from talisman options

After some 10-year old ick-ocking pubbie edgelord has shown us how good
of an idea this is, I have decided to remove armor options from the
talisman (starting and possibly imbued). Here's my reasoning :

- A rune already exists, and you can imbue it, so you sure as hell
aren't forbidden from having those edgy rune robes
- Giving someone the ability to muderbone with gear that OPENLY screams
what's happening, in a STEALTH GAMEMODE, is one of those good /tg/ ideas
that plague our code
- Seriously, you have three words to research. Hell is usually supplied,
then find Destroy and Other. You sure as hell shouldn't be able to
summon armor if you wouldn't even be able to make a rune if it raped
your mind
- Sides effects include not being able to imbue armor talismans anymore,
but if you have tome and a few seconds you can make armor anyways
```

It seems to me that the salient bit less that "this gear is enabling action too fast for people to do their jobs!", and more the `gear that OPENLY screams
what's happening, in a STEALTH GAMEMODE`; so armour was removed from the supply talisman because retards would unzip a sword without coordinating with the other cultists, get caught after 0-2 kills that they didn't even bother stoning, and fuck up the round for their supposed allies. That was removed sure, but what we still have happening is "Some scrub that didn't read the wiki page before enabling cult, then left a nonfunctional rune in maint which was seen by a greyshit two minutes later and fucked up the round for their supposed allies."

Two minutes before being exposed is better than zero minutes, I'll grant you, but it's still pretty rough stuff.

**Pull request closed without merging**
