### PR TITLE
Bicarodyne explosions no longer purge chemicals from their container.

### PR DESCRIPTION
**Pull request by Irradiation**
And this, folks, is why Sonix shouldn't be trusted with 50% controversial PRs. Can't be assed to go all the way and remove other sources of explosive chem purging. Sorry 50% spessmen, you can't put on an EOD suit to chem purge yourself now.

:cl:
 * tweak: Bicarodyne explosions don't purge chemicals from their container anymore.

### CODE REVIEW

**Comment by SonixApache** [comment]
¯\_(ツ)_/¯

**Comment by Pathid** [comment]
And why does this matter anyway?

**Comment by Irradiation** [comment]
@Pathid Because this is how I'm intending to infiltrate the sneaky coder metaclub. Sacrifices must be made. That and consistency.

**Comment by ShiftyRail** [comment]
There goes my reason to have antags to on

**Comment by Irradiation** [comment]
You see, before this PR, you could be an antagonist chemist/pharmacist and not even antagonize the station. Just do the method indicated in the OP and soon you will learn to antagonize the _coders_. Are you a bad enough dude to stop this PR from being merged?

**Comment by bathosbathtime** [comment]
Consistency of game mechanics is important, at least to me.

**Comment by SonixApache** [comment]
[DNM]

**Comment by Pathid** [comment]
>**muh consistency**

https://github.com/vgstation-coders/vgstation13/blob/62712d9ba6dd0b3a3fcc16046bd6e201cb560bef/code/modules/reagents/Chemistry-Recipes.dm#L82-L84

If you really wanted it to be consistent, you'd have it remove all bicarodyne and paracetamol. But that's not at all what this PR is doing.

**Comment by SonixApache** [comment]
oh man, wouldn't this cause infinite explosions?

**Pull request merged**
