### PR TITLE
All mobs (except bosses and aliums) can be pacified

### LINKED ISSUE #22957: Only asteroid mobs can be pacified, which is intended but bizarre.
That means pillowbugs pacify goliaths around you
But it also means you can bring a cage with 10 carp and 1 pillowbug to the bar, and the carp won't be pacified (but humans will so they can't attack the carp in retaliation)

Why was it specifically made to be like this?

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Why?
 - So Vox Traders can pump deadly wild mobs full of chillwax in dangerous exotic zoo operations.
 - Because it's gay that a miner can easily just buy a pokemon master belt and carry a pillbug with him, which makes it impossible for other players to shoot his mobs but letting his mobs attack as much as they want.
 - I want to make a shit PR if this passes.

Fixes #22957

:cl:
 * tweak: All non-vault, non-awaymission mobs can now be pacified (with a few exceptions like mechahitler and aliens).

### CODE REVIEW

**Comment by MadmanMartian** [comment]
prepare for unforeseen consequences

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
My favorite

**Comment by MadmanMartian** [comment]
This would make pretty much all mob-based challenges (Vaults, dungeons, away missions, etc.) instantly cheesable via a pillowbug or chillwax syringes.

I implore you to reconsider.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
That's true. Rather than blacklist all the vault etc mobs, maybe we can add a NO_PACIFICATION area flag?

**Comment by FudgePucker** [comment]
Lmao, simple mobs have to be cheezed.
Its dislodged wall support or chill bug

**Comment by MadmanMartian** [comment]
> That's true. Rather than blacklist all the vault etc mobs, maybe we can add a NO_PACIFICATION area flag?

So the tactic then would be to lure them out of their area. Full mob pacification is a thing that should be approached carefully, as it is incredibly powerful. If not with a pillowbug, with chillwax.

**Comment by FudgePucker** [comment]
These are simple mobs. If you dont cheese them they ruin your shit because they do not bleed, they do not feel pain, and they do not know fear.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Still rules out away missions and if you can lure a mob out of a vault then you can just like make it space itself?

If you have a better idea I'm listening

**Comment by MadmanMartian** [comment]
Better idea for what?

For the cases given, there's

>So Vox Traders can pump deadly wild mobs full of chillwax in dangerous exotic zoo operations.

Just use a structure shield, or girders instead of grilles. As was mentioned by FudgePucker, there's plenty of ways ingame to block a creature.

>Because it's gay that a miner can easily just buy a pokemon master belt and carry a pillbug with him, which makes it impossible for other players to shoot his mobs but letting his mobs attack as much as they want.

This is a problem with the pillowbug. Could have it so that the pillowbug becomes exhausted if it's stopping too many things from attacking. For instance, it can stop 10 attacks at a maximum, with this pool being replenished by 1 point every lifetick perhaps.

>I want to make a shit PR if this passes

What would the PR consist of? And why does it require this?

Overall, this would be a bad idea. Better to have a whitelist-esque of things that can be pacified, than to have a blacklist of things that can't be pacified, so as to avoid unexpected (Or undeclared) functionality.

**Comment by brndd** [comment]
I'm with FudgePucker here. FUCK simple mobs and FUCK vaults that rely on them for difficulty. Nobody ever does them legitimately anyway, so we shouldn't let the cheese potential of vaults ruin an otherwise perfectly reasonable PR.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Nah, I think awayvault cheese is a valid criticism.
However, I believe an area flag will acceptably solve that issue.
dreamseeker_2019-05-29_12-40-35


As for unforeseen interactions, I'm willing to take that responsibility. Weird and wacky interactions are half of this game's appeal to me, personally.
In any case I can think of multiple questionable interactions with a whitelist, and so far only awayvault cheese for a blacklist instead. If anyone can think of any other issues that should be addressed now rather than later, I'm listening.

**Comment by Kurfursten** [comment]
I hope your solution with areas is sufficient, but I trust you on saying you'll keep an eye on this since you always have in the past

**Pull request merged**
