### PR TITLE
Upload computers now only target silicons on their z-level. Adds long range AI upload.

### PR DESCRIPTION
**Pull request by Duny-**
This is basically my version of [jknpjr's attempt](https://github.com/vgstation-coders/vgstation13/pull/17746). I re-used the code of his old PR and made no vain attempt at refactoring the upload computer's code.

Standard upload computers can now only target silicons on their z-level with their cheap-ass transceiver.
After overwhelming reports of station "workers" explaining why not being able to reset an AI that was brought off-station was a really, really bad thing for productivity, NT officials decided to design and build a single more expensive long range AI upload computer on each station. The model includes a subspace transceiver capable of reaching AIs well beyond station range. 
They added: "This is expensive stuff, made to be very annoying to replicate to discourage terrorists. If you break it, you better find a way to build a new one yourself because we're not paying.".

All maps have had their starting AI upload replaced with the long range version.
The circuit board requires the following research to build:
Data Theory 4, Materials ~~7~~ 9, Bluespace 3 and Electro-magnetic 5 (basically the research required for a subspace transmitter and an AI upload combined, with material bumped to ~~7~~ 9 to gate it behind understanding of phazon technology)
I'm not quite sure about those requirements. Maybe they should be harder or different like requiring a diamond or some shit. Not a lot of sensible options with research being as it is. 
It should be tedious enough that people will refrain from using it unless they're really dedicated or two hours in the round. Unlike the current requirements for an infinite range upload which can be built 10 minutes in on the research outpost.
Also thought about simply removing the ability to make the new board but the entire station not being fully repairable is haram.

This has the side effect of allowing people to check relatively easily if the AI left the z-level, just build a cheap upload. You can also find which z-level it's in the same way, although with more effort. So, slight AI nerf.

I'm open to suggestions if you think this is inadequate. Pls no bully

:cl:
 * tweak: Standard upload computers now require their target to be on the same z-level.
 * rscadd: Added new long range AI upload which uses its in-built subspace transceiver to reach any z-level in exchange for having harder research requirements.
 * tweak: Replaced roundstart AI upload computers with the long range version.

### CODE REVIEW

**Comment by DrSnips** [comment]
While I think the changes are good I'm honestly let down now that I can see what you were trying to make a cost for. I thought it was going to be some type of teleporter or an all in one tcomms machine because it technically costs phazon.

**Comment by Duny-** [comment]
I told you it wasn't anything new smh don't get high expectations from me coding I'm toddler level in byond code all I ever did was fix bugs and rework shit by looking at and understanding the already present code, I am unable to make new things.

**Comment by Hoshi-chan** [comment]
Materials 7 doesn't require phazon, it requires deconstructing a sheet of diamond.

**Comment by Duny-** [comment]
What does require phazon then so I can bump it to that

**Comment by Hoshi-chan** [comment]
Phazon circuits require materials 9, for reference.

**Comment by Duny-** [comment]
I know but it seems a bit ridiculous to have it on the same level as phazon circuits, doesn't 8 require deconstructing a phazon sheet or something? I don't know much about rnd

**Comment by Pathid** [comment]
https://github.com/vgstation-coders/vgstation13/blob/90d82ea6bcca65c5392c134e8d59f71238a6e234/code/game/objects/items/stacks/sheets/mineral.dm#L257

**Comment by Unknown-as-Captain** [comment]
This feels so convoluted and abusable you honestly might as well just make uploads only work in the station's z-level and avoid a lot of headaches.

**Comment by jknpj** [comment]
@Unknown-as-Captain but then what about dorf mode and centcomm?

**Comment by Unknown-as-Captain** [comment]
Both require admins, add an admin-only longrange console.

Problem with this implementation is that it indeed cucks people building off-Z consoles, but it also allows people to destroy the starting console and move the AI off-Z and now the station is reverse-cucked hard as well.

**Comment by Duny-** [comment]
>but it also allows people to destroy the starting console and move the AI off-Z and now the station is reverse-cucked hard as well.
If the AI is moved off-z, just build your upload computer on its z-level. You were already going to build one since the upload was destroyed, anyway.
If you manage to completely destroy the upload and move the AI off-z unnoticed you deserve your subverted/harder to reset AI. It's much simpler to just build your upload computer on the station's z-level.
The point of this PR is to make subverting the AI involve more risk, not just rolling scientist and casually building an upload on the asteroid 10 minutes in for safe, permanent power over silicons; while taking into account the concern of an AI simply being teleported off-z preventing a reset with the starting computer. 
I think the requirement of destroying the original computer and moving the AI off-z to prevent easy resets is fine. Maybe the requirement for making the long range computer is too hard, I don't know. But at least it can be made.

While I do think my solution is inelegant (I'd rather do away with the long-range computer altogether and nerf telesci, making off-z AIs harder to pull off), making uploads arbitrarily only function on the station's z-level doesn't make much sense and limits possibilities (also breaks the useless upload on centcomm but who gives a shit).

Entirely reworking science is the true solution here (or nerfing/removing telesci and not handholding the playerbase constantly but that's clearly WILD), you can only make building circuit boards piss easy 5 minutes into the round or make it expensive 40mins into the round if you focus on it and get a suit; but don't @ me about this.
I think this is an alright band-aid until 2025 when science is reworked.

**Comment by iFlashYou** [comment]
You need materials or need to steal the law boards out of the AI Upload if you want to subvert any silicons with your roid computer, this "you can do it in 10 minutes roundstart" is a lie.

**Comment by Duny-** [comment]
Just buy a freeform on your PDA lmao it doesn't take 30min.
It's up to the players if this gets closed, merged or modified. I just made this PR on a whim when I saw the older one closed even though people seemed to agree with it.

My firm belief is that the current "problems" related to silicons that I keep being told about are due to current policies, which I can't code or map away. THIS minor change is something I could actually do so I did it, and learned a few things about byond code in the process (and it's even shittier than I thought).

**Comment by DeityLink** [comment]
Makes sense to me.

**Pull request merged**
