### PR TITLE
Remove word research from legacy cult.

### PR DESCRIPTION
**Pull request by Allspice**
Halloween has come and gone. So here's a 0% tested stopgap nicked from #19606 until the promised proper fix is implemented.

:cl:
* rscdel: Removed word research from legacy cult.

### CODE REVIEW

**Comment by DamianX** [comment]
The linked PR specifically mentions that the toggle doesn't work, please test this.

**Comment by Allspice** [comment]
With regards to the toggle, it always worked. It's just that it didn't affect tomes after they are created, which I think is reasonable; gotta toggle it off before spawning in the legacy cult if you want that.

**Comment by DamianX** [comment]
I don't think legacy cult is coming back.

**Comment by jknpj** [comment]
Deity killed it with cult3, literally.

**Pull request closed without merging**
