### PR TITLE
paroxetine prevents *dab

### LINKED ISSUE #33728: paroxetine doesn't prevent *dab
(WEB REPORT BY: janez420ivan REMOTE: 206.221.180.138:7777)
# Revision
79b8dc3e557b0860e373b25b99323ea18c830341
good news, you are not dying! you are going to live fore-

### PR DESCRIPTION
**Pull request by pedr69**
## What this does
paroxetine prevents suicide
prevents you from dabbing while cuffed if you queue up the prompts 
closes #33728

## Why it's good
sneed sells feed and seed

## Changelog

:cl:
 * tweak: paroxetine now prevents you from dabbing
 * bugfix: being handcuffed now properly prevents you from dabbing

### CODE REVIEW

**Comment by jwhitak** [comment]
Message is not funny enough

**Comment by pedr69** [comment]
it's copied over from the suicide check

**Comment by Kurfursten** [comment]
I'm just going to merge this over slight disapproval for consistency, no strong feelings on it

**Comment by Jeremopolis** [comment]
revert this shit for the love of god dabbing is ruined PLEASE

**Comment by Kurfursten** [comment]
It has been merged for a week so if you want to try to pass a revert you are welcome to it

**Comment by Jeremopolis** [comment]
> It has been merged for a week so if you want to try to pass a revert you are welcome to it

How

**Comment by pedr69** [comment]
image

**Comment by pedr69** [comment]
oh nvm you cant because of #33902
gotta revert that first i think

also, think of a better gimmick
i grudgecoded the PR after you dabbed your brain out while cuffed/parox'd about 10 times in a week

**Comment by Kurfursten** [comment]
You don't need to make it sound so hard. Instead of using the revert button, just delete the conditional at line 320 in human/emote.dm -- so easy you can do it on the web editor.

**Comment by Jeremopolis** [comment]
i mean from now on i'll just ghost, at least with dabbing it's concrete, dramatic, funny, and paroxetene doesn't prevent it 
literally all you did was make the game less fun and amusing so good work i guess

**Comment by smashedandslammed** [comment]
Soulless

**Comment by Jeremopolis** [comment]
commenting again so this doesn't leave people's attention, this faggot made the game less fun and it was done specifically to target me

**Comment by pedr69** [comment]
bro what
if i fixed any of the various emitter/reflector laser bugs, would it be metagrudging boxer grigsby too?

**Comment by Jeremopolis** [comment]
> oh nvm you cant because of #33902 gotta revert that first i think
> 
> also, think of a better gimmick i grudgecoded the PR after you dabbed your brain out while cuffed/parox'd about 10 times in a week

it's a grudge when you say it's a grudge

and when any PR that fixes a well known bug that is used for fun, and entirely harmless, it's shitty. wish i had other examples besides this one. it's like if you fixed the bug that made spamming resist when inside a welded locker eventually completely displace the locker. it hurts noone and is funny

**Comment by Jeremopolis** [comment]
> > and it was done specifically to target me
> 
> Most narcissistic post of 2023 so far but I am sure we'll top it in a few months

so you're just not reading the post HE posted where he says he only coded it because I dabbed in custody several times in a short time period? it's not like i'm talking out my ass here

**Comment by Kurfursten** [comment]
I thought that was a joke, I didn't think you actually did that

**Pull request merged**
