### PR TITLE
emaggable clown soundsynth(take 2)

### PR DESCRIPTION
**Pull request by pedr69**
[controversial]
image

## What this does
allows you to use the sequencer on the sound synth, unlocking more playable sounds
emagging it again will play the sacred adminhelp.ogg

## Why it's good
gives antag clowns/mimes more possibilities to make people paranoid
bwoink funny

## Changelog

:cl:
 * tweak: sound synthesizers can now be emagged to unlock illegal sounds. multiple emaggings may result in disaster

### CODE REVIEW

**Comment by Servalfang** [comment]
i doubt itll be that controversial

**Comment by Eneocho** [comment]
Just make the bwoink a regular emagging feature instead of needing double emagging (since a clown with a double emagged soundsynth could only make bwoinks, nothing else).

**Comment by Eneocho** [comment]
>although it might not be consistent with other emag items, is there anywhere a double emagging does anything?

You can emag a body scanner to enable the irradiating fuckmode and emag it again to disable it, but that's the outlier, the common standard with emags is that emagging is to some degree, breaking and/or corrupting.
Please make it so you can select the bwoink and sound it freely.

**Comment by Kurfursten** [comment]
Number of swipes was not the reason it was rejected the first time. We don't close a lot of things on policy, and yet you continue to violate it. It must be a forbidden fruit thing - near unlimited content potential, but if one thing is disallowed, that's the only thing you're interested in PRing.

**Comment by Eneocho** [comment]
And I guess the clownshoes, the ones that make random sounds. They cannot be emagged twice, but if the earrape mode flag is enabled (only activated if emagged or april fools) without the thing being emagged, it gives you a cursed banana.

**Comment by PrimeDSS13** [comment]
this PR is actually good if you removed the bwoink and discord
OOC sounds are shit

**Comment by Exxion** [comment]
The policy was explained. It's the same reason you can't use text speak IC. This isn't a noRP server.
As for the song, it's a bit different in that its actual purpose is to break the fourth wall, but honestly it probably shouldn't be player-accessible either

**Comment by Eneocho** [comment]
I can concede on the bwoink because it's getting some asses blasted, but the shitcord one should definitely stay in, it's funny.

**Comment by Eneocho** [comment]
How about this: The bwoink is enabled during april fools or if an admin VVs the soundsynth to enable it.

**Comment by Eneocho** [comment]
@pedr69, that's the way to go. Limit bwoink to april fools or VV and try for the third time.

**Comment by pedr69** [comment]
i guess the emojicracy does not matter when the c*llab decrees a converting sound norp
what's next? a ban on red crayons during cult rounds?

still mad about the holyjuke

**Comment by Exxion** [comment]
Converting sound is fine? It's just the bwoink and Discord sounds we're complaining about

**Comment by Eneocho** [comment]
The Bwoink is apparently too much due to its admin OOC implications, but I'll be damned if you c*ders try to remove the shitcord sound as well.

**Comment by Kurfursten** [comment]
That is correct, the emojiocracy does not matter when the collabs are in agreement. That has always been the case.

We take player feedback seriously on more than 99% of PRs. But I am sure you will continue to throw a tantrum over that the one in literal thousands of PRs we've drawn the line on. I expect three days of thread whining that the Gestapo have LITERALLY taken your freedoms and practiced real violence against you. You are so oppressed.

**Comment by pedr69** [comment]
how do i edit the thing now?
i bend the knee to the Gestapo, but the commits arent showing up here
do i need to make another PR

**Comment by Eneocho** [comment]
aye.

**Pull request closed without merging**
