### PR TITLE
Introducing the NINJAMOP

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
Companion PR to #21632

Instead of having a progress bar, mops now clean instantly and have a 1 second cooldown afterwards.
This is much nicer to use, in my opinion. It adds a lot more utility, allows for NINJASLIPS, and allows you to mop a little faster unless you're trying to deal with an entire 3x3 area of gunk. It will be slightly slower in that case, since you can't parallelclean.
Also added sounds to it.
I really, really, really like how the mop feels to use now.

:cl:
 * rscadd: Added mop and mopbucket sounds.
 * tweak: Mops now clean instantaneously, but have a 1 second cooldown.

### CODE REVIEW

**Comment by Dacendeth** [comment]
This be crazy good when you coat your mop with lube/thermite.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Not sure if thermite would work and you usually don't thermite more than 1 or 3 walls at once, lube for sure but no more than a spraybottle

**Comment by bathosbathtime** [comment]
I'll miss parallelclean but this seems to be some love to the mop that is sorely needed.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Now you have clean durifto so it evens out

**Comment by Blithering** [comment]
Sneaky mop nerf, can't be clean multiple tiles at once anymore

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
I did mention that in the OP, though
It's not a nerf somuch as a tradeoff and in my opinion it's a buff for average use

**Comment by DeityLink** [comment]
Believe it or not, it's a feature I had in my TODO backlog for ages, ever since I played Viscera Cleanup Detail, good on you! 👍

**Comment by Chazach** [comment]
\>introduce massive blood piles
\>change mop to become pure griff tool instead of corridor cleaner 

sasuga voxman

**Comment by DeityLink** [comment]
>implying that using it won't feel much better now.

**Comment by jknpj** [comment]
just make this another mop

**Comment by Sooose** [comment]
Even after all this, soap still triumphs.

**Comment by DeityLink** [comment]
rag master-race!
t.bartender

**Pull request merged**
