### PR TITLE
Adds a maptool to convert step_x and step_y

### PR DESCRIPTION
**Pull request by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE**
BYOND's built-in mapping tool only lets you nudge items as step_x and step_y which should never be used, so I made a shitty personal-use script to convert them to the proper variables

### CODE REVIEW

**Comment by Exxion** [comment]
image

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
dreammaker_2018-08-04_20-08-53
dreammaker_2018-08-04_20-09-16
dreammaker_2018-08-04_20-09-33
dreammaker_2018-08-04_20-09-47
dreammaker_2018-08-04_20-09-59
dreammaker_2018-08-04_20-10-24
dreammaker_2018-08-04_20-09-47
dreammaker_2018-08-04_20-10-50
dreammaker_2018-08-04_20-11-05
???

**Comment by Exxion** [comment]
What BYOND version are you on? Because it's adjusting the correct variables for me.

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
512.1425

**Comment by Exxion** [comment]
Try 512.1430. That was the latest version to touch nudging, as far as I know.
Code won't compile on 1438-1444 (current at time of writing), so you can go as high as 1437 if you want

**Comment by I-VAPE-VOX-CLOACA-EVERY-DAY-OF-MY-LIFE** [comment]
Oh I didn't try updating BYOND because this version seemed to be the only one that didn't give me frozen viewport on the live server

It probably works if I update, but w/e consider it a boon for whichever mapper doesn't know to tick nudge as pixels in the future

**Pull request merged**
