### PR TITLE
Bagelstation Update

### LINKED ISSUE #15147: [BAGEL] Medbay needs more cameras
the areas around surgery and aux surgery are lacking in cameras

### PR DESCRIPTION
**Pull request by CptWad**
I keep this bagel FRESH

closes #15147

:cl: 
 * rscadd: General improvements to Bagelstation, such as a new look to botany's biodome and more soundsystems.
 * bugfix: Cleans up a few more Bagel things here and there. Please report any more bugs or weirdness you find.

### CODE REVIEW

**Comment by CptWad** [comment]
there we fuckin go

**Comment by gbasood** [comment]
hello jakmak

**Comment by CptWad** [comment]
Least I got one account

**Comment by SonixApache** [comment]
fix the fukken commit message

**Comment by Unknown-as-Captain** [comment]
It can be fixed when they merge it

**Comment by CptWad** [comment]
wait you guys care about commit messages I just slam my hand on the keyboard

**Comment by Skullyton** [comment]
speaking of slamming hands on keyboards, this good to go?

**Comment by CptWad** [comment]
I mean I see no other bugs up so go for it

**Pull request merged**
