### PR TITLE
R*moves unused duplicate water/welder tank icons

### PR DESCRIPTION
**Pull request by Irradiation**
Woops.

No changelog because it doesn't affect anybody in the game.

[sprites]

### CODE REVIEW

**Comment by DrSnips** [comment]
> error generating diff
Careful now.

**Comment by Irradiation** [comment]
3 spooky 5 me

**Comment by Irradiation** [comment]
Curse you c*llab!

Honestly I forgot those sprites were added by accident, the only people it affects are m*ppers using that new mapping tool or whatever.

**Comment by Kurfursten** [comment]
gonligts..

**Comment by Irradiation** [comment]
Gonfligds...

**Comment by Kurfursten** [comment]
fix conflicts

**Comment by Kurfursten** [comment]
Fix conflicts... or else

**Comment by Kurfursten** [comment]
Let us know if you plan on doing this

**Pull request closed without merging**
