### PR TITLE
Bagelstation

### PR DESCRIPTION
**Pull request by CptWad**
BAGELSTATION ARISES!
Features:

- Off station science department! A Research station, if you will!
- Off station Gulag/perma to shove off all your prisoners!
- Expansive comfy dorms with lockable doors!
- A barber's shop and Traders store!
- Its very own Central Singularity!
- Internal cooling for the AI core! Feel your circuits hum in pleasure!
- Heads of staff with their own personal bedrooms!
- Telescience right next door to the paramedics!
- EVA now contains public Space suits for crew use!
- The biggest chapel on record!
- A comfy large bridge!
- New corpse disposal chute straight to the kitchen!
- Botanies very own Biodome for animal husbandry!
- Mechanics want to make space pods? Now adjacent!
- And much much more!

Merge today!

bagelmap

scisat
image
prisonstation

adds bagelstation aka donutstation that map

proof it works/compiles
image

List of more shit I should do
- [x] Update images with the many microchanges
- [x] Further tweaks as suggested by folks
- [x] This box being checked means that this can be merged

:cl:
 * rscadd: Added Bagelstation, son of Donutstation

### CODE REVIEW

**Comment by CptWad** [comment]
works on my machine

**Comment by BobdaBiscuit** [comment]
>not using suit storage units for the xenoarch anomaly suits

INTO THE TRASH IT GOES

**Comment by CptWad** [comment]
oh sure why not, fixed

**Comment by BobdaBiscuit** [comment]
10/10 - REVOLUTIONISES SPESSMENS

**Comment by Skullyton** [comment]
Press O to pay respects

**Comment by CptWad** [comment]
cool so dont know why travis does not like it but whatever it compiles and plays

Other than that fixed all the woopsies such as lights and APCS. Probably missed like two apcs

**Comment by CptWad** [comment]
>The command "find maps/ -name '*.dmm' -exec cat {} \; | awk '/(step_[xy]|layer) =/ { exit 1 }'" exited with 1.
0.03s$ find -name '*.dme' -exec cat {} \; | awk '/maps\\test.*/ { exit 1 }'

**Comment by CptWad** [comment]
hallelujah

**Comment by Commandersand** [comment]
>xenobio on the roid
SMASHING THAT MOTHERFUCKING POSITIVE EMOJI BUTTON

**Comment by Shadowmech88** [comment]
I don't know what shape that is, but it's not a bagel.
It's more like a square with a bump in the middle.

**Comment by CptWad** [comment]
its a bagel because its not a donut
thats the joke
also because squasheddonutstation is too long

**Comment by SarahJohnson489** [comment]
Toxins could use 4 more oxygen canisters. It's pretty easy to run out of just 4 when you're experimenting even when using a mixer to reduce waste. It also badly needs 3 more portable air pumps for handling small quantities of gas. Being on an outpost it's a much bigger headache to go loot and push them from the station. Also replace the 2 rtables with regular tables. They had no reason to be rtables other than to get in your way and waste your time when you need them moved to store your various cans for a multistep mix. A pipe dispenser will let them get right into getting all their pies in the oven while they can go and make an rpd if they need to really go to town with whatever theoretical yield increase idea they wanted to test.

**Comment by carshalash** [comment]
Ya know since nobody else has bothered asking yet.

Why is there a tajaran in lingerie in maint?

**Comment by Praecordia** [comment]
why wouldn't there be?

**Comment by carshalash** [comment]
The real question is if its female or female(male)

**Comment by Skullyton** [comment]
>There's a honkmech wreckage in the wall

HARM ALARM

**Comment by Fruktlimpa** [comment]
The cloner is lightyears away from the tubes.
But that CMO office is making me moist. Truly an office befitting of the most important head role.

**Comment by SarahJohnson489** [comment]
Clearly so you can steal its genomes and force fur the station.

**Comment by Megamaw** [comment]
revival of a classic

i as a player will commit to giving as much constructive feedback as possible once i've actually played an actual round on it

**Comment by liltiptop** [comment]
>that engineeirng

it's fucking perfect
bless you wad

**Comment by Gunosaguki** [comment]
I'm always a fan of perma being seperated from the station. and having rocks to mine for maximum RP

**Comment by Durgen** [comment]
where does the tradership dock? I don't see any south facing ship docks.

**Comment by CptWad** [comment]
Docks dont need to be same direction

**Comment by Diavill** [comment]
So how do you escape this perma; can you just dig your way out or is this finally the one permanent confinement?

**Comment by Durgen** [comment]
so the trader dock is the far north double doors? Would it be possible to swap it for one of the closer, and lesser used docks? The farther away from the action the trader dock is, the less traffic they get.

**Comment by CptWad** [comment]
@diavill
image
@Durgen 
image

**Comment by CptWad** [comment]
ok that should account for 90 of the inital bugs
been trying to get it on the test serb with no success.

**Comment by LordMyroc** [comment]
>all heads of staff get their own personal bedroom
except for the CE who just gets a bed and a curtain shoved in a corner in their office

Discrimination, I say.

As for actually serious feedback, I think maintenance could stand to have a few more external airlocks, there is not a single one to be found in the south part of the station that aren't part of solars or engineering. The other maps tend to have a few more in addition to those.

Other than that, this map looks fucking radical.

**Comment by IratePirate** [comment]
>Engineering toilets

I like this map.

**Comment by JustSumBody** [comment]
Did some local testing of my own with others to give it a look, here's an imgur album
http://imgur.com/a/8kMNo
Things of note:

Misaligned APCs and wall mounted things(lightswitches, brig timers)
In addition: Individual dorm rooms are missing lights(a lamp would probably be fine)
unisex bathrooms,lockerrooms,  gateway, and dorms toilets are missing lights 

The button for what I presume to be used for unlocking the medbay EVA in the CMO's office doesn't seem to work

Research shuttle dock should probably be using an external airlock
Ditto with the MoMMi nest airlocks
Vault door is not bolted by default

Prisoner shuttle doesn't seem to be linked to either prison shuttle console
Vox trade shuttle doesn't dock correctly unless you set it to destroy_everything, and then it docks in the wrong direction(see album)

Some delivery windoors are in the wrong spot(off the top of my head Janitor's and science's)

**Comment by CptWad** [comment]
some changes since last

image

>vox shuttle doesnt turn

wew
image

**Comment by Shadowmech88** [comment]
So, clearly a singuloose is always going to have a 100% chance of resulting in a shuttle call.
Is this a feature, or should there be a button in the CE's office to drop the entire center of the station to another Z-level in case of singuloose?

**Comment by Kurfursten** [comment]
Even if you witnessed the singuloose happening, the odds that you could sprint to the CE office and hit the button before it got free of the center seems rather low. In the old checklist Issue I suggested replacing the center singularity with a shield generator room, since that works perfectly with the circle shape of the station.

The truth is that it would be suicidal to use the central singulo on this map, no matter how much of a reference it is to the original.

**Comment by Shadowmech88** [comment]
Maybe not before it's free of the containment field, but as long as no one's using a singulo beacon, I would think you could make it to the office before it wandered much farther than the emitters.
You could just make the button drop out everything in the center that isn't a part of the station interior, plus the PA room.

**Comment by Durgen** [comment]
maybe embed a few bags of holding in the r walls around containment

**Comment by Shadowmech88** [comment]
People would break into the walls to steal the bags.
If you were going to go the automatic-containment route, it'd be better to make new objects which affected singularities in the same way, and put those around its containment.

**Comment by Commandersand** [comment]
Why not have the ce start with a bag of holding instead of the belt only on this map

**Comment by Blithering** [comment]
Maybe a dummy item that has the same effect when a sing eats it, so people don't dig out the bags for themselves?

**Comment by CptWad** [comment]
works for me
but lets least let it loose a few times for old times sake :wink:

Also I updated this fuckhuge piece of shit
bagelmap

**Comment by CptWad** [comment]
Im gonna give this till the 20th then fix the DME for merging. A week is good yes? Even while testing and ironing this out?

**Comment by Kurfursten** [comment]
No wire into the radio transmitter room
Tiny mainbrig cells are gonna be annoying to use, it was a big complaint on the original Taxi
Since you're giving the janitor a roomba, chef a RAMsay, sec an ED209, I suppose you may as well include a dracula in medbay

These are all tiny tweaks though, you've already made the bulk of changes I could point out. Good work with your persistence. I still think the asteroid content could use an overhaul, but at this point you're probably too exhausted to continue mapping original stuff. Maybe someone will come along and revise it later.

**Comment by CptWad** [comment]
Asteriods i feel is pretty original. The mining quarter is the same but the roid, gulag, voxpost and scisat have a bit of work done. And yeah later on i can revamp things but the works draining. 
As for the rest, i can get fixed sooner than later. 
Dunno about the dr acula those are robust when emagged, i fear them more than a singlo in the center.

**Comment by SarahJohnson489** [comment]
Singuloose isn't a big deal. Crate the bags into it, glass off the breach then start putting things back together again. If you do somehow accomplish losing cargo, tech storage, and science just go salvage the derelict since you'll probably need another oxyminer too. Diona brainswap or MaMMI posibrains into human bodies for anyone that got sucked off by the goose, posi the dead borgs that want back then go on with life.

**Comment by Shadowmech88** [comment]
Theoretically a singuloose could be managed, but practically I doubt anyone is going to bother when they could just call the shuttle instead.

**Comment by Kurfursten** [comment]
Singuloose is a lot less dangerous on Box/Meta since there's about a 60% chance it fucks off to space eating nothing but engineering, and even then might leave behind an engine or the SMES and most of atmos. There's nearly a 25% chance that research gets eaten before anyone is warned to print bags on this station.

But y'know, we can trial it a while. If it ends up being too frustrating people will just stop using the singulo or there will be player demand to change the central chamber. Honestly, it's not something I'm too worried about because it's one of those things where if it turns out to be a big problem, there will be a lot of support to change it. Small things, like an awkwardly shaped hall, are harder to rally support for.

**Comment by Orangerush** [comment]
Bagelstation?? Oy vey!!!

**Comment by Blithering** [comment]
I would prefer the anti-singulo system having to be manually fired, rather than just embedded in walls, as it gives the players the responsibility of preventing the singuloose rather than just leaving it to sort itself out, and antags the agency to sabotage it (Putting a shard on the launch pad in place of the singularity detonator and letting the CE seal his own fate would be a fun example)

**Comment by Shadowmech88** [comment]
~80% of the time a singuloose is going to be caused by an antag.
If the antag can break down a single rwall and remove the countermeasure, there's not a whole lot of point to having it.

**Comment by Durgen** [comment]
it would probably have to be surrounded by 5 or 6 counter measures

**Comment by Kurfursten** [comment]
We need a singularity transmitter

>When activated, sends a nearby singularity to a different Z level at random (never Z2). Somebody else's problem now!

**Comment by Fruktlimpa** [comment]
Maybe we should trial it first. Even on box the singularity being loosed is an instant shuttle call 90% of the time, even when it "just" eats engineering and a bit of atmos.
Yes, a loose on bagel will probably ALWAYS result in a shuttle call but still. Just make anyone who enters the singularity area after it is set up validsalad, then the validhunters will defend the singu.

**Comment by CptWad** [comment]
that is indeed one of the larger points, if you loose it it has to be at your own expense
also heres for kurfurst 
image

**Comment by CptWad** [comment]
bonus
image

**Comment by Kurfursten** [comment]
Gee Bill how come your brig stocks TWO battering rams?

**Comment by kilozombie** [comment]
The reinforced wall beam above the singulo is still off by one tile.
Until you fix this, your space game privileges are suspended

**Comment by Chazach** [comment]
Could you replace that lone spare cuff in the officer spawn with a box of them, and maybe a flashbang box if you feel so kind? Apart from that the brig looks pretty nice and the whole station too

**Comment by CptWad** [comment]
done
?
image

done

**Comment by kilozombie** [comment]
yeah the scaffolds are offset by 1 equally on each side
the beams are otherwise centered on the singulo generator itself

**Comment by CptWad** [comment]
Yes and?

**Comment by ihadtoregisterforthis** [comment]
The beams are aligned to the singularity because it's the main attraction. The generators are in a swastika because otherwise they form four small squares

**Comment by Durgen** [comment]
bagel on the test server when

**Comment by CptWad** [comment]
image

**Comment by Shadowmech88** [comment]
@Durgen 
Ask one of the collabs in the Discord to testmerge it, it'll get loaded onto the PR test server.

**Comment by Blithering** [comment]
I may be blind, but does bagel not have any escape pods?

**Comment by CptWad** [comment]
Engineering.
Sci outpost
Sec outpost

**Comment by Kurfursten** [comment]
It has no public pods and only one on-station pod.

**Comment by CptWad** [comment]
image
heres your public pod, this really is the only open space left for it

**Comment by kilozombie** [comment]
@ihadtoregisterforthis before the top beam was 1 tile to the left of being aligned with the singularity generator (and instead centered on the scaffold)
now it fix

**Comment by Arthurdentist** [comment]
might be a bit of an odd suggestion but in surgery I think it would be much better if you swapped anesthetics locker with the space cleaner table, then had all the tools spawn on the tables in the blue rectangle I've indicated below.
surgery
This'd enable a doctor to stand directly beneath the surgery table and grab all of his tools without moving. Currently you'd have to stand in the corner which just seems a bit weird to me.

**Comment by CptWad** [comment]
image

**Comment by DamianX** [comment]
Chemistry could use a screwdriver to make grenades, all other maps have it, I think.

**Comment by CptWad** [comment]
screwdriver: Placed
dick: out
map: Updated

**Comment by CptWad** [comment]
cool one last checkover and things look great. Thanks for the help yall

**Comment by Wizardcrying** [comment]
@CptWad DNM?

**Comment by CptWad** [comment]
Duh

**Comment by CptWad** [comment]
habbening

**Comment by Durgen** [comment]
https://github.com/vgstation-coders/vgstation13/issues/14859

**Pull request merged**
