### PR TITLE
Brig Medics spawn with medic armor instead of paramedic vest

### PR DESCRIPTION
**Pull request by tinysaturn**
[tweak]
## What this does
Changes the roundstart loadout of Brig Medics to medic armor (added in https://github.com/vgstation-coders/vgstation13/pull/29642) instead of the standard paramedic vest
It also moves the penlight from the suit storage into the right pocket

## Why it's good

seccies get into more violent situation and I think it's better for the role/alt. title, which is more closely aligned with security, to have default gear which makes them a little tougher and not just die the moment they get hit by a stray slug during a cargo raid for example

## Changelog

:cl:

 * tweak: Brig Medics now spawn with medic armor

### CODE REVIEW

**Comment by ManopolisJones** [comment]
Tohoho, talk about a feature I never would have guessed with that green crayon on the armor vest. Anyway I can hardly see the problem with this, we never seen the medic vest used as it is.

**Comment by pedr69** [comment]
i crafted the medic vest as a secoff once

**Comment by tinysaturn** [comment]
> i crafted the medic vest as a secoff once

firefox_VbNGwPv0DL

**Comment by Hinaichigo** [comment]
Sec powercreep.

**Comment by Apogee-dev** [comment]
back when i coded in brig medic (which, in retrospect, was a mistake), i left out the armor vest mostly because i didn't want to play them up as a combat alt title (this is the same reason they don't get sunglasses by default). The other reason is that the vest, even when reskinned to a medic vest, can't hold certain medical items like the M.O.T. that can be fairly important for a paramed.

**Pull request merged**
