### PR TITLE
Overdue Bagelstation bugfixes

### LINKED ISSUE #15001: Bagel vox outpost
There's a dead APC in the hallway near engineering

There are no lights in the antechamber to the tarjan genetics room.

There was also an air alarm with no power somewhere.

### LINKED ISSUE #15009: Bagel: engineering oversights
These meters could/should be assigned a name and frequency
dreamseeker_2017-05-24_11-42-56 dreamseeker_2017-05-24_11-42-30

The SME computer is not linked to the injectors in the chamber, I feel like it should be?
dreamseeker_2017-05-24_11-43-42

### LINKED ISSUE #15041: [BAGEL] another reversed intercomm
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

3b727e7bfb1e89d66fcc4faa450118ffc43f6684 

>General description of the issue

https://puu.sh/w1Xiu/c5f80eb126.png

### LINKED ISSUE #15052: Bagel: Paramedic APC placement
How did no one report this already?
image

### LINKED ISSUE #15058: missing pipe in bagel atmos
missing pipe in bagel atmospherics

### LINKED ISSUE #15063: [BAGEL] Aft Port Solar Control computer isn't wired.
(WEB REPORT BY: sonixapache REMOTE: 172.93.109.202:7777)
>Revision (Should be above if you're viewing this from ingame!)

32b39d13bf6bc22284abcec26abe4e35c7e30181 

>General description of the issue

https://puu.sh/w3Qcf/9b89924f9b.png
The computer doesn't come with wires under it. (Computer is wired in this picture.)

### LINKED ISSUE #15119: [Bagel] cargo has no shuttle timer display
WAAAAD

### LINKED ISSUE #15129: BagelStation - Intercoms in Detective's Office start toggled on
(WEB REPORT BY: wulfel REMOTE: 172.93.109.202:7777)
The intercoms in the Detective's Office on BagelStation are toggled on by default, meaning if the detective sits as his desk and starts chatting on Security comms, the whole station will hear it.

### LINKED ISSUE #15131: BagelStation - Intercom starts on
(WEB REPORT BY: wulfel REMOTE: 172.93.109.202:7777)
The intercom to the southeast of the Chapel, by a vending machine, starts turned on.

### LINKED ISSUE #15145: [BAGEL] No hand labeller in the brig
#### Description of issue
How can I tag my locker without a labeller?

#### Server revision
74db1fa3b9682139521d69a1159523ea63c491a8

### LINKED ISSUE #15146: [BAGEL] External airlocks near brig are inaccessible to sec
#### Description of issue
The ones in maint around the brig. Should give them external access *or* sec access requirements, so officers don't have to walk around to arrivals to leave.

#### Server revision
74db1fa3b9682139521d69a1159523ea63c491a8

### LINKED ISSUE #15183: bagelstation chapel disposal unit
(WEB REPORT BY: cmdrstupid REMOTE: 172.93.109.202:7777)
Revision: c1141f9ef54061ddb0cd70005e97e23523b90bc8

Bagelstation chapel disposal unit is not functioning correctly.

Flushed garbage to enter the disposals system.

Flushed garbage is immediately thrown back out of disposal.

To reproduce, just throw something in and flush.

### LINKED ISSUE #15212: Det can't open one doors in brig, but can open all the other doors leading to the same place
(WEB REPORT BY: moltevolte REMOTE: 172.93.109.202:7777)
http://prntscr.com/fiz3v2 take this screenshot as a description, it's more descriptive than how I can describe it myself

### LINKED ISSUE #15294: Bagelstation HoS has a holodeck button instead of keycard authenticator
You can't go code red with the holodeck please
@CptWad

### LINKED ISSUE #15340: Bar vent pump #3
(WEB REPORT BY: zushakon REMOTE: 172.93.109.202:7777)
>Revision c8ab2aa22449e87b6463b560370143c893e0cf80 
>General description of the issue
Its not connected to pipes since it was placed in the wrong way

This is on bagel map
https://puu.sh/wBSaG/2f0563adb4.png

### PR DESCRIPTION
**Pull request by CptWad**
Welcome to the PR thats way too late, sorry

closes #15001
close #15009
closed #15041
fixed #15052
fixes #15058
solves #15105
fixed #15340
fixed #15183
fixed #15063
closes #15119
(Also generally improves the cargo situation)
closes #15145
closes #15129
close #15131
close #15212 
close #15146
close #15294
(did a hard replace on all the intercoms so they should be FUCKING GONE)

:cl:
 * tweak: Bugfixes to Bagelstation long overdue
 * tweak: Slight updates to map due to recent additions at the time, IE barbervend and glass floors

### CODE REVIEW

**Comment by gbasood** [comment]
praise be

**Comment by Exxion** [comment]
Just to make sure, you redid all of this in the map editor and didn't just copy your old changes and remove the barber stuff, right?

**Comment by CptWad** [comment]
I deleted the barber pr. so yes

**Comment by CptWad** [comment]
\>compiles

I am honestly suprised

**Comment by Exxion** [comment]
Why wouldn't it?

**Comment by CptWad** [comment]
because im both unlucky and a fuckup
otherwise, that was fast
woohoo

**Comment by SonixApache** [comment]
image
😐

**Comment by gbasood** [comment]
gross

**Comment by Exxion** [comment]
Honestly I can only blame GitHub for not naming merge squashes after the PR

**Pull request merged**
