### PR TITLE
literally replaces all solo antag objectives with "Do as you like."

### PR DESCRIPTION
**Pull request by Allspice**
…st bee yourself" (#19485)" (#19487)"

A decent idea was undone due to shenanigans. Might as well give it a legitimate shot.

:cl:
* rscdel: "Removes" solo antag objectives.

### CODE REVIEW

**Comment by Exxion** [comment]
Use a non-meme sentence.
Also stop these stupid fucking revert wars.

**Comment by Allspice** [comment]
Not a war; while the precise phrasing of the change was a bit dubious, it seems to have been reverted primarily due to the whole speedmerge dealio. I can respect that. So I'm interested in getting this merged properly without taking shortcuts, in accordance with the first revert's reasoning.

**Comment by PJB3005** [comment]
A proper way to do this is being discussed in #19489, and the ideas in there are already 10x better than a single non-objective. Don't rush it.

**Comment by Exxion** [comment]
I'd reopen this PR if you just changed the phrase from "Just bee yourself" to something less stupid, and changed the title to reflect it
I wouldn't support it, mind you; I'd rather see what happens in #19489 and go from there, but I'd reopen it

**Comment by bathosbathtime** [comment]
I don't think this will do much as solo antagonists that only follow the objectives and do nothing else may just do nothing now, as well as new friends not having the initial push to do anything when they are unsure of what to do.  I personally think that our current objectives can be too boring and I don't see having them replaced with a non-goal fixing anything.

**Comment by MadmanMartian** [comment]
I can probably set up some form of story generator if that is what people want

"You were [pick(wronged)] by [pick(potential_targets)], treat /him in kind."

**Comment by Blithering** [comment]
I'm not a fan of removing objectives, players aren't forced to attempt them as bit stands, and for those that do, removing the prompts won't motivate them to be any more bombastic and interesting antagonists than before

**Comment by SonixApache** [comment]
this is probably the best solution to tide the serb over till datums

**Comment by MadmanMartian** [comment]
I'd argue having it being a config.txt thing over being in setup.dm

**Comment by yclatious** [comment]
If you are going to be vague, be vague with flavor. If you are going to remove objectives, write it decently and with enough ic as to not literaly be a ooc message saying "do whatever faglord, you got your antag token", take one of my prompts or someone elses.

Whether or not if it should be vague to begin with, whether or not if we should remove objectives as a whole, dont matter for the scope of the convo, its outside of this pr, but atleast give enough of a shit you write more than "Do as you like", atleast give a semblance of ic in it, use something akin to what I wrote in #19489.

Im agaisnt forced stories or anything of the kind for objectives, and I dont see a single thing wrong with adding this in pre datums. Its essentialy just some text change, but even if its a text change, it can be done better, itl just take you 5 minutes to write some text thats atleast half assed ic.

Or just ignore me.  Either or, really.

**Comment by Kurfursten** [comment]
>It is time to pay your debt to the Syndicate. Disrupt Nanotrasen research, commerce, and workflow by any and all means you see fit.
>Varied adversity is required for adaptation and evolution. Create chaos and test the limits of your powers in unusual ways so that the Hive genome can grow toward perfection.
>The Masquerade has officially ended. After years of tedium, the time to embrace wild abandon and create chaos is upon you.
>You are a wizard and therefore have no sense of right or wrong.

**Comment by SonixApache** [comment]
@Kurfursten make the PR

**Comment by jknpj** [comment]
If you're willing to fix the conflicts, ping me or whatever

**Pull request closed without merging**
